### ISSUE TITLE
HTML comments don't look like comments anymore.

### ISSUE THREAD

**Issue by sanket-bhalerao** [angular/vscode-ng-language-service#591] opened 2020-01-29 09:12 UTC
Issue Type: <b>Bug</b>

the comments in the html in an angular project do not look like comments.
it looks like plain code.

![image](https://user-images.githubusercontent.com/9264813/73342930-98464300-42a5-11ea-92d2-d841cb4c56ad.png)

Extension version: 0.900.7
VS Code version: Code - Insiders 1.42.0-insider (be9c72410acc677070685a616773b122f4c5e141, 2020-01-29T05:39:07.145Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.15.0-65-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (1.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: angular_serve|
|OS|Linux x64 4.15.0-65-generic|
|CPUs|Intel Xeon E312xx (Sandy Bridge, IBRS update) (4 x 2399)|
|Memory (System)|7.79GB (3.03GB free)|
|VM|0%|
</details>

**Comment by ayazhafiz** [comment] 2020-01-29 15:58
Can you provide a minimal reproduction of this? I am unable to see this with the template

```html
<button mat-icon-button (click)="printDay(day)">
  <mat-icon>people</mat-icon>
</button>
```

In either an inline or external template. If there are other highlighting errors in the template, they may be impacting this.

**Comment by sanket-bhalerao** [comment] 2020-01-30 07:28
it seems I am not able to replicate this now.
however, yesterday (while raising this) I tried to cross out all the other cases like,
1. reloading vscode.
2. restarting vscode
3. disabling other extensions to find the extn causing this.
4. creating a new project and trying the same thing in it.
and it had the issue at all the places.
it's not today.

**Comment by sanket-bhalerao** [comment] 2020-01-30 10:43
@ayazhafiz 
found something regarding the bug
the *ngFor is expecting to end with a ";"
`*ngFor="let range of day.ranges; let whichIndex = index;"`
without the ";" in the end,  the comment does not appear proper, attribute and their values change color.
without ";" -> 
![image](https://user-images.githubusercontent.com/9264813/73442650-39eb9400-437b-11ea-90ee-c9cdbef2c6df.png)

with ";" ->
![image](https://user-images.githubusercontent.com/9264813/73442678-496add00-437b-11ea-9430-a3e35417dc16.png)

**Comment by jsangmeister** [comment] 2020-01-30 10:54
Having the exact same problem right now: If a structural directive contains a ';' but doesn't end with one, the syntax highlighting breaks and, whats even more annoying, VS Code seems to think that the HTML after that ist still javascript so it will insert '//' when commenting code out.

**Comment by sanket-bhalerao** [comment] 2020-01-30 14:16
if you have linting enabled with eslint it removes the ";" every time 🤣

**Comment by ayazhafiz** [comment] 2020-01-30 16:30
In this case it seems like the issue is the same as #575. Marking as duplicate to track there. If you find a bug with another root cause, feel free to open a new issue.

**Closed by ayazhafiz** 2020-01-30 16:30 UTC
