### ISSUE TITLE
[version 0.1.5] SERVER ERROR: Cannot find module 'minimist'

### ISSUE THREAD

**Issue by Avadesign-David** [angular/vscode-ng-language-service#142] opened 2017-08-05 08:15 UTC
I got this error when using new version of release v0.1.5. This error did not appear in my project when using previous version 0.1.4.

```
SERVER ERROR: Cannot find module 'minimist'
Error: Cannot find module 'minimist'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at $getModule (/Users/apple/.vscode/extensions/Angular.ng-language-service-0.1.5/server/node_modules/@angular/language-service/bundles/language-service.umd.js:10:55)
    at Array.map (native)
    at module.exports (/Users/apple/.vscode/extensions/Angular.ng-language-service-0.1.5/server/node_modules/@angular/language-service/bundles/language-service.umd.js:16:46)
    at CompilerService.resolveLanguageServiceModule (/Users/apple/.vscode/extensions/Angular.ng-language-service-0.1.5/server/editorServices.js:1782:22)
    at new CompilerService (/Users/apple/.vscode/extensions/Angular.ng-language-service-0.1.5/server/editorServices.js:1746:24)
    at new Project (/Users/apple/.vscode/extensions/Angular.ng-language-service-0.1.5/server/editorServices.js:702:36)
[Error - 4:06:03 PM] Notification handler 'textDocument/didOpen' failed with message: Cannot find module 'minimist'
Search path: /Users/apple/Desktop/lesson/forms-reactive-start/node_modules/@angular/cli/plugins
Config file name: /Users/apple/Desktop/lesson/forms-reactive-start/tsconfig.json
SERVER ERROR: Cannot find module 'minimist'
Error: Cannot find module 'minimist'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at $getModule (/Users/apple/.vscode/extensions/Angular.ng-language-service-0.1.5/server/node_modules/@angular/language-service/bundles/language-service.umd.js:10:55)
    at Array.map (native)
    at module.exports (/Users/apple/.vscode/extensions/Angular.ng-language-service-0.1.5/server/node_modules/@angular/language-service/bundles/language-service.umd.js:16:46)
    at CompilerService.resolveLanguageServiceModule (/Users/apple/.vscode/extensions/Angular.ng-language-service-0.1.5/server/editorServices.js:1782:22)
    at new CompilerService (/Users/apple/.vscode/extensions/Angular.ng-language-service-0.1.5/server/editorServices.js:1746:24)
    at new Project (/Users/apple/.vscode/extensions/Angular.ng-language-service-0.1.5/server/editorServices.js:702:36)
[Error - 4:06:04 PM] Notification handler 'textDocument/didOpen' failed with message: Cannot find module 'minimist'
Search path: /Users/apple/Desktop/lesson/forms-reactive-start/node_modules/@angular/cli/blueprints/ng/files/__path__/app
Config file name: /Users/apple/Desktop/lesson/forms-reactive-start/node_modules/@angular/cli/blueprints/ng/files/tsconfig.json
SERVER ERROR: Cannot find module 'minimist'
Error: Cannot find module 'minimist'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at $getModule (/Users/apple/.vscode/extensions/Angular.ng-language-service-0.1.5/server/node_modules/@angular/language-service/bundles/language-service.umd.js:10:55)
    at Array.map (native)
    at module.exports (/Users/apple/.vscode/extensions/Angular.ng-language-service-0.1.5/server/node_modules/@angular/language-service/bundles/language-service.umd.js:16:46)
    at CompilerService.resolveLanguageServiceModule (/Users/apple/.vscode/extensions/Angular.ng-language-service-0.1.5/server/editorServices.js:1782:22)
    at new CompilerService (/Users/apple/.vscode/extensions/Angular.ng-language-service-0.1.5/server/editorServices.js:1746:24)
    at new Project (/Users/apple/.vscode/extensions/Angular.ng-language-service-0.1.5/server/editorServices.js:702:36)
```

**Comment by AlexMcArdle** [comment] 2017-08-07 16:24
Same on Windows.

**Comment by Meligy** [comment] 2017-08-09 01:02
Same on Windows 8.1, using the VSIX from the Releases tab (the version didn't seem to show up in the extension gallery for me).

**Comment by cyrilletuzi** [comment] 2017-08-09 12:19
Solved by angular/angular#18532, now I suppose we have to wait the next patch or beta release of Angular so the VS Code extension could be fixed too.

**Comment by rdzidziguri** [comment] 2017-08-12 18:46
Same here Windows 10 VS Code X64

`Search path: c:/Users/Rati/Desktop/New folder (3)/MyApp/src/app
Config file name: c:/Users/Rati/Desktop/New folder (3)/MyApp/tsconfig.json
SERVER ERROR: Cannot find module 'minimist'
Error: Cannot find module 'minimist'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at $getModule (C:\Users\Rati\.vscode\extensions\Angular.ng-language-service-0.1.5\server\node_modules\@angular\language-service\bundles\language-service.umd.js:10:55)
    at Array.map (native)
    at module.exports (C:\Users\Rati\.vscode\extensions\Angular.ng-language-service-0.1.5\server\node_modules\@angular\language-service\bundles\language-service.umd.js:16:46)
    at CompilerService.resolveLanguageServiceModule (C:\Users\Rati\.vscode\extensions\Angular.ng-language-service-0.1.5\server\editorServices.js:1782:22)
    at new CompilerService (C:\Users\Rati\.vscode\extensions\Angular.ng-language-service-0.1.5\server\editorServices.js:1746:24)
    at new Project (C:\Users\Rati\.vscode\extensions\Angular.ng-language-service-0.1.5\server\editorServices.js:702:36)
[Error - 10:42:17 PM] Notification handler 'textDocument/didOpen' failed with message: Cannot find module 'minimist'
Search path: c:/Users/Rati/Desktop/New folder (3)/MyApp/dist
Config file name: c:/Users/Rati/Desktop/New folder (3)/MyApp/tsconfig.json`

**Comment by marcelnem** [comment] 2017-08-15 11:57
Same here Windows 10 VS Code X64. Using 0.1.4 in the meantime. Any workaround for this?

**Comment by startewho** [comment] 2017-08-18 03:57
Same here ,Win10 VsCode X64 extesnion vers0.1.5 .And waiting for the solution

**Comment by ratidzidziguri** [comment] 2017-08-20 20:36
Any update on this? this issue prevents us from using this extension.

**Comment by rdzidziguri** [comment] 2017-08-26 01:02
This is active issue and there is still no update on it.

**Comment by chuckjaz** [comment] 2017-08-28 23:35
Version 0.1.5 was not published to the store because of this issue. I am cutting 0.1.6 to replace it.

**Comment by chuckjaz** [comment] 2017-08-29 00:33
This dependency was removed in 0.1.6. This doesn't fix the issue with 0.1.5 however but I am closing this issue.

**Closed by chuckjaz** 2017-08-29 00:33 UTC

**Comment by Meligy** [comment] 2017-08-29 12:52
Any idea how long it should take for the store to reflect it?

I'm still seeing 0.1.4 at https://marketplace.visualstudio.com/items?itemName=Angular.ng-template

Thanks heaps for this super awesome work by the way :) :) :)

**Comment by jtsom** [comment] 2017-08-29 12:55
For me, 0.1.4 did not auto-update. I had to do a search for "angular language service" to find 0.1.6. Oddly, I still had 0.1.5 installed (but disabled), which I installed directly via the VSIX, and THAT auto-updated.

I removed 0.1.4 and now only have 0.1.6 - which seems to be working, btw.

**Comment by ratidzidziguri** [comment] 2017-08-29 16:26
I downloaded this from this repo. removed old version and installed 0.1.6. I can confirm it is working now (with some minor issues but not definitely related to this topic). properties marked with @input are not filtered based on angular component and instead it shows large list but's different staff so for now great job it works again thank u.

**Comment by Meligy** [comment] 2017-08-31 01:49
For people having issues with versions, THIS might be why:

![image](https://user-images.githubusercontent.com/171637/29902508-fb169112-8e41-11e7-95d0-162c14da24c2.png)

It seems that 0.1.6 is showing as a totally different extension in the marketplace, and the one with 0.1.4 version is of course still the one with most download / stars, and the one that shows up first when you search for the language service.
