### ISSUE TITLE
Support for inline template defined outside component decorator

### ISSUE THREAD

**Issue by mfp22** [angular/vscode-ng-language-service#216] opened 2018-01-19 18:37 UTC
It would be great to get support for a template defined in the component file outside the component decorator, maybe with the type `Component['template']`. I have no idea how this library's magic works, so I don't know if this is possible.

## Why this would be great
Currently the Angular Language Service works for inline templates defined as follows:

```
@Component({
	selector: 'my-component',
	template: `
		<h1>My Component</h1>
		<p>Is cool</p>
		<p>Another paragraph</p>
	`,
	changeDetection: ChangeDetectionStrategy.OnPush
)}
```

But the longer the component template becomes, the more difficult it is to read the important things inside the decorator because you have to check both above and below the template. It would be nice to define the template above so the component decorator is easier to read:

```
const template: Component['template'] = `
	<h1>My Component</h1>
	<p>Is cool</p>
	<p>Another paragraph</p>
`;

@Component({
	selector: 'my-component',
	template,
	changeDetection: ChangeDetectionStrategy.OnPush
)}
```

**Comment by kyliau** [comment] 2018-01-19 19:43
The language service works with external templates defined in `templateUrl`.
For example, you can move your template to `my-component.ng.html` by doing so:
```
@Component({
    selector: 'my-component',
    templateUrl: 'my-component.ng.html',
})
```
Have you explored that option?

**Comment by mfp22** [comment] 2018-01-19 19:45
Yes, but it also works for inline templates, as I said.

**Comment by chuckjaz** [comment] 2018-01-23 23:19
I created https://github.com/angular/angular/issues/21736 to track this.

**Comment by chuckjaz** [comment] 2018-01-23 23:23
The reason we don't support this today is because that the string literal itself tells us nothing about where it is referenced.

There are two ways around this. 

First is just to ask typescript to produce the references to the string and see if any one of them is in a declaration. This is expensive and potentially doubles or triples the amount of work needed to produce diagnostics and completions.

Second, we can ask the static reflector if the local is used in a declaration. The static reflector currently doesn't track this but it relatively simple to add. Since the static reflector has already collect the information about the file to determine if it contains components it could also track this information. This seems like the most likely direction to enable this. This would also mean that we could track this information across files so we don't need to limit it to just in the same file.

**Comment by kyliau** [comment] 2021-01-11 18:27
Duplicate of #80

**Closed by kyliau** 2021-01-11 18:27 UTC
Labels: feature, ivy, lib, tracking in angular
