### ISSUE TITLE
No help when working with templates in monrepos

### ISSUE THREAD

**Issue by Drovosek01** [angular/vscode-ng-language-service#1371] opened 2021-05-20 09:52 UTC
### Description

The project I'm working on is a monorepository with several Angular web applications.

Today I noticed that in the template of one component, the error highlighting does not work for me if I write the wrong field name.

Also later I noticed that moving to the component code doesn't work either, when I hover the cursor over the name of the directive and try to click on it with the Ctrl key held down.

And when I put a couple of square brackets and press Ctrl+Space, so that the autocomplete works and I see what properties are available to me, there are no properties with the @Input () decorator that are declared in the directive code.

Nevertheless, in the template of another component in the neighboring application of this repository, everything works well - there is error highlighting, auto-completion, and a transition to the component code by Ctr+Space.

For all applications, the same settings are written in angular.json and tsconfig are at the root of the mono repository, and each application has its own tsconfig, which simply takes data from the main one.

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [x] Angular Language Service server

## Reproduction

I do not know how to reproduce it

### **Logs**

When I log in to Verbose mode, reloaded VS Code, looked at the 2. html template and opened the log, it had more than 100 thousand lines. Which of these should I post?

### **Screenshots**

![image](https://user-images.githubusercontent.com/29478700/118958496-26967a80-b96a-11eb-84b4-2ac9bb0f5606.png)

![image](https://user-images.githubusercontent.com/29478700/118958526-2dbd8880-b96a-11eb-820d-044acc5ddd57.png)

![image](https://user-images.githubusercontent.com/29478700/118958550-34e49680-b96a-11eb-9e9f-171c748997af.png)

## 🌍  Your Environment
**Angular Version:**
<pre><code>
$ ng version

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.0
Node: 14.15.1
OS: win32 x64

Angular: 11.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: <error>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.8
@angular-devkit/build-angular   0.1102.8
@angular-devkit/core            11.2.8
@angular-devkit/schematics      11.2.0
@schematics/angular             11.2.0
@schematics/update              0.1102.0
rxjs                            6.6.3
typescript                      4.1.4
</code></pre>

Extension Version:
<pre><code>
Angular Language Service: v12.0.1
</code></pre>

VSCode Version:
<pre><code>
Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042
</code></pre>

Operating System:
<pre><code>
Windows 10 Version 20H2 OS Build 19042.985
</code></pre>

**Comment by atscott** [comment] 2021-05-20 18:44
@Drovosek01 Are you able to provide an example project where this isn't working? If you can't share your monorepo, what you can try doing is create a new project use the same directory structure and `tsconfig`s as your monorepo. This should get you to a state where you can reproduce the problem in the new project.

There could be an issue with the build setup, tsconfigs, imports, or something else but it's hard to tell without having a project to debug with. A similar issue was discussed in https://github.com/angular/vscode-ng-language-service/issues/1227#issuecomment-807689533

**Comment by atscott** [comment] 2021-05-26 16:10
Closing since there's not enough information here for us to determine what the issue is. Please feel free to open a new report that includes a project in which this issue can be reproduced and we'll be happy to investigate.

**Closed by atscott** 2021-05-26 16:10 UTC
Labels: bug, needs clarification, needs repro
