### ISSUE TITLE
Colorizing of type script gone when enabling the extension

### ISSUE THREAD

**Issue by mtorgovitsky** [angular/vscode-ng-language-service#610] opened 2020-02-03 16:20 UTC
**Describe the bug**

When enabling /installing the extension, the colors in TS file was gone - see the picture:
https://gyazo.com/9cd8f009abb93c2e057da81ed544833c

**To Reproduce**

**Expected behavior**

**Logs**

Please attach two logs:

1. Console output (Go to toolbar --> View --> Output, and copy the contents)
2. Log file (Path is printed to the console output at startup)

**Screenshots**

![Example Screenshot](./output.png)

**Additional context**

**Comment by ayazhafiz** [comment] 2020-02-03 16:27
Can you please provide a minimal reproduction of this issue, via a code snippet we can copy/paste to see the problem?

**Comment by mtorgovitsky** [comment] 2020-02-03 16:29
Which code snippet?

**Comment by ayazhafiz** [comment] 2020-02-03 16:29
The code that you are experiencing this bug with..

**Comment by mtorgovitsky** [comment] 2020-02-03 16:32
It's ionic with angular ts

**Comment by ayazhafiz** [comment] 2020-02-03 16:49
Can you provide the TypeScript source code that is causing this problem? Without that, it is very difficult to tell what is causing the issue you are seeing.


________________________________
От: Michael Torgovitsky <notifications@github.com>
Отправлено: понедельник, февраля 3, 2020 8:32 AM
Кому: angular/vscode-ng-language-service
Копия: hafiz; Comment
Тема: Re: [angular/vscode-ng-language-service] Colorizing of type script gone when enabling the extension (#610)

It's ionic with angular ts

**Comment by mtorgovitsky** [comment] 2020-02-03 18:57
You see, this code is from my job project, so I cannot provide it to You.
Although, You actually don't need this code because it's not depend on this
specific TS.
It's just a bag that causing for vs code to not colorize the ts file while
the extension is enabled.
In the same time the ext is working, I actually can jump from html template
to related ts.
The only problem that the colors are disappearing while the ext is enabled.

**Comment by ayazhafiz** [comment] 2020-02-04 05:27
Yes, but the problem is likely caused because of something specific in the TypeScript code of your project. It is the extension's bug, but it will be very difficult for us to figure out what is causing the particular issue you are seeing with the wrong coloring without being provided a piece of code that we can copy/paste to reproduce the issue. Would it be possible for you to narrow down the kind of syntax, that when included, causes the coloring bug? We do not need the whole code, just something that shows the where the problem comes from.

**Comment by mtorgovitsky** [comment] 2020-02-04 08:03
How can i know which peace of code You need?

**Comment by ayazhafiz** [comment] 2020-02-04 08:05
You will probably have to do some experimentation. Can you remove code
until the highlighting is correct, and then add it back until the bug
appears again?

**Comment by mtorgovitsky** [comment] 2020-02-04 09:21
Not working
I've deleted several chunks of code - no result.
BUT when I've uninstalled the ext - all works

בברכה, מיכאל טורגוביצקי.
054-5857784
ערוץ שלי לקניות מסין - צפייה נעימה!
<https://www.youtube.com/channel/UCCO2VtbZDRvH0C8DueePK2Q>

**Comment by ayazhafiz** [comment] 2020-02-04 15:32
Can you try disabling all your other extensions? This may be a cause. But without a code that we can use to reproduce the bug you see, there is very little chance for us to find out what the problem is.

**Comment by mtorgovitsky** [comment] 2020-02-04 15:43
I've tried by removing all the extensions and deleting all the data from
VSCODE and also uninstalling vscode.
Your bug happens even when the vscode installed from scratch and there's no
extensions except Angular Language Service.

**Comment by ayazhafiz** [comment] 2020-02-06 15:16
I understand. This is definitely our bug. Unfortunately, without a way to reproduce it, there is no way for us to personally observe it and figure out how to fix it. Without showing what kind of code experiences this bug, there is almost nothing we can do here.

**Comment by GoldMax** [comment] 2020-02-08 08:48
May be this help ...
![problem](https://user-images.githubusercontent.com/3939443/74082222-75c4de80-4a8a-11ea-9561-8c8ac205abb0.png)

**Comment by ayazhafiz** [comment] 2020-02-08 19:48
Okay. @mtorgovitsky is this the same issue you are experiencing? @GoldMax you can resolve this by starting the template code on the same line as the `template: ` key, so like

```
template: `<img *ngIf...`
```

but we can fix this

**Comment by mtorgovitsky** [comment] 2020-02-08 20:21
No, see the gif I've posted

בברכה, מיכאל טורגוביצקי.
054-5857784
ערוץ שלי לקניות מסין - צפייה נעימה!
<https://www.youtube.com/channel/UCCO2VtbZDRvH0C8DueePK2Q>

**Comment by ayazhafiz** [comment] 2020-02-08 20:48
Okay. Without a reproduction we will probably close this issue, since it is impossible to tell what needs to be fixed here.

**Comment by levjad** [comment] 2020-02-10 16:13
I got a similar problem. If the extension is activated, a lot of the syntax highlighting isn't working properly. For me it's happening just in HTML files. Although the file is detected as HTML it's treated as JavaScript file (e.g. if a html tag is commentet out vscode uses '//' instead of ''). If I deactivate the extension everything's working properly.

VSCode Info:
Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Datum: 2020-02-06T10:51:33.119Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
Betriebssystem: Darwin x64 19.3.0

Theme: Atom Dark theme (Although it's happening even with the default theme)

<img width="928" alt="Bildschirmfoto 2020-02-10 um 17 02 59" src="https://user-images.githubusercontent.com/19470048/74166729-5dd69180-4c27-11ea-87e3-69432e0898d7.png">

**Comment by ayazhafiz** [comment] 2020-02-11 16:21
This is a known issue that should be fixed in #609.

As we have not been given a way to reproduce the original issue, I am closing this. If you are facing template grammar issues, please file a new issue, following the bug template that is presented and providing sample code that we can copy/paste to reproduce the issue you are seeing. Without this information, it is very difficult for us to find and fix the problem.

**Closed by ayazhafiz** 2020-02-11 16:21 UTC
Labels: bug
