### ISSUE TITLE
referencesCodeLens + angular template support

### ISSUE THREAD

**Issue by smnbbrv** [angular/vscode-ng-language-service#270] opened 2018-07-11 10:06 UTC
The referencesCodeLens does not take into account the references in angular templates.

![image](https://user-images.githubusercontent.com/13453858/42565080-bedf677e-8502-11e8-968b-97930c459ff4.png)

Is it possible to somehow implement this?

**Comment by michaelsanford** [comment] 2019-09-18 03:23
Seems to be a duplicate of #162.

**Comment by kyliau** [comment] 2019-11-09 00:07
Tracking this in https://github.com/angular/vscode-ng-language-service/issues/162

**Closed by kyliau** 2019-11-09 00:07 UTC
