### ISSUE TITLE
Cannot rename HTML tags

### ISSUE THREAD

**Issue by tophed** [angular/vscode-ng-language-service#1745] opened 2022-08-26 00:05 UTC
# 🐞 bug report

### Description
Same issue here: https://github.com/angular/vscode-ng-language-service/issues/1139
However, I am using Angular 14 (which I believe Ivy is enabled by default) and extension version 14.1

## Bug Type
What does this bug affect

I don't know.

## Reproduction

1. Install the extension
2. Create a new Angular app (my CLI version is 14.1.2)
3. Try to use F2 to rename any tag in app.component.html
4. See error "The element can't be renamed."

**Expected behavior**

Default vscode HTML tag renaming to work.

## 🌍  Your Environment
**Angular Version:**
<pre><code>14.1.0
</code></pre>

Extension Version:
<pre><code>14.1.0
</code></pre>

VSCode Version:
<pre><code>Version: 1.70.2 (Universal)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:37.829Z (1 wk ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.5.0
</code></pre>

Operating System:
<pre><code>macOS Monterey 12.4

Dev Container (cat /etc/os-release):
RETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
</code></pre>

**Comment by atscott** [comment] 2022-09-20 18:33
Closing as unable to reproduce. I attempted this using the steps described and was able to rename the HTML tags.

**Closed by atscott** 2022-09-20 18:33 UTC
Labels: bug
