### ISSUE TITLE
Intellisense works very slowly

### ISSUE THREAD

**Issue by anna-zhernovkova** [angular/vscode-ng-language-service#44] opened 2017-03-17 09:19 UTC
We have a package of about 200 components with 50 attributes in each. Execution of each action takes from several seconds up to a minute.  

The language-service package's version is 2.4.9
Extension version is 0.0.12
Project for reproduce - [intellisense-test.zip](https://github.com/angular/vscode-ng-language-service/files/850042/intellisense-test.zip)

Steps to reproduce:
1. Install packages.
2. Go to src/app/app.component.html.
3. Type "<dx" and press Ctrl+Space <- a delay will occur here
4. Select the "dx-button" component after loading components.
5. Close the new tag and try to type a new attribute for it (for example, "(onClick)") <- a delay will occur.

**Comment by chuckjaz** [comment] 2017-03-29 00:30
PR https://github.com/angular/angular/pull/15543 address this. It should make it to a release by Wednesday or Thursday.

**Comment by chuckjaz** [comment] 2017-04-03 22:26
Improved in `0.1.1`. I will close this for now but I plan to continue to work on performance in this area.

**Closed by chuckjaz** 2017-04-03 22:26 UTC
Labels: bug, tracking in angular

**Comment by nasreddineskandrani** [comment] 2018-09-27 06:43
Hi,
`ctrl + click` is not working proprely (slow) in 3 differents code base i used for 3 real products.
I decided to investigate and i found that the problem is coming from `vscode-ng-language-service` i referenced the issue from vscode repo.

Since i can't share the code of the private repos. I decided to hunt for a way to reproduce it in a public repo and i found one easily.

So the steps to reproduce are:
- clone repo https://github.com/stefanoslig/angular-ngrx-nx-realworld-example-app
- `yarn install`
- did some ctrl + click here and their but what make it hang in an infinit loop is:
-- apps\conduit\src\app\app.component.spec.ts
ctrl + click line 29 the method `detectChanges`

Voila. i don't know for now how i can debug it but if you can't work on it. I can try since it's a problem in angular projects right now that use john papa extension package https://johnpapa.net/essential-angular-vs-code-extensions/ (and it's popular which impact a lot of devs).

**Comment by matheusdavidson** [comment] 2019-01-25 16:30
it is indeed very slow, disabling language service fixes, would like to use it but intellisense is too slow

**Comment by NSExceptional** [comment] 2019-02-10 21:42
Also slow on macOS on the latest version at the time of writing. C/C++.

**Comment by muehlburger** [comment] 2019-02-26 18:45
It's also slow on MacOS on the latest version for writing Go.

**Comment by wbhob** [comment] 2019-05-10 04:48
I still frequently experience this issue with 0.1.11. Are there any plans to dive into this deeper?

macOS 10.14.4
VS Code 1.33.1
NGLS 0.1.11

**Comment by gittar** [comment] 2019-05-19 10:25
same here, makes intellisense mostly unusable. This is i.m.o. more relevant than many other features since it affects basically the whole userbase. Anyone fixing this would be my hero :-)

ubuntu 18.04 LTS
VS Code 1.33.1

**Comment by Yonben** [comment] 2019-05-20 10:17
Same for me. IntelliSense is extremely slow, very very frustrating experience :/

macOS 10.14.4
VS Code 1.34.0

**Comment by wbhob** [comment] 2019-05-20 13:48
@gittar @Yonben how big are your projects? My theory is that it may be a side effect of huge projects (ours has hundreds of components), but it would be interesting if it's happening to you on a smaller project

**Comment by Yonben** [comment] 2019-05-21 07:02
@wbhob Gotta admit I made a mistake. I thought I was in the vscode repo. For me, it's not an angular project... Thanks though, sorry for the notifications :/

**Comment by gittar** [comment] 2019-05-21 10:46
Just a couple of components, really small

**Comment by wbhob** [comment] 2019-05-21 16:54
Ok. My next thought is this is a memory/optimization issue. I typically experience this after openning a few windows and closing them I think; it's intermittent now. @chuckjaz – do you have any news or updates about this performance issue since you last commented?

**Comment by Yonben** [comment] 2019-05-21 17:04
I know my issue wasn't with ng, but I updated to Insiders build and it
fixed my TS Intellisense issue. Worth a try.
