### ISSUE TITLE
Language Service not working out-of-the-box with angular 10

### ISSUE THREAD

**Issue by DibyodyutiMondal** [angular/vscode-ng-language-service#844] opened 2020-07-06 12:07 UTC
**Describe the bug**
This is basically the same as #824

Angular language service plugin does not work in template files (.html) out of the box

**Expected behavior**
Autocomplete feature should ideally be working without extra configuration

**Additional context**
The problem was solved by editing the `tsconfig.app.json`: 
```json
{
    "include": [
        "src/**/*.d.ts",  <= this was generated by the angular cli
        "src/**/*.ts" <= this was added by me, otherwise it would not work
      ]
}
```
However, this results in warnings like: 
![image](https://user-images.githubusercontent.com/50345677/86593995-e1689480-bfb3-11ea-9344-7b3d9744ebd7.png)

PS: Not sure if this should be an issue for the CLI or the language service, but this was basically a continuation of #824, so decided to put it in here.

**Comment by mateusz-pietrzak** [comment] 2020-07-06 15:06
I encountered same problem. It only affects files that are not imported anywhere in the project. As soon as file is included in compilation intellisense picks it up and autocomplete starts to work.

**Comment by DibyodyutiMondal** [comment] 2020-07-07 11:18
I am importing the files but still getting an error.
The entry-point 'main.ts' imports 'app.module.ts' which imports 'app.component.ts' which in turn has the template. The typescript file for the component has autocomplete features etc that works fine. 'ng build' works fine too. Only the template files don't show any kind of autocomplete whatsoever, until I change the 'tsconfig.app.json'

**Comment by kyliau** [comment] 2020-07-10 18:13
this is a duplicate of https://github.com/angular/angular-cli/issues/18040 and it has to be fixed from the CLI side. Please track the progress there.

**Closed by kyliau** 2020-07-10 18:13 UTC
Labels: bug

**Comment by DibyodyutiMondal** [comment] 2020-07-10 19:39
Thank you!
