### ISSUE TITLE
new project html not working!

### ISSUE THREAD

**Issue by zhang-wenchao** [angular/vscode-ng-language-service#1905] opened 2023-07-23 11:21 UTC
```
ng new cc-admin
```

```
cd cc-admin

code .
```

```
[Info  - 7:17:01 PM] Angular language server process ID: 3841722
[Info  - 7:17:01 PM] Using typescript/lib/tsserverlibrary v5.1.6 from /home/life/Develop/job/code/my/learn/cc-admin/node_modules/typescript/lib/tsserverlibrary.js
[Info  - 7:17:01 PM] Using @angular/language-service v16.1.4 from /home/life/.vscode-server/extensions/angular.ng-template-16.1.4/node_modules/@angular/language-service/index.js
[Info  - 7:17:01 PM] Log file: /home/life/.vscode-server/data/logs/20230722T221404/exthost10/Angular.ng-template/nglangsvc.log
[Info  - 7:17:04 PM] Enabling Ivy language service for /home/life/Develop/job/code/my/learn/cc-admin/tsconfig.json.
[Error - 7:17:05 PM] No config file for /home/life/Develop/job/code/my/learn/cc-admin/src/index.html
[Error - 7:17:05 PM] No config file for /home/life/Develop/job/code/my/learn/cc-admin/src/index.html
[Error - 7:17:05 PM] No config file for /home/life/Develop/job/code/my/learn/cc-admin/src/index.html
```

```

Angular CLI: 16.1.5
Node: 18.16.0
Package Manager: npm 9.5.1
OS: linux x64

Angular: 16.1.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.5
@angular-devkit/build-angular   16.1.5
@angular-devkit/core            16.1.5
@angular-devkit/schematics      16.1.5
@angular/cli                    16.1.5
@schematics/angular             16.1.5
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.1
```

```
angular.ng-template v16.1.4
```

[nglangsvc.log](https://github.com/angular/vscode-ng-language-service/files/12138588/nglangsvc.log)

**Comment by zhang-wenchao** [comment] 2023-07-23 11:41
#1901

**Comment by atscott** [comment] 2023-08-29 16:31
Closing as duplicate of #1901. That said, I was not able to reproduce this in a new project.

**Closed by atscott** 2023-08-29 16:31 UTC
Labels: bug
