### ISSUE TITLE
Component not included in a module warning for all components not in root AppModule

### ISSUE THREAD

**Issue by chrissena** [angular/vscode-ng-language-service#10] opened 2016-12-08 20:50 UTC
Hi,

This is looking very promising, can't wait to use it!

I am however having trouble getting this to recognise components that are declared in feature modules (both lazy-loaded and not). All these components have the following warning (with red squiggles under the component decorator). 

 `[Angular] Component 'xxxComponent' is not included in a module and will not be available inside a template. Consider adding it to a NgModule declaration`

This means that in templates (the app.component.html template in the root module is the only one) in this module I can get completion etc. to work for directives that are in the same module and imported angular built-in directives. However directives from my own imported modules i get the following.

`[Angular] 'app-nav' is not a known element:
          1. If 'app-nav' is an Angular component, then verify that it is part of this module.
          2. If 'app-nav' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
`
Have i missed something or is this maybe a bug?

I am very excited to use this. It will make my angular 2 coding experience so much better and hopefully save a lot of time, so thanks!

**Comment by chuckjaz** [comment] 2016-12-08 22:47
It could be a bug but I am not sure. Can you produce a repository that reproduces this issue?

This error is generated when you include a reference to a component that is not included in the the `NgModule` it is declared in or one of the `NgModule`s that is imported by its module.

The language service scans the entire project (everything included by the tsconfig.json) for `@NgModule` declarations and creates a dependency graph between the components and the modules. The first error is generated for components that are not declared in a module and the second is for references to components not reachable from the module the component is in.

**Comment by chrissena** [comment] 2016-12-12 22:14
Just tried in a new angular-cli project but can't seem to be able to reproduce the issue. Not sure if it's a problem that only affects projects over a certain threshold size/module structure. 

The project in which I discovered the issue has 12 modules in total:
- a core module
- a shared module
- 4 feature modules (with some nesting)
- 1 root app module
- 5 routing modules (corresponding to the 4 feature modules and single root app module)

Will have a further look and play around when I get a chance to see if I can discover at what point this is reproduced.

**Comment by petebacondarwin** [comment] 2017-01-23 14:38
I think this might be related to #36

**Comment by chrissena** [comment] 2017-02-11 07:40
I'm still have the same issue with the latest version.

I have managed to narrow down one scenario that causes the bug.
In a simple solution created with the latest angular-cli, I have the following structure

- A root AppModule 
    - An AppComponent 
- A CoreModule.
    - A NavComponent
    - A HomeComponent
    - An AuthService

When I include the AuthSevice in the CorModule's providers array and import the CoreModule into the AppModule I get the following errors.
![coremodule](https://cloud.githubusercontent.com/assets/6528986/22852062/106f9a9a-f02c-11e6-986b-f32b48dcbcfe.jpg)

![navcomp](https://cloud.githubusercontent.com/assets/6528986/22852064/1ee0e1e2-f02c-11e6-8a4b-4f043b4a53e4.jpg)
The same error occurs with the HomeComponent too.

![appcomponent](https://cloud.githubusercontent.com/assets/6528986/22852067/23c57e84-f02c-11e6-9a91-94eb265e9356.jpg)

If I comment out the AuthService from the providers array in the CoreModule the errors go away.
The app works fine though.

I've uploaded the example [to this repository](https://github.com/chrissena/LSExample).

Hope this helps track down the problem.

**Comment by chuckjaz** [comment] 2017-02-21 23:20
Tracked as https://github.com/angular/angular/issues/14631.

This bug will be closed when the fix for the above lands and a new release of `ngls.visx` produced.

**Comment by chuckjaz** [comment] 2017-03-24 22:13
This has been fixed in `0.1.0`

**Closed by chuckjaz** 2017-03-24 22:13 UTC
Labels: bug, tracking in angular

**Comment by veldirre** [comment] 2017-04-11 13:09
Still have the same problem, version 0.1.3

**Comment by jshea** [comment] 2017-04-11 15:30
Just installed 0.1.3 to check out this plugin. Getting the same error on a project that's working fine.

**Comment by chuckjaz** [comment] 2017-04-11 22:54
@veldirre Can you create a separate issue and attach a way to reproduce the issue you are having? This issue has been fixed. You are probably running into a different issue that looks similar.

**Comment by chuckjaz** [comment] 2017-04-11 22:55
@jshea I am not sure I understand you issue. Can you open a separate issue and attach a project that reproduces the issue?

**Comment by tdsmithATabc** [comment] 2017-04-12 16:04
@chuckjaz Are there any debugging methods for investigating this as it occurs? None of my non-route components are recognized as included in the module declaration, but stripping down our production app to a minimal example would be very time consuming (and so far all of the toy versions I've tried to spin up haven't exhibited the problem).

I'll keep trying to make a small reproduction, but if there are any other approaches that would help a lot.

**Comment by tdsmithATabc** [comment] 2017-04-12 16:42
Nevermind. I stumbled upon the problem just a bit after posting: #80.

**Comment by chrissena** [comment] 2017-04-12 16:47
@tdsmithATabc  The initial cause of original issue of this thread is fixed in the latest version 0.1.3. 

However, I did notice I was still getting the same error occasionally for some components. After a bit of investigating I realised these remaining errors were being caused by another separate issue #72. 

Changing references in the offending components to relative paths seems to act as a workaround in the offending components. Not sure if this is the same issue you have but thought I'd mention it here.

**Comment by chrissena** [comment] 2017-04-12 16:48
Ah, just got you last message, nevermind.

**Comment by tdsmithATabc** [comment] 2017-04-12 18:35
Thanks for the tip regardless! I've had some path struggles as well, but that was because our set-up was using _project-relative_ paths which are nice for development but terrible for pretty much everything else...

**Comment by Marcidius** [comment] 2017-04-19 13:06
Upgrading the Angular Language Service from 0.1.2 to 0.1.3 has fixed the issue for me.

**Comment by wbuck** [comment] 2017-05-18 00:56
I'm using Angular Language Service 0.1.3 and I'm still having this same issue.

**Comment by markus-fischbacher** [comment] 2017-08-07 19:52
Any news about that thing?
Still having the issue with 0.1.4

**Comment by ivanlopezmolina** [comment] 2017-09-15 15:45
I was having the same issue

Component 'xxxComponent' is not included in a module and will not be available inside a template. Consider adding it to a NgModule declaration

and while I was researching an reading some threads of pretty much the same issue, the error suddenly (after about 15 minutes) disappeared, I think is more a timing issue when you change/add components

**Comment by DmitryEfimenko** [comment] 2017-10-27 19:53
Still having the issue with 0.1.7

**Comment by josh-strickland-4c** [comment] 2018-02-12 02:18
Encountering this on 0.1.9.

Reproducible by starting new ionic project with the tutorial template and creating a new page which requires the the new page class be declared in the app.module.ts file.

I am able to get this to go away by just reopening the project so not the end of the world, but inconvenient.

**Comment by olehleskiv** [comment] 2018-02-12 21:54
Have this issue on 0.1.9 with Directives

**Comment by andrei0x309** [comment] 2018-02-20 10:54
I can confirm the same behavior as @josh-strickland-4c.

**Comment by LeonardoMinatiCrispyBacon** [comment] 2018-03-07 09:09
I can report this issue with the 0.1.9 version with components.

**Comment by pramodaya** [comment] 2018-06-26 09:34
i got the same error. b/c first i made a component by using "ng g c post "  then i made another folder inside of post, and push all the files was created before and renamed all files, post to post-create. then i got the same error.. even there was an error said by VS code, my chrome console doesn't say anything. and it works. 
![1](https://user-images.githubusercontent.com/19555470/41902916-34374ec2-7952-11e8-9bd3-ab75314e37d5.PNG)

**Comment by baerree** [comment] 2018-09-26 11:57
Still an issue with 2018.2 in a library project (created with angular cli).

**Comment by MikeVoermans** [comment] 2018-09-26 12:57
Same for me in Webstorm Project!

**Comment by miguelms95** [comment] 2018-09-28 22:22
The same problem with WebStorm.
![image](https://user-images.githubusercontent.com/17082987/46236068-78370480-c37d-11e8-9ae8-8e75d60801ca.png)
Angular Cli 6.2.3
Angular 6.1.9
