### ISSUE TITLE
template pipe breaks formatting

### ISSUE THREAD

**Issue by ayyash** [angular/vscode-ng-language-service#613] opened 2020-02-04 09:14 UTC
Writing a template with `*ngif` and an async pipe like this
![image](https://user-images.githubusercontent.com/1110344/73730299-3a02df80-473f-11ea-9247-3b03efd22b1d.png)

Now adding `as var` to the ngif statement, breaks the formatting

![image](https://user-images.githubusercontent.com/1110344/73730391-5acb3500-473f-11ea-9640-c45957e0a6e0.png)

Notice I disabled all extensions first. 
Version: 1.42.0-insider (user setup)  
Commit: 705f01577dd37d6f17eaa683ab89b0c392fa1a7c  
Date: 2020-02-03T14:02:55.075Z  
Electron: 6.1.6  
Chrome: 76.0.3809.146  
Node.js: 12.4.0  
V8: 7.6.303.31-electron.0  
OS: Windows_NT x64 10.0.18362

**Comment by zacnomore** [comment] 2020-02-04 14:50
Possibly a duplicate of #575

**Comment by ayazhafiz** [comment] 2020-02-04 15:44
This is a different bug, but same root problem. There is a massive PR in review right now to hopefully solve existing highlighting problems. We'll keep this issue open as a test case.

**Comment by william-lohan** [comment] 2020-02-06 17:20
I'm experiencing the same issue with the `as` keyword in 

```html
<mat-error *ngIf="form.get('note')?.get('note')?.getError('minlength') as minlength">Minimum length of {{ minlength.requiredLength }}</mat-error>
```

![image](https://user-images.githubusercontent.com/8146733/73961548-ad345f00-48c1-11ea-967b-c4b22d3e75cd.png)
 the syntax highlighting of the rest of the file is all thrown off

**Comment by ayazhafiz** [comment] 2020-02-08 09:51
bcîi hihas yuh h ouihooo hu h

________________________________
От: William Lohan <notifications@github.com>
Отправлено: Thursday, February 6, 2020 9:20:03 AM
Кому: angular/vscode-ng-language-service <vscode-ng-language-service@noreply.github.com>
Копия: hafiz <ayaz.hafiz.1@gmail.com>; Comment <comment@noreply.github.com>
Тема: Re: [angular/vscode-ng-language-service] template pipe breaks formatting (#613)


I'm experiencing the same issue with the as keyword in

<mat-error *ngIf="form.get('note')?.get('note')?.getError('minlength') as minlength">Minimum length of {{ minlength.requiredLength }}</mat-error>

[image]<https://user-images.githubusercontent.com/8146733/73961548-ad345f00-48c1-11ea-967b-c4b22d3e75cd.png>
the syntax highlighting of the rest of the file is all thrown off

**Comment by hoangngk** [comment] 2020-02-16 03:52
Any news on this ?

**Comment by ayazhafiz** [comment] 2020-02-16 04:03
There is an open PR in review at #609.

**Closed** 2020-02-20 16:11 UTC
Labels: bug
