### ISSUE TITLE
This component requires inline template type-checking, which is not supported by the current environment.

### ISSUE THREAD

**Issue by smnbbrv** [angular/vscode-ng-language-service#1154] opened 2021-02-26 09:38 UTC
**Describe the bug**

If a component / directive has a generic type, the following error is shown.

> This component requires inline template type-checking, which is not supported by the current environment.

The error is also shown in the places where this component is used:

> This component uses a directive which requires an inline type constructor, which is not supported by the current environment.

This leads 

- the file with this component 
- the html templates that use this component
- the .ts component files that relate to the html templates that use this component

to be all red.

Removing the generic type "solves" the issue, but actually removes the meaningful part of the type-checking process.

**To Reproduce**

```
import { Component, Input, OnInit } from '@angular/core';

interface Searchable {
  id: string;
  name: string;
}

@Component({
  selector: 'app-select-search',
  template: `
  `,
})
export class SelectSearchComponent<T extends Searchable> implements OnInit {

}
```

**Expected behavior**

Well, would be totally perfect to support it.

While it's not being supported, however, it would be convenient to stop showing it as an error. Maybe some warning in the extension logs would be sufficient.

The fact that the extension does not support yet something does not mean the code is invalid.

**Logs**

```
[Info  - 9:28:28 AM] Angular language server process ID: 17286
[Info  - 9:28:28 AM] Using typescript/lib/tsserverlibrary v4.1.5 from /Users/***/.vscode/extensions/angular.ng-template-11.2.3/node_modules/typescript/lib/tsserverlibrary.js
[Info  - 9:28:28 AM] Using @angular/language-service/bundles/ivy v11.2.2 from /Users/***/.vscode/extensions/angular.ng-template-11.2.3/node_modules/@angular/language-service/bundles/ivy.js
[Info  - 9:28:28 AM] Log file: /Users/***/Library/Application Support/Code/logs/20210225T134851/exthost5/Angular.ng-template/nglangsvc.log
[Info  - 9:28:34 AM] Enabling Ivy language service for /Users/***/tsconfig.json.
[Error - 10:19:37 AM] Script info not found for /Users/***/src/app/common/validators/oneof/oneof.ts
```

**Screenshots**

![image](https://user-images.githubusercontent.com/13453858/109281741-f765e680-781c-11eb-9dbf-156c9522eca6.png)

**Comment by tonivj5** [comment] 2021-02-27 11:40
Rel in Angular's repo https://github.com/angular/angular/issues/40857

**Comment by atscott** [comment] 2021-03-01 19:05
Same issue in the Angular repo https://github.com/angular/angular/issues/40963. I've discussed this with @alxhub, and while the information provided in the error is correct, we should convert it to an informational diagnostic rather than an error and provide clearer information about what's going on here. In short, the compiler is unable to determine the correct types for the component without making inline edits to the existing code and the diagnostic is just letting you know that the type information for the template will be incomplete.

**Comment by AmandavZ** [comment] 2021-03-12 16:24
@atscott - Could you please elaborate on the last part? What is the correct way of extending generics on a class if it is not a bug but informational diagnostics? Is there a workaround other than disable Ivy or removing the extended type?

**Comment by Brandinga** [comment] 2021-03-13 20:18
looks like this gets adressed here: [41043](https://github.com/angular/angular/pull/41043)

**Comment by atscott** [comment] 2021-03-15 16:23
@AmandavZ - As @Brandinga mentioned, this is being addressed in [#41043](https://github.com/angular/angular/pull/41043). There's not an "incorrect" way to write the generic. The compiler generates files for type-checking a component/directive. If it finds that there isn't a reliable way to import they types used in the generic, it instead has to make an in-line edit to the directive's file to export some required information. We can't do this for the language service so we instead have this informational diagnostic to let you know the language service won't have complete type information.

**Comment by AmandavZ** [comment] 2021-03-15 18:05
@atscott  thank you for the explanation

**Comment by atscott** [comment] 2021-03-19 17:59
Fixed by https://github.com/angular/angular/commit/09aefd29045db77689f4dc16a6abae09a79cfb81. This will be included in next week's release.

**Closed by atscott** 2021-03-19 17:59 UTC
Labels: user XP
