### ISSUE TITLE
Type checking of context doesn't work with custom directives

### ISSUE THREAD

**Issue by cbejensen** [angular/vscode-ng-language-service#1302] opened 2021-04-22 21:32 UTC
**Describe the bug**

See #650. I am still seeing a custom directive's context value typed as `any`, but the aforementioned issue has been locked.

When using `ngIf`, the context type is correct. If you create your own directive exactly life `ngIf`, though, the type will always be `any`.

In my case, I am using a `let` directive that works like `ngIf`, except it will always render its template, even if the value is falsy (used for getting values out of Observables). I believe I have type everything correctly (following `ngIf`'s example), but the context type in the template is still `any`.

```ts
interface LetDirectiveContext<T = unknown> {
  $implicit: T;
  fxLet: T;
}

/**
 * Like `*ngIf`, but when you need the variable even if it's falsy.
 *
 * **Example**
 * ```html
 * <my-comp *fxLet="value$ | async as val">
 *   <!-- will work even if `val` is falsy -->
 *   <my-child-comp [input]="val"></my-child-comp>
 * </my-comp>
 * ```
 */
@Directive({
  selector: '[fxLet]',
})
export class LetDirective<T = unknown> {
  
  static ngTemplateGuard_fxLet: 'binding';

  static ngTemplateContextGuard<K>(dir: LetDirective<K>, ctx: LetDirectiveContext<K>): ctx is LetDirectiveContext<K> {
    return true;
  }

  _ref: EmbeddedViewRef<LetDirectiveContext<T>>;
  context: LetDirectiveContext<T> = {} as LetDirectiveContext<T>;

  @Input()
  set fxLet(value: T) {
    if (!this._ref) this.createView();
    this._ref.context.$implicit = this.context.fxLet = value;
  }

  constructor(
    private readonly vcRef: ViewContainerRef,
    private readonly templateRef: TemplateRef<LetDirectiveContext<T>>
  ) {}

  createView(): void {
    this.vcRef.clear();
    this._ref = this.vcRef.createEmbeddedView<LetDirectiveContext<T>>(this.templateRef, this.context);
  }
}
```

**Comment by atscott** [comment] 2021-04-23 16:40
@cbejensen - what `angularCompilerOptions` are you using? Please ensure you have `strictTemplates` enabled. I was not able to reproduce this issue. The correct type is being shown for me when I use the directive in your example:
![image](https://user-images.githubusercontent.com/479713/115902968-e0580500-a417-11eb-805a-affa43241091.png)

**Comment by atscott** [comment] 2021-04-27 16:22
Closing - this appears to be working as intended. I was unable to reproduce the issue.

**Closed by atscott** 2021-04-27 16:22 UTC
Labels: bug, needs clarification
