### ISSUE TITLE
typescript 2.1.5

### ISSUE THREAD

**Issue by fxck** [angular/vscode-ng-language-service#41] opened 2017-01-24 07:49 UTC
Is this supposed to work when VSC is running ts version 2.1.5?

![image](https://cloud.githubusercontent.com/assets/1303561/22238472/d844e1b6-e211-11e6-86d0-83a00c1a0391.png)

It doesn't throw any error, so it's hard to know why exactly is it not working at all..

repro repo https://github.com/katallaxie/angular2-preboot/

**Comment by fxck** [comment] 2017-01-31 13:27
@chuckjaz have you, by any chance, had time to confirm that this is actually a bug, not me doing something wrong? I miss this plugin dearly, it's been huge timesaver.

**Comment by chuckjaz** [comment] 2017-01-31 18:25
A bug: https://github.com/angular/vscode-ng-language-service/blob/master/client/package.json#L5

**Comment by chuckjaz** [comment] 2017-01-31 18:27
The issue is that the tsconfig.json file that is usable in 2.1 is not readable in the bundled 2.0 version of typescript. I was planning on updating the version to 2.1 last week but there was a bug that needs to be fixed in `@angular/langauge-service` that will not be released until tomorrow.

**Comment by fxck** [comment] 2017-02-04 09:17
@chuckjaz was it part of the recent 2.4.6 release?

**Comment by chuckjaz** [comment] 2017-02-05 03:27
Yes. I plan on updating the plugin on Monday

**Closed** 2017-02-07 22:49 UTC
Labels: bug

**Comment by fxck** [comment] 2017-02-08 07:07
It works! Thank you.
