### ISSUE TITLE
Hover over item in html shows multiple tooltip entries

### ISSUE THREAD

**Issue by jtsom** [angular/vscode-ng-language-service#122] opened 2017-06-28 18:19 UTC
Sometime after VS Code is launched, and a project is opened, hovering over an item in an html template will pop up two, duplicate tooltip entries. Sometimes quitting and relaunching VS Code will clear it out, but the problem will eventually popup. 

I do see two getHoverAt: events being displayed in the log, so something looks to be called multiple times.

This is version 0.1.4 of the VS Code extension and the latest VC Code insiders.

**Comment by chuckjaz** [comment] 2017-07-07 17:45
@jtsom @DBosley Can either of you produce a repository that reproduces this issue?

**Comment by pabloxn** [comment] 2017-07-12 09:24
I am getting the same and it eventually crashes VS Code.

**Comment by chuckjaz** [comment] 2017-07-12 16:25
@pabloxn I have not be able to reproduce this. Can you spend some time to produce a repository I can clone that reproduces this?

**Comment by DBosley** [comment] 2017-07-12 16:33
@chuckjaz sorry I haven't built a repro-repo. I'm seeing it in a fairly
large project that I can't share that doesn't use the standard ng-cli
setup. I'll see if I can figure out a way to repro it, but I don't know
what in particular is causing it.

**Comment by DBosley** [comment] 2017-07-12 16:36
I found a repo that has the issue:
https://github.com/AngularClass/angular-starter

Hover over the [routerLink] in barrel.component.ts in the latest source.
![image](https://user-images.githubusercontent.com/2766936/28128740-03164afe-66ee-11e7-8ab2-f1f526a319e6.png)

**Comment by chuckjaz** [comment] 2017-07-12 20:04
@DBosley Thanks for looking into this! Let me know what you have something!

**Comment by DBosley** [comment] 2017-07-12 20:05
I will. This looks like it might be a tricky one to spot.

**Comment by harisb2012** [comment] 2017-07-19 13:27
+1 getting the same issue

**Comment by kyliau** [comment] 2019-11-11 23:38
Closing this, since issue is more than two years old and has since been fixed.

**Closed by kyliau** 2019-11-11 23:38 UTC
Labels: bug, needs repro
