### ISSUE TITLE
Extension stopped working after upgrading to v14.2.0

### ISSUE THREAD

**Issue by darrenw-npi** [angular/vscode-ng-language-service#1770] opened 2022-10-03 13:04 UTC
I have just upgraded my Angular Language Services extension to v14.2.0 from v14.1.0 and the extension appears to have stopped working. When I hold the Ctrl button the Angular components are no longer underlined. Clicking on them does nothing and if I right click and select "Go to Definition (F12)" I get the message "No definition found for...."

This appears to be a regression of the bug
_Originally posted by @kyliau in https://github.com/angular/vscode-ng-language-service/issues/1109#issuecomment-780129761_

Downgrading to any prior version (I have tested v14.1.0 and 13.3.4) resolves the issue so presumably something has snuck back in on this version???

**Comment by atscott** [comment] 2022-10-03 14:22
Since there's not enough information here to know otherwise, I'm closing as a likely duplicate of https://github.com/angular/vscode-ng-language-service/issues/1753.  See https://github.com/angular/vscode-ng-language-service/issues/1753#issuecomment-1252471732

**Closed as not planned by atscott** 2022-10-03 14:22 UTC

**Comment by darrenw-npi** [comment] 2022-10-03 14:48
I think this is the same issue as it's an Angular v8.3.12 project. Sorry, my bad! I only checked for open issues before posting.

**Comment by ghaschel** [comment] 2022-10-06 19:01
Same happening here. Even with *Legacy View Engine enabled*, *Include completion with snippet text disabled* and *Include automatic optional chain completions disabled*
