### ISSUE TITLE
The version  16.0.0 doesn't recognize some components and attributes of external modules. Until 15.2.1 i had no problems.

### ISSUE THREAD

**Issue by sebastiaorabelo** [angular/vscode-ng-language-service#1896] opened 2023-06-14 14:47 UTC
# 🐞 bug report

So far this issue only happened when I forgot to import some components or module on my app.module.ts. But that's a existing project that I only opened on my VS Code and update the editor to latest version and Angular Language Service Extension to 16.0.0 version (also the latest).

### Description

After the update, codes like that below started to present the following errors, but only on VS Code problems tab. When I run an "ng build" or "ng serve" all happens just fine. Then I disabled and downgraded all my extensions until I found that ALS Extension downgrade would solve my problem temporally.

I didn't find anything useful on the internet about a similar case, so I decided to open this issue.

#### Sample code

```
<p-dialog [visible]="msgSucesso" [modal]="true" [contentStyle]="{'max-width':'500px'}" [closable]="false">
    <p-header>
      <strong>Sucesso</strong>
    </p-header>
    <div class="content-alert">
      <p>{{msgSucesso}}</p>
    </div>
    <p-footer>
      <button pButton type="button" class="valida-key-ok" label="Fechar" (click)="esconderSucesso()"></button>
    </p-footer>
  </p-dialog>
```

#### Some errors related:

```
'p-dialog' is not a known element:
1. If 'p-dialog' is an Angular component, then verify that it is part of this module.
2. If 'p-dialog' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```

```
Can't bind to 'closable' since it isn't a known property of 'p-dialog'.
1. If 'p-dialog' is an Angular component and it has 'closable' input, then verify that it is part of this module.
2. If 'p-dialog' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
```

```
'p-header' is not a known element:
1. If 'p-header' is an Angular component, then verify that it is part of this module.
2. If 'p-header' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```

```
'p-footer' is not a known element:
1. If 'p-footer' is an Angular component, then verify that it is part of this module.
2. If 'p-footer' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```

**Comment by JanK-Qics** [comment] 2023-06-26 10:47
Same issue here, build/serve passes, but i get those errors.

![image](https://github.com/angular/vscode-ng-language-service/assets/129259868/ab31f6d7-607f-4628-b6d7-cf595e17c5ed)
![image](https://github.com/angular/vscode-ng-language-service/assets/129259868/d9371351-7bde-4d73-8327-e98109b2a1c8)

**Comment by wxpxzdj** [comment] 2023-06-27 23:53
same problem

**Comment by atscott** [comment] 2023-08-07 23:07
Thanks for reporting this issue. I wasn't able to reproduce it myself and it appears that this has been resolved by some uninstalling/reinstalling. As far as I can tell, this isn't widespread and is likely isolated to some individual workspace issues.

**Closed by atscott** 2023-08-07 23:07 UTC
Labels: bug

**Comment by arazinger** [comment] 2023-08-22 08:58
I have the same problem - using Angular 8 and latest ALS version.
Uninstalling and reinstalling didn't help.
Rollback to version 15.2.1 did solve the issue, but it's not a real solution.

Might be related to Ivy language service as I see this in ALS log output "_Enabling Ivy language service ..._" when using latest version and "_Enabling View Engine language service ..._" when using version 15.2.1?

**Comment by sebastiaorabelo** [comment] 2023-08-22 11:43
> I have the same problem - using Angular 8 and latest ALS version. Uninstalling and reinstalling didn't help. Rollback to version 15.2.1 did solve the issue, but it's not a real solution.
> 
> Might be related to Ivy language service as I see this in ALS log output "_Enabling Ivy language service ..._" when using latest version and "_Enabling View Engine language service ..._" when using version 15.2.1?

Hello, I keep trying new versions of all my extensions and VS Code, and yet ALS only works fine in version 15.2.1.
I stand for your affirmation too "Rollback to version 15.2.1 did solve the issue, but it's not a real solution."

**Comment by atscott** [comment] 2023-08-22 16:36
Version 16 dropped both ngcc and support for View Engine projects. If your project requires ngcc or is very old (version 8 has been unsupported for several years now), this is expected. I believe this is the root cause of the issues based on the comments above.
