### ISSUE TITLE
Extension issue: Try to invoke ngcc manually

### ISSUE THREAD

**Issue by ashwinlimbani** [angular/vscode-ng-language-service#1652] opened 2022-05-06 05:00 UTC
###**- Issue Type**: Bug
- Extension Name: Angular Language Service

###**Error Msg:**
 Angular extension might not work correctly because ngcc operation failed. Try to invoke ngcc manually by running 'npm/yarn run ngcc'. Please see the extension output for more information.

###**Expected behavior**

Extension should work properly with Ivy Compiler. Because Angular has removed ngcc from v13.
We need to take care of that

###**OUTPUT **

<pre><code>
c:\Users\ashwi\.vscode\extensions\angular.ng-template-13.3.2\node_modules\vscode-jsonrpc\lib\common\connection.js:477
                        responsePromise.reject(new messages_1.ResponseError(error.code, error.message, error.data));
                                               ^

ResponseError: Request window/workDoneProgress/create failed with message: Language client is not ready yet
    at handleResponse (c:\Users\ashwi\.vscode\extensions\angular.ng-template-13.3.2\node_modules\vscode-jsonrpc\lib\common\connection.js:477:48)
    at processMessageQueue (c:\Users\ashwi\.vscode\extensions\angular.ng-template-13.3.2\node_modules\vscode-jsonrpc\lib\common\connection.js:292:17)
    at Immediate.<anonymous> (c:\Users\ashwi\.vscode\extensions\angular.ng-template-13.3.2\node_modules\vscode-jsonrpc\lib\common\connection.js:276:13)
    at processImmediate (node:internal/timers:464:21) {
  code: -32603,
  data: undefined
}
[Info  - 9:52:40 AM] Angular language server process ID: 14844
[Info  - 9:52:40 AM] Using typescript/lib/tsserverlibrary v4.6.3 from d:\Practice\angular\Medikonnex-client-portal\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 9:52:40 AM] Using @angular/language-service v13.3.5 from c:\Users\ashwi\.vscode\extensions\angular.ng-template-13.3.2\node_modules\@angular\language-service\index.js
[Info  - 9:52:40 AM] Logging is turned off. To enable, run command 'Open Angular server log'.
[Error - 9:52:46 AM] Failed to run ngcc for d:/Practice/angular/Medikonnex-client-portal/tsconfig.json, language service may not operate correctly:
    ngcc for d:/Practice/angular/Medikonnex-client-portal/tsconfig.json returned exit code 1, stderr: [33mWarning:[0m Entry point '@angular/common' contains deep imports into 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/Subscription', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/Observable'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
[33mWarning:[0m Entry point '@angular/common/http' contains deep imports into 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/observable/of', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/operator/concatMap', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/operator/filter', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/operator/map', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/Observable'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
[33mWarning:[0m Entry point '@angular/common/http/testing' contains deep imports into 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/Observable', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/Observer'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
[33mWarning:[0m Entry point '@angular/common/testing' contains deep imports into 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/Subscription'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
[33mWarning:[0m Entry point '@angular/core' contains deep imports into 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/Observable', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/observable/merge', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/operator/share', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/Subject', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/Subscription'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
[33mWarning:[0m Entry point '@angular/forms' contains deep imports into 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/observable/forkJoin', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/observable/fromPromise', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/operator/map', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/Observable'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
[33mWarning:[0m Entry point '@angular/http' contains deep imports into 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/Observable'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
[33mWarning:[0m Entry point '@angular/http/testing' contains deep imports into 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/ReplaySubject', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/Subject', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/operator/take'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
[33mWarning:[0m Entry point '@angular/router' contains deep imports into 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/BehaviorSubject', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/Subject', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/observable/of', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/operator/concatMap', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/operator/map', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/operator/mergeMap', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/Observable', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/observable/from', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/operator/catch', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/operator/concatAll', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/operator/first', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/util/EmptyError', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/observable/fromPromise', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/operator/every', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/operator/last', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/operator/mergeAll', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/operator/reduce', 'd:/Practice/angular/Medikonnex-client-portal/node_modules/angular-moment-timezone/node_modules/rxjs/operator/filter'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
Error: Error on worker #1: TypeError: Cannot read properties of null (reading 'fileName')
    at getImportRewriter (file:///d:/Practice/angular/Medikonnex-client-portal/node_modules/@angular/compiler-cli/bundles/chunk-S2JDWKKT.js:3934:54)
    at DtsRenderer.renderDtsFile (file:///d:/Practice/angular/Medikonnex-client-portal/node_modules/@angular/compiler-cli/bundles/chunk-S2JDWKKT.js:4254:45)
    at file:///d:/Practice/angular/Medikonnex-client-portal/node_modules/@angular/compiler-cli/bundles/chunk-S2JDWKKT.js:4247:73
    at Map.forEach (<anonymous>)
    at DtsRenderer.renderProgram (file:///d:/Practice/angular/Medikonnex-client-portal/node_modules/@angular/compiler-cli/bundles/chunk-S2JDWKKT.js:4247:16)
    at Transformer.transform (file:///d:/Practice/angular/Medikonnex-client-portal/node_modules/@angular/compiler-cli/bundles/chunk-S2JDWKKT.js:4574:44)
    at file:///d:/Practice/angular/Medikonnex-client-portal/node_modules/@angular/compiler-cli/bundles/chunk-S2JDWKKT.js:4649:34
    at Worker.<anonymous> (file:///d:/Practice/angular/Medikonnex-client-portal/node_modules/@angular/compiler-cli/bundles/ngcc/src/execution/cluster/ngcc_cluster_worker.js:70:24)
    at Worker.emit (node:events:390:28)
    at process.<anonymous> (node:internal/cluster/worker:33:12)
    at ClusterMaster.onWorkerMessage (file:///d:/Practice/angular/Medikonnex-client-portal/node_modules/@angular/compiler-cli/bundles/chunk-UAIUNABS.js:1464:15)
    at file:///d:/Practice/angular/Medikonnex-client-portal/node_modules/@angular/compiler-cli/bundles/chunk-UAIUNABS.js:1374:71
    at EventEmitter.<anonymous> (file:///d:/Practice/angular/Medikonnex-client-portal/node_modules/@angular/compiler-cli/bundles/chunk-UAIUNABS.js:1532:15)
    at EventEmitter.emit (node:events:390:28)
    at Worker.<anonymous> (node:internal/cluster/primary:186:13)
    at Worker.emit (node:events:390:28)
    at ChildProcess.<anonymous> (node:internal/cluster/worker:33:12)
    at ChildProcess.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[Info  - 9:52:46 AM] Enabling Ivy language service for d:/Practice/angular/Medikonnex-client-portal/tsconfig.json.
</code></pre>

**Screenshots**
![image](https://user-images.githubusercontent.com/23011801/167069335-7db15c1c-2385-485e-be10-b8fad852271b.png)

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.3.3
Node: 16.14.2
Package Manager: npm 8.5.0
OS: win32 x64

Angular: 13.3.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------       
@angular-devkit/architect       0.1303.3
@angular-devkit/build-angular   13.3.3
@angular-devkit/core            13.3.3
@angular-devkit/schematics      13.3.3
@angular/cli                    13.3.3
@schematics/angular             13.3.3
rxjs                            7.5.5
typescript                      4.6.3

</code></pre>

Extension Version:
<pre><code>
Extension Version: v13.3.2

</code></pre>

VSCode Version:
<pre><code>
VSCode Version:
<pre><code>
Version: 1.67.0 (user setup)
Commit: 57fd6d0195bb9b9d1b49f6da5db789060795de47
Date: 2022-05-04T12:06:02.889Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

</code></pre>

Operating System:
<pre><code>
Edition	Windows 10 Home Single Language
Version	21H2
Installed on	‎4/‎16/‎2022
OS build	19044.1645
Experience	Windows Feature Experience Pack 120.2212.4170.0

</code></pre>

**Comment by atscott** [comment] 2022-05-06 15:54
`ngcc` was not removed in v13 and is still necessary to run because libraries may not be published with Ivy instructions.

There is an extension option that will be included in the v14 release to manually disable `ngcc` for the extension.

With that, the error is correct and valid. Ngcc failed to run and the language service _might_ not work correctly. Closing as working as intended

**Closed by atscott** 2022-05-06 15:54 UTC
Labels: bug

**Comment by ashwinlimbani** [comment] 2022-05-06 15:57
ok Thanks for reply
