### ISSUE TITLE
reference to function/variables being refferred in HTML

### ISSUE THREAD

**Issue by sanket-bhalerao** [angular/vscode-ng-language-service#612] opened 2020-02-04 08:02 UTC
Issue Type: <b>Feature Request</b>

similar to typescript showing reference to function/variable reference(i.e. this function is called 3 time) code lens, is it possible to show reference to a function/variable that is being refferred from HTML?

Extension version: 0.900.9
VS Code version: Code - Insiders 1.42.0-insider (705f01577dd37d6f17eaa683ab89b0c392fa1a7c, 2020-02-03T14:02:55.075Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.15.0-65-generic

**Comment by ayazhafiz** [comment] 2020-02-04 08:06
Duplicate of #29. This will be supported eventually, likely after the Ivy rewrite of the language service.

**Closed by ayazhafiz** 2020-02-04 08:06 UTC
