### ISSUE TITLE
The paths setting in tsconfig.json causes issues

### ISSUE THREAD

**Issue by maxisam** [angular/vscode-ng-language-service#183] opened 2017-10-13 16:42 UTC
I have TSLint (5.7.0), codelyzer (3.2.1) and angular lang service 0.1.7 installed on vscode 1.17.0 (windows)

In my angular cli (1.4.5) project

If I have the following setting in tsconfig

    "paths": {
      "@app/*": ["app/*"],
      "@env/*": ["environments/*"]
    },
and my import would be like
import { SharedModule } from '@app/shared/shared.module';

I will have lots of error like this in my template showing in vscode with red underlines.

[Angular] Property binding ngIf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations".

But if I import it with relative path

import { SharedModule } from '../../shared/shared.module';

The problem goes away.

at first, I thought it was vscode-tslint https://github.com/Microsoft/vscode-tslint/issues/276#event-1292520818

But it seems like it is from Angular Language Service

**Comment by thiagoaos** [comment] 2017-10-16 19:35
Here i have the same problem.

**Comment by aitboudad** [comment] 2017-10-16 22:11
for a workaround try to create a symbolic link in `node_modules` for example for the `@app` path:
```console
ln -s src/app node_modules/@app
```

**Comment by aitboudad** [comment] 2017-10-16 23:43
***Note***: using symlink may remove your project files when updating npm, so use it at your own risk!

**Comment by jahmani** [comment] 2017-10-18 07:10
i have the same problem
* vscode show error when using path alias
* vs code show error when using *ngIf... in template

**Comment by juraj0137** [comment] 2017-10-18 09:00
@maxisam Could you write here how you code structure looks like? Especially where app.module.ts and shared.module.ts are located. Do you use barels (index.ts)? 

I would like to mention that if you use `"paths"` in yout tsconfig, you have to specify `"baseUrl".` (according to [this stackoverflow answer](https://stackoverflow.com/questions/43281741/how-to-use-paths-in-tsconfig-json?answertab=active#tab-top))

**Comment by maxisam** [comment] 2017-10-18 14:57
root
  |--src
       |--app
             |--share

I don't use barrels. It is a normal CLI layout. The project is generated by cli.

It has paths setting.

**Comment by Dunos** [comment] 2017-11-13 14:55
Same issue here, the `baseUrl` parameter is already set with "src" and yet it does not work.

**Comment by FeroxB2B** [comment] 2017-11-16 13:29
This config solved the problem for me:

    "baseUrl": "./",
    "paths": {
      "@app/*": ["app/*"],
      "@env/*": ["environments/*"],
      "@services/*": ["app/modules/core/services/*"],
      "@models/*": ["app/models/*"],      
      "@components/*": ["app/components/*"],
      "@modules/*": ["app/modules/*"],
      "@core/*": ["app/modules/core/*"],
      "@shared/*": ["app/modules/shared/*"],
      "@features/*": ["app/modules/features/*"]
    }

**Comment by ghiscoding** [comment] 2017-11-22 21:45
I'm using Angular-CLI and also have this problem when using an external component library (which I'm the author). I tried to change the `tsconfig.app.json` with the mentioned config but that didn't change anything on my side. Is there any other workaround? And/or, do I have to do any kind of changes in my library?

**Comment by aitboudad** [comment] 2017-11-22 22:01
@thiagoaos see https://github.com/angular/angular/issues/16382#issuecomment-343603683

**Comment by ghiscoding** [comment] 2017-11-24 15:30
Thanks @aitboudad but that didn't work for me. I finally took the time to update my App to `Angular 5` and updated as you suggested in that other issue to `"@angular/language-service": "5.1.0-beta.1"` but still get this error. It comes from a library that I made called `Angular-Slickgrid` and in my Dev environment using relative paths `./` I don't see this problem, but using the lib in an external App as `import ... from 'angular-slickgrid'` and switch to my View completely it becomes completely red as shown below.

You can see the error being
```bash
[Angular] Cannot read property 'isSkipSelf' of null
```

![cannotskipitself](https://user-images.githubusercontent.com/643976/33216502-18446108-d102-11e7-9be2-1490da4b03ca.png)

**Comment by aitboudad** [comment] 2017-11-24 15:54
@ghiscoding after installing `@angular/language-service` you  should restart vscode

**Comment by ghiscoding** [comment] 2017-11-24 16:59
@aitboudad  Yes I had done that too but still got the error.

**Comment by Dunos** [comment] 2017-11-24 18:00
This is not working for me either, even after installing @angular/language-service

**Comment by davidwuerfel** [comment] 2017-12-11 22:11
I can also report the same problem. This is only occurring in VS Code with the language service extension. WebStorm has no problem with it by default and resolves everything.
See also: https://github.com/angular/angular/issues/16382 and https://github.com/nrwl/nx/issues/73.

**Comment by fxck** [comment] 2018-01-17 08:42
any updates on this?

**Comment by jwuliger** [comment] 2018-01-24 06:41
Hello, I thought I was the only one.

I am working on an Angular Mono Repo, and this started happening to me a little while ago.

![](https://s3.amazonaws.com/viven-images/vs-code-ts-error.PNG)

Hoping it gets fixed soon! Thanks, Guys!

**Comment by fxck** [comment] 2018-03-01 07:51
@chuckjaz any ideas?

**Comment by kyliau** [comment] 2018-03-07 18:21
https://github.com/angular/angular/issues/16382 fixed this and it was released as Angular.ng-template 0.1.9. @fxck Can you please check if you're running the latest version?

**Comment by ghiscoding** [comment] 2018-03-07 18:33
@kyliau 
I don't see the issue on my side anymore, so I can confirm that it does work for me now. Thanks

**Comment by kyliau** [comment] 2018-03-07 19:19
Closing this for now since issue is fixed.

**Closed by kyliau** 2018-03-07 19:19 UTC
Labels: bug
