### ISSUE TITLE
No config file for & No definition found for 😢

### ISSUE THREAD

**Issue by Bernoulli-IT** [angular/vscode-ng-language-service#1112] opened 2021-02-16 09:24 UTC
**Describe the bug**

The Angular Language Service stopped working correctly since most recent update (3 days ago). It show these kind of messages:

**To Reproduce**

1. Install latest version 11.2.0
2. Go to any HTML template inside the src folder
3. Hover over a code reference to the underlying typescript file
4. Check error in tooltip and see log results which report "No config file"

**Expected behavior**

The usual super handy Angular Language Service functionality of gettin a tooltip with information, syntax checks & go to definition.

**Logs**

[Info  - 10:15:16] Angular language server process ID: 25044
[Info  - 10:15:16] Using typescript/lib/tsserverlibrary v4.1.5 from c:\Users\Bernoulli IT\.vscode\extensions\angular.ng-template-11.2.0\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 10:15:16] Using @angular/language-service/bundles/ivy v11.2.0 from c:\Users\Bernoulli IT\.vscode\extensions\angular.ng-template-11.2.0\node_modules\@angular\language-service\bundles\ivy.js
[Info  - 10:15:16] Log file: c:\Users\Bernoulli IT\AppData\Roaming\Code\logs\20210216T101512\exthost1\Angular.ng-template\nglangsvc.log
[Error - 10:15:25] No config file for c:/Users/Bernoulli IT/Documents/Applications/Argaleo/Argaleo.Digitwin.Browser.App/src/app/modules/root/app.component.html
[Info  - 10:15:26] Enabling Ivy language service for c:/Users/Bernoulli IT/Documents/Applications/Argaleo/Argaleo.Digitwin.Browser.App/tsconfig.json.
[Error - 10:15:27] No config file for c:/Users/Bernoulli IT/Documents/Applications/Argaleo/Argaleo.Digitwin.Browser.App/src/app/modules/root/app.component.html

**Screenshots**

![2021-02-16 10_15_40-app component html - App - Visual Studio Code](https://user-images.githubusercontent.com/9802752/108042609-528b2280-7040-11eb-988a-0a36900d2c5a.png)

**Workaround**

Downgrade to 11.1.3  (and restart VS Code) and be a happy camper again 🤓💻

**Comment by roycastro** [comment] 2021-02-16 10:37
I also saw the same behavior from the Angular Language Service and the downgrading to 11.1.3 seems to solve the issue.

- VSCode 1.54.0-insider
- Angular 11.1.5
- Typescript 4.0.3

**Comment by ikilinc** [comment] 2021-02-16 10:43
I have the same issue, downgrading to version 11.1.3 helps.

**Comment by magnusbakken** [comment] 2021-02-16 12:55
I have it as well, but downgrading the extension to 11.1.3 does not fix the issue for me, without also downgrading the language service dependency to 11.1. I also already saw problems before upgrading the extension to 11.2.0, so I think there are multiple issues.

**Comment by DirkStorck** [comment] 2021-02-16 14:00
I have created a new project and added 
    "@angular/language-server": "^11.1.3",
    "@angular/language-service": "^11.1.1",
in my package.json

But I still get 
Error - 14:27:20] No config file for d:/REWE/Angular/test/src/app/app.component.html

**Comment by roycastro** [comment] 2021-02-16 16:29
> I have created a new project and added
> "@angular/language-server": "^11.1.3",
> "@angular/language-service": "^11.1.1",
> in my package.json
> 
> But I still get
> Error - 14:27:20] No config file for d:/REWE/Angular/test/src/app/app.component.html

Did you also change the VSCode extension to version 11.1.3?

**Comment by DirkStorck** [comment] 2021-02-16 16:54
Additionally I installed this version:
https://github.com/angular/vscode-ng-language-service/tree/11.1.x
using " in Visual Studio code, go to the extensions tab. Click on the "..." menu...."

this didn't work for me
"code --install-extension /path/to/ngls.vsix"

Now it works for me again :)

**Comment by atscott** [comment] 2021-02-16 20:22
Duplicate of #1109

**Closed by atscott** 2021-02-16 20:22 UTC
Labels: bug
