### ISSUE TITLE
template attribute directive autocomplete overwrites following characters

### ISSUE THREAD

**Issue by diminutivesloop** [angular/vscode-ng-language-service#262] opened 2018-06-21 19:50 UTC
Issue Type: <b>Bug</b>

When accepting an autocomplete suggestion for an attribute directive (such as *ngIf) the inserted directive overwrites several of the characters following the insertion point. For example with the following template code:
```
<div class="mainContent">
```
after inserting an *ngIf directive via autocomplete immediately before the `class` attribute I get the following result:
```
<div *ngIf=lass="mainContent">
```

This doesn't appear to be a VSCode issue as I can not reproduce the issue with non angular-specific autocomplete suggestions.

Extension version: 0.1.9
VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 6.1.7601

**Comment by kyliau** [comment] 2019-11-09 00:13
@ayazhafiz could you please confirm if this is still the case?

**Comment by ayazhafiz** [comment] 2019-11-09 02:55
I can't reproduce this. I don't think `=`s are completed anymore.

**Comment by ayazhafiz** [comment] 2019-11-09 02:55
Closing, please open a new issue if you are experiencing this.

**Closed by ayazhafiz** 2019-11-09 02:55 UTC
Labels: bug
