### ISSUE TITLE
Feature Request - Add Support for "Find All References" right mouse click

### ISSUE THREAD

**Issue by shawndotey** [angular/vscode-ng-language-service#259] opened 2018-06-08 15:32 UTC
Can we look into adding support for "Find All References" right mouse click when in the HTML context and and also finding the HTML references when in the TS context?

**Comment by kyliau** [comment] 2019-11-09 00:09
This is a duplicate of https://github.com/angular/vscode-ng-language-service/issues/29

**Closed by kyliau** 2019-11-09 00:09 UTC
