### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by vinaynasha** [angular/vscode-ng-language-service#1285] opened 2021-04-15 03:29 UTC
- Issue Type: `Bug`
- Extension Name: `ng-template`
- Extension Version: `11.2.10`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.55.1`

:warning: Angular Language Service Unresponsive Performance Issue :warning:

**Comment by vinaynasha** [comment] 2021-04-15 03:31
Also from the same angular service i am also getting this info every time i open vs code

Some language features are not available. To access all features, enable [strictTemplates] in [angularCompilerOptions].

**Comment by atscott** [comment] 2021-04-15 15:24
Closing as duplicate of #636. There's not enough information here for me to tell if this is a separate issue.

As for the strict templates prompt, we recommend updating your `angularCompilerOptions` to set `strictTemplates` to `true`. You can disable this prompt by clicking the "do not show again for this workspace" button.

**Closed by atscott** 2021-04-15 15:24 UTC
