### ISSUE TITLE
Prevents renaming folders (Windows)

### ISSUE THREAD

**Issue by tflanitzer** [angular/vscode-ng-language-service#240] opened 2018-03-29 08:09 UTC
I have noticed that I cannot rename folders within my project as long as the language service is active. This is the error I get when I try:

![2018-03-29 10_02_47-inbox - thomas flanitzer zuehlke com - outlook](https://user-images.githubusercontent.com/10977536/38077273-be1afd2e-3338-11e8-997a-33a931a47a5a.png)

As soon as I deactivate the extension and reload, it works as expected.

Using Process explorer I found out that indeed Code.exe has open handles on each folder in my project:

![2018_03_29_10_07_57_data_import_editor component ts_frontend_visual_studio_code_administrator_](https://user-images.githubusercontent.com/10977536/38077417-2f1df1a2-3339-11e8-8755-019691d8f124.png)

Here is the Angular Language Service log output:

```
Search path: c:/dev/XXX/Sources/Frontend/src/app/data-import/data-import-editor
Config file name: c:/dev/XXX/Sources/Frontend/tsconfig.json
Angular Language Service: 5.1.0
TypeScript: 2.6.2
getTemplateRefrences: 2942ms
Add recursive watcher for: c:/dev/XXX/Sources/Frontend
Opened configuration file c:/dev/XXX/Sources/Frontend/tsconfig.json
getDiagnostics: 20ms
```

**Comment by Darkein** [comment] 2019-02-18 09:32
Hello,
the problem is still here. I have to deactivate this extension to rename my files and folders on Windows 10.

**Comment by jonaskuske** [comment] 2019-04-08 12:35
Same issue. :(

**Comment by techy2493** [comment] 2019-06-18 18:11
This is a much larger issue than just renaming, the service is leaving open file handles all over the place. I'm having trouble deleting things, re-building projects with libraries that npm link & unlink, git rebases... It's gotten worse recently, which may be partly due to windows updates but the extension itself is keeping these handles open.

**Comment by techy2493** [comment] 2019-06-18 18:14
![image](https://user-images.githubusercontent.com/2701534/59708674-dd13e280-91ca-11e9-9885-8bb964029bf7.png)
This is an example of attempting to rebase with the extension on, (after failing and re-starting VsCode) and below is an example after the extension is disabled in the worksapce.
![image](https://user-images.githubusercontent.com/2701534/59708765-0b91bd80-91cb-11e9-9293-222d99166aaa.png)

**Comment by techy2493** [comment] 2019-06-18 18:16
Here is an example where the Angular Language Service blocks an NPM Unlink of a package library due to these same open file handles.
![image](https://user-images.githubusercontent.com/2701534/59708854-3bd95c00-91cb-11e9-899c-e55ed29b0592.png)

**Comment by techy2493** [comment] 2019-06-18 18:18
These things separately impact workflow and performance, but when working quickly in large projects these things together make working with the angular language service enabled nearly impossible.

**Comment by Darkein** [comment] 2019-06-19 04:22
This issue is opened since more than one year, and this annoying problem is still here (I just can't use this great extension).
What do you need to take a look on it ?

**Comment by JohnnyDevNull** [comment] 2019-06-20 01:20
Well i have also the problems since a long time and the plugin in the actual state is in bigger projects especially with local angular libraries not usable. I have disabled it and work without it.

I think the problem is the duplicate TS-Server which is running and maybe it's fixed with that one here: https://github.com/angular/vscode-ng-language-service/issues/338

**Comment by kyliau** [comment] 2019-11-23 00:46
This is the same as https://github.com/angular/vscode-ng-language-service/issues/224, will track the issue there.

**Closed by kyliau** 2019-11-23 00:46 UTC
