### ISSUE TITLE
Suggestions not displaying for object keys containing "_"

### ISSUE THREAD

**Issue by iFarmGolems** [angular/vscode-ng-language-service#175] opened 2017-10-02 10:49 UTC
Hello, 

So I have an interface like this:

```
export interface FindWhatYouNeedResponse {
  nid: Nid[];
  uuid: Uuid[];
  vid: Nid[];
  langcode: Uuid[];
  type: Type[];
  status: Status[];
  title: Uuid[];
  uid: Uid[];
  created: Nid[];
  changed: Nid[];
  promote: Status[];
  sticky: Status[];
  revision_timestamp: Nid[];
  revision_uid: Uid[];
  revision_log: any[];
  revision_translation_affected: Status[];
  default_langcode: Status[];
  path: any[];
  field_index_fwyn_1_btn_link: Uuid[];
  field_index_fwyn_1_btn_text: Uuid[];
  field_index_fwyn_1_subject: Fieldindexfwyn1subject[];
  field_index_fwyn_2_btn_link: Uuid[];
  field_index_fwyn_2_btn_text: Uuid[];
  field_index_fwyn_2_subject: Fieldindexfwyn1subject[];
  field_index_fwyn_3_btn_text: Uuid[];
  field_index_fwyn_3_subject: Fieldindexfwyn1subject[];
  field_index_fwyn_heading: Uuid[];
  _xyz: Uuid[];
}
```

Then I got some local variable:

`blockData: FindWhatYouNeedResponse;`

But when I trigger autocomplete, I get this:

![2017-10-02 12_45_18- find-what-you-need component html frontend visual studio code](https://user-images.githubusercontent.com/12659034/31074206-cd889c1c-a76f-11e7-82e0-c06c556cfec1.png)

There are just 2 more keys that are not visible. Notice how all the keys containing "_" are missing from the autocomplete.

**Comment by kyliau** [comment] 2019-11-08 23:44
Duplicate of https://github.com/angular/vscode-ng-language-service/issues/258

**Closed by kyliau** 2019-11-08 23:44 UTC
Labels: bug
