### ISSUE TITLE
Templates completely ignored by VS Code extension in Angular 16

### ISSUE THREAD

**Issue by CZ-DannyK** [angular/vscode-ng-language-service#1901] opened 2023-07-12 10:27 UTC
# 🐞 bug report

### Is this a regression?

 Tested on Angular 16 and 12.4. with latest version of VS Code extension. In Angular 12 it was working fine.

### Description

Recently i have started noticing after we migrated to Angular 16 from 12.4. that extension completely ignores angular html templates. To be more specific, i have noticed 2 things not working as expected:

1. Intellisense does not pop up in angular html templates at all (for example in any [], (), [()] attribute)
2. Finding of references for object property does not list references in templates, only in ts files.

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction (missing intellisense in templates)

Steps to reproduce the behavior of missing intellisense in templates:
1. Go to any angular template (like app.component.html)
2. Add *ngIf for example (but basically any attribute or eval in {{ }} is affected)
3. Start typing name of variable or function that is in app.component.ts and is public
4. No intellisense pop up

**Expected behavior**

Intellisense should pop up and suggest all available variables and properties in component at least

### **Logs**

There are no logs i am aware of

## Reproduction (Templates ignored in finding of references)

Steps to reproduce the behavior of missing intellisense in templates:
1. Go to any angular ts file (like app.component.ts)
2. Add any public variable and use it in template (either as input, or eval)
3. In ts file right click on given variable and select Find all references
4. Reference in template is missing from results

**Expected behavior**

Template references should be included in found results

### **Logs**

There are no logs i am aware of

## 🌍  Your Environment
**Angular Version:**
<pre><code>Angular CLI: 16.0.5
Node: 18.16.0
Package Manager: npm 9.5.1
OS: win32 x64

Angular: 16.0.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1600.5
@angular-devkit/build-angular      16.0.5
@angular-devkit/core               16.0.5
@angular-devkit/schematics         16.0.5
@angular/cdk                       16.0.3
@angular/cli                       16.0.5
@angular/material                  16.0.3
@angular/material-moment-adapter   16.0.3
@schematics/angular                16.0.5
rxjs                               7.8.1
typescript                         4.9.5
</code></pre>

Extension Version:
<pre><code>v16.0.0
</code></pre>

VSCode Version:
<pre><code>Version: 1.80.0 (user setup)
Commit: 660393deaaa6d1996740ff4880f1bad43768c814
Date: 2023-07-04T15:06:02.407Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
</code></pre>

Operating System:
<pre><code>Edition	Windows 11 Pro
Version	22H2
Installed on	‎14.‎05.‎2023
OS build	22621.1848
Experience	Windows Feature Experience Pack 1000.22642.1000.0
</code></pre>

Extension options:
<pre><code>Only default setting
</code></pre>

**Anything else relevant?**

Not sure about any, ask if you need something and i will try to answer as best as i can.

**Comment by CZ-DannyK** [comment] 2023-08-29 15:49
@atscott i dont right now. It happens in company product project. But i will try to make some example repo from that project and basically keep mainly configs and basic component (lets see if it will work in this way or not).

**Comment by atscott** [comment] 2023-08-29 17:55
@CZ-DannyK Can you verify that there are no diagnostics in the problems pane of VSCode?

**Comment by CZ-DannyK** [comment] 2023-08-29 17:56
@atscott tomorrow i will check to be sure

**Comment by atscott** [comment] 2023-09-13 14:17
Closing as likely duplicate of https://github.com/angular/vscode-ng-language-service/issues/1923 which has a reproduction.

**Closed by atscott** 2023-09-13 14:17 UTC
Labels: bug, needs repro
