### ISSUE TITLE
Go To Definition not working in template on component tags with the directive *ngfor 

### ISSUE THREAD

**Issue by suisoku** [angular/vscode-ng-language-service#1184] opened 2021-03-09 12:41 UTC
**Describe the bug**

Go To Definition not working in template on component tags with the directive *ngfor in VSCode using the lastest ALS

**To Reproduce**

F12 on <component-name *ngFor=".."> in VSCode with the latest ALS version
I have "No definition found for component-name"

**Expected behavior**

It should get me to the ts file

**Logs**

ALS log doesn't show anything in particular (set to verbose)

**Additional context**

I rolled back to an earlier version done 6 months ago (v0.1000.8) it seemed to work normally 
I have Angular v11 and switched to ESLINT recently

**Comment by atscott** [comment] 2021-03-15 20:06
@suisoku - Could you provide some more information about you project setup? Uploading the Angular Language Server logs would be a good start.

**Comment by atscott** [comment] 2021-03-17 15:58
Closing since there's not enough information to reproduce or debug the issue. 

If the problem still exists in your application, please open a new issue and provide enough information for us to reproduce it.

**Closed by atscott** 2021-03-17 15:58 UTC
Labels: bug, needs clarification
