### ISSUE TITLE
Unexpected token } in JSON at position 823

### ISSUE THREAD

**Issue by markgoho-EDT** [angular/vscode-ng-language-service#202] opened 2017-12-21 03:07 UTC
``` bash
Search path: c:/Users/Nella/Documents/EDT/app-copa/src/app
Config file name: c:/Users/Nella/Documents/EDT/app-copa/tsconfig.json
SERVER ERROR: Unexpected token } in JSON at position 823
SyntaxError: Unexpected token } in JSON at position 823
    at JSON.parse (<anonymous>)
    at parseAndReEmitConfigJSONFile (C:\Users\Nella\.vscode-insiders\extensions\Angular.ng-template-0.1.7\server\editorServices.js:257:33)
    at ProjectService.configFileToProjectOptions (C:\Users\Nella\.vscode-insiders\extensions\Angular.ng-template-0.1.7\server\editorServices.js:1598:18)
    at ProjectService.openConfigFile (C:\Users\Nella\.vscode-insiders\extensions\Angular.ng-template-0.1.7\server\editorServices.js:1620:42)
    at ProjectService.openOrUpdateConfiguredProjectForFile (C:\Users\Nella\.vscode-insiders\extensions\Angular.ng-template-0.1.7\server\editorServices.js:1486:41)
    at ProjectService.openClientFile (C:\Users\Nella\.vscode-insiders\extensions\Angular.ng-template-0.1.7\server\editorServices.js:1404:23)
    at C:\Users\Nella\.vscode-insiders\extensions\Angular.ng-template-0.1.7\server\documents.js:135:47
    at TextDocuments.logErrors (C:\Users\Nella\.vscode-insiders\extensions\Angular.ng-template-0.1.7\server\documents.js:235:13)
    at C:\Users\Nella\.vscode-insiders\extensions\Angular.ng-template-0.1.7\server\documents.js:131:74
    at handleNotification (C:\Users\Nella\.vscode-insiders\extensions\Angular.ng-template-0.1.7\server\node_modules\vscode-jsonrpc\lib\main.js:353:21)
[Error - 10:05:39 PM] Notification handler 'textDocument/didOpen' failed with message: Unexpected token } in JSON at position 823
```

**Comment by smasala** [comment] 2018-01-10 22:18
+1

`[Error - 23:16:59] Notification handler 'textDocument/didOpen' failed with message: Unexpected token } in JSON at position 515`

**Comment by smasala** [comment] 2018-01-10 22:20
Could this be a trailing comma issue? Can't seem to replicate anymore.

**Comment by tkoenig89** [comment] 2018-01-18 10:35
Having the same issue with a different error position:

`[Error - 11:28:36] Notification handler 'textDocument/didOpen' failed with message: Unexpected token } in JSON at position 534`

**Comment by tkoenig89** [comment] 2018-01-19 07:36
I guess, i managed to find root cause. It's not a bug in the plugin or the language service! It's an issue with the tsconfig.json beeing not formated correctly.

My tsconfig.json looked like this:
```JavaScript
"angularCompilerOptions": { 
      "fullTemplateTypeCheck": true , <-------- This comma did cause the issue
}
```
After removing the comma, the plugin worked well. 

I guess you can close this issue, as it's not a bug of the plugin.

**Comment by tkoenig89** [comment] 2018-01-19 14:12
@markgoho-EDT i guess you are right, i might have been a little too quick about this. Might be because i was bothered by the issue, and too happy when i finally managed to find a solution :)

**Comment by markgoho-EDT** [comment] 2018-01-19 15:32
Update: we also had an extraneous comma at the end of a line in our `tsconfig.json`

it was here:
``` json
"pretty": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "noUnusedParameters": false,
  },
```
after `noUnusedParamters`.

@chuckjaz hopefully this helps. I won't close this bug because this should probably solved by a different method of error handling rather than a user removing a comma.

**Closed** 2018-07-31 18:49 UTC
Labels: bug
