### ISSUE TITLE
Type completion not working when component has no selecot

### ISSUE THREAD

**Issue by johannesnormannjensen** [angular/vscode-ng-language-service#753] opened 2020-04-29 07:57 UTC
**Describe the bug**

Type completion in the template of a component with no selector is not working. 

**To Reproduce**

1. Create a component (ng g c...)
2. Remove the selector from the component
3. Add a property to the component class (ex. name: string)
4. Try to bind the property value to the template using type completion (Ctrl + Space)

**Expected behavior**

Should show me a dropdown of component properties

**Comment by ayazhafiz** [comment] 2020-04-29 22:36
What version of the language service are you on? Can you show the output of the extension (View > Output > Angular Language Service)? I can't reproduce this:

![i713-1588199670437](https://user-images.githubusercontent.com/20735482/80653520-3d9cbe80-8a2f-11ea-9d76-db4debe14cb0.gif)

**Comment by gustavodamazio** [comment] 2020-07-22 14:55
With me the autocomplete is not working in version 0.1000.4, I had to downgrade it to work again.
This is true for both normal vscode and vscode insiders.

Video showing the behavior.
https://vimeo.com/440686304

**Comment by atscott** [comment] 2021-01-27 19:07
Closing as unable to reproduce. Please update to the latest version of the extension and submit a new issue if this still happens.

**Closed by atscott** 2021-01-27 19:07 UTC
Labels: bug
