### ISSUE TITLE
"find all references" has redundant results

### ISSUE THREAD

**Issue by lsbbd** [angular/vscode-ng-language-service#1152] opened 2021-02-24 18:28 UTC
Issue Type: <b>Bug</b>

1. for any variable, right click `find all references`
2. view the `REFERENCE` view
3. the reference in the same position in the search results appears twice

Extension version: 11.2.3
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|32.00GB (18.96GB free)|
|Process Argv|./|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by prabh-62** [comment] 2021-02-24 19:09
VSCode shows double results for `*.ts` files
<img width="751" alt="double_references" src="https://user-images.githubusercontent.com/13006107/109052307-75a17c00-76a9-11eb-9213-a77834df2ca5.png">

`Ivy` enabled
<img width="1092" alt="ivy_enabled_vscode" src="https://user-images.githubusercontent.com/13006107/109052598-cadd8d80-76a9-11eb-8a40-b164d2c531a1.png">

**Comment by atscott** [comment] 2021-02-24 22:10
Duplicate of #1124. TL;DR this is an issue in vscode, the fix is here https://github.com/microsoft/vscode/pull/117424

**Closed by atscott** 2021-02-24 22:10 UTC
