### ISSUE TITLE
Super High CPU usage in VS Code for this extension

### ISSUE THREAD

**Issue by rohan-paul** [angular/vscode-ng-language-service#763] opened 2020-05-05 12:58 UTC
**Describe the bug**

As soon as I install it in VSCode the CPU usage (in Ubuntu 18.04) goes above 95%. And after uinstalling goes back to normal.

Have tried it multiple times and the same issue persists. 

**Screenshots**

![image](https://user-images.githubusercontent.com/12703975/81068080-66c0c180-8efd-11ea-8ffa-ca4961314317.png)

**Additional context**
VS Code version

```
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:50:03.709Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.2.11-050211-generic
```

**Comment by ayazhafiz** [comment] 2020-05-05 14:15
Closing as a dupe of #712

**Closed by ayazhafiz** 2020-05-05 14:15 UTC
Labels: bug
