### ISSUE TITLE
throws error

### ISSUE THREAD

**Issue by gkamlesh21** [angular/vscode-ng-language-service#1744] opened 2022-08-24 12:28 UTC
with latest upgrate to vs code 1.70.2 it seems unstable with the angular language service extension. it throws error for all the angular related code

**Comment by atscott** [comment] 2022-09-19 14:39
Given that this was reported before the 14.2 release of the extension and I can't reproduce it, I'm closing this as fixed.

**Closed by atscott** 2022-09-19 14:39 UTC
