### ISSUE TITLE
Notification handler 'textDocument/didOpen' failed with message: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by alusev** [angular/vscode-ng-language-service#201] opened 2017-12-19 17:07 UTC
VS Code Version 1.19.0 (1.19.0)

```
[Error - 10:54:51] Notification handler 'textDocument/didOpen' failed with message: Cannot read property 'length' of null
Search path: /Users/latenal/alus/docker-nginx-webstack/www/commissions2.0/frontend/src/app/users/admin/summary
Failed to read JSON file /Users/latenal/alus/docker-nginx-webstack/www/commissions2.0/frontend/node_modules/@angular/common/locales/es-MX.metadata.json
Config file name: /Users/latenal/alus/docker-nginx-webstack/www/commissions2.0/frontend/tsconfig.json
Angular Language Service: 5.0.0-beta.5
TypeScript: 2.4.2
Error for getTemplateRefrences:
    TypeError: Cannot read property 'version' of null
    at /Users/latenal/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:21442:70
    at Array.find (native)
    at ReflectorHost.BaseAotCompilerHost.readMetadata (/Users/latenal/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:21442:42)
    at ReflectorHost.BaseAotCompilerHost.getMetadataFor (/Users/latenal/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:21419:29)
    at StaticSymbolResolver.getModuleMetadata (/Users/latenal/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:17910:45)
    at StaticSymbolResolver._createSymbolsOf (/Users/latenal/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:17740:29)
    at StaticSymbolResolver.getSymbolsOf (/Users/latenal/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:17725:14)
    at /Users/latenal/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:16800:30
    at Array.forEach (native)
    at extractProgramSymbols (/Users/latenal/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:16799:79)
getTemplateRefrences: 1807ms
SERVER ERROR: Cannot read property 'length' of null
TypeError: Cannot read property 'length' of null
    at Project.updateFileMap (/Users/latenal/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:797:94)
    at Project.updateGraph (/Users/latenal/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:815:14)
    at Project.finishGraph (/Users/latenal/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:807:14)
    at ProjectService.openConfigFile (/Users/latenal/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1634:17)
    at ProjectService.openOrUpdateConfiguredProjectForFile (/Users/latenal/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1486:41)
    at ProjectService.openClientFile (/Users/latenal/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1404:23)
    at /Users/latenal/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:135:47
    at TextDocuments.logErrors (/Users/latenal/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:235:13)
    at /Users/latenal/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:131:74
    at handleNotification (/Users/latenal/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/vscode-jsonrpc/lib/main.js:353:21)
[Error - 11:04:09] Notification handler 'textDocument/didOpen' failed with message: Cannot read property 'length' of null
```

**Comment by chuckjaz** [comment] 2017-12-21 23:02
This happens because the language service tried to read a metadata file with the content `[null]`. 

These files can safely be deleted as they should not have been emitted in the first place and that is currently fixed master of angular.

I am leaving this issue open as the language service should not crash on invalid metadata.

**Comment by damasofc** [comment] 2017-12-26 03:02
I hava the same problem!! someone knows how to fixed it

**Comment by Romanchuk** [comment] 2017-12-29 06:51
Same problem:
It failes on angular locales metadata files for locales that registered with "registerLocaleData" (@angular/common)

**Comment by chuckjaz** [comment] 2017-12-30 18:29
This is a duplicate of #192

**Closed by chuckjaz** 2017-12-30 18:29 UTC
