### ISSUE TITLE
Error for getTemplateReferences (cannot read property 'name' of null)

### ISSUE THREAD

**Issue by mateuszwitkowski** [angular/vscode-ng-language-service#186] opened 2017-10-25 06:38 UTC
Hi! I have similiar issue to #182 (another TypeError though). Unfortunatelly, for now Angular Language Service doesn't work for me at all. Here's the error message I'm getting. 

Angular Language Service: 5.0.0-beta.5
TypeScript: 2.4.2
Error for getTemplateRefrences:
    TypeError: Cannot read property 'name' of null
    at CompileMetadataResolver._getEntryComponentMetadata (C:\Users\Acer01\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:9258:38)
    at C:\Users\Acer01\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:8915:53
    at Array.map (native)
    at CompileMetadataResolver.getNgModuleMetadata (C:\Users\Acer01\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:8915:18)
    at addNgModule (C:\Users\Acer01\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:16824:41)
    at C:\Users\Acer01\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:16835:14
    at Array.forEach (native)
    at _createNgModules (C:\Users\Acer01\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:16834:26)
    at analyzeNgModules (C:\Users\Acer01\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:16731:14)
    at TypeScriptServiceHost.ensureAnalyzedModules (C:\Users\Acer01\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:39118:17)
getTemplateRefrences: 6365ms
SERVER ERROR: Cannot read property 'length' of null
TypeError: Cannot read property 'length' of null
    at Project.updateFileMap (C:\Users\Acer01\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:797:94)
    at Project.updateGraph (C:\Users\Acer01\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:815:14)
    at Project.finishGraph (C:\Users\Acer01\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:807:14)
    at ProjectService.openConfigFile (C:\Users\Acer01\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:1634:17)
    at ProjectService.openOrUpdateConfiguredProjectForFile (C:\Users\Acer01\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:1486:41)
    at ProjectService.openClientFile (C:\Users\Acer01\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:1404:23)
    at C:\Users\Acer01\.vscode\extensions\Angular.ng-template-0.1.7\server\documents.js:135:47
    at TextDocuments.logErrors (C:\Users\Acer01\.vscode\extensions\Angular.ng-template-0.1.7\server\documents.js:235:13)
    at C:\Users\Acer01\.vscode\extensions\Angular.ng-template-0.1.7\server\documents.js:131:74
    at handleNotification (C:\Users\Acer01\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\vscode-jsonrpc\lib\main.js:353:21)
[Error - 08:27:03] Notification handler 'textDocument/didOpen' failed with message: Cannot read property 'length' of null

tsconfig.js

```{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "paths": {
      "@app/common": ["app/common"],
      ...
    },
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  }
}

**Comment by slavede** [comment] 2017-11-09 09:02
Same here.... :(

**Comment by GuillaumeNury** [comment] 2017-11-16 10:29
Same here, the following error appeared during Angular 5 update:

```
Search path: (...)/src/app/billing/core/cc-process/services
Failed to read JSON file (...)/node_modules/@angular/common/locales/fr.metadata.json
Config file name: (...)/tsconfig.json
Angular Language Service: 5.0.0-beta.5
TypeScript: 2.4.2
Error for getTemplateRefrences:
    TypeError: Cannot read property 'version' of null
    at C:\Users\Gnury\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:21442:70
```

**Comment by sandangel** [comment] 2017-11-17 03:39
Any fix? I have the same problem with language service 5.0.2 too

**Comment by OysteinAmundsen** [comment] 2017-11-28 19:05
Same here...

**Comment by OysteinAmundsen** [comment] 2017-11-30 09:23
Just for kicks, I edited the ~\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:21438 and placed a 
```
console.log(filePath);
```
in there. That actually gave me a `Failed to read JSON file` pointing to my projects `node_modules/@angular/common/locales/nb.metadata.json`. Rightly so, this file does not exist. It seems it tries to read out my current locale to fetch some translations or whatnot, and fails miserably.

**Comment by vdolek** [comment] 2017-12-06 09:54
Any fix? Same here...

**Comment by sandangel** [comment] 2017-12-06 10:57
update to 5.1.0-rc1 fix it

**Comment by deniskrafczyk** [comment] 2017-12-06 16:04
not for me, i updated my project to 5.1.0-rc.1 and the same error still appears

**Comment by smasala** [comment] 2017-12-08 14:55
Temp workaround:

Replace the contents of the server folder in your vscode Angular.ng-template-0.1.7 extension with the files out of the repo:

https://github.com/smasala/angular-language-service-0.17.patch

You'll usually find your extension folder in Windows under:
C:\Users[username].vscode\extensions\Angular.ng-template-0.1.7

**Comment by smasala** [comment] 2017-12-08 14:55
Temp workaround: https://github.com/angular/vscode-ng-language-service/issues/192#issuecomment-350281121

**Comment by chuckjaz** [comment] 2017-12-30 18:09
This is a duplicate of #192

**Closed by chuckjaz** 2017-12-30 18:09 UTC
