### ISSUE TITLE
Long lines cause wrong highlighting in a template

### ISSUE THREAD

**Issue by mfgabriel92** [angular/vscode-ng-language-service#640] opened 2020-02-16 11:20 UTC
**Describe the bug**

The highlighting becomes messed up with a line, say for a `ngFor` becomes too long with a `;let i = index` is added

**Screenshots**

![Screenshot from 2020-02-16 08-19-32](https://user-images.githubusercontent.com/26734503/74603695-1ae84400-5095-11ea-99fa-d42fd66d3f4c.png)

**Comment by ayazhafiz** [comment] 2020-02-16 15:58
Duplicate of #575

**Closed by ayazhafiz** 2020-02-16 15:58 UTC
Labels: bug
