### ISSUE TITLE
file content suddenly changed after hovering with command key holding

### ISSUE THREAD

**Issue by littlee** [angular/vscode-ng-language-service#1431] opened 2021-07-01 03:02 UTC
# 🐞 bug report

### Is this a regression?

yes

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [x] Angular Language Service server

## Reproduction

put the code below in an angular project, hovering with [command key] (WITHOUT clicking) `nativeElement` will trigger the bug... it will change the file content to another generated file... this is annoying
```ts
import { ViewChild } from '@angular/core';
import { ElementRef } from '@angular/core';
import { Component, OnInit } from '@angular/core';
@Component({
  selector: 'question-stem',
  templateUrl: './question-stem.component.html',
})
export class QuestionStemComponent implements OnInit {
  constructor() {}
  ngOnInit(): void {
    this.$stem.nativeElement;
  }
  @ViewChild('questionStem') $stem: ElementRef<HTMLElement>;
}
```

**Expected behavior**

hovering with command holding should not change file content

### **Logs**

```
-----------------------------------------------
Open files: 
Info 172  [10:56:33.933] Starting updateGraphWorker: Project: /Users/lixiaokai/code/flame-design-biz/tsconfig.json
Info 173  [10:56:34.129] Finishing updateGraphWorker: Project: /Users/lixiaokai/code/flame-design-biz/tsconfig.json Version: 5 structureChanged: true Elapsed: 196.09436297416687ms
Info 174  [10:56:34.130] Different program with same set of files:: structureIsReused:: 1
Info 175  [10:57:40.127] FileWatcher:: Close:: WatchInfo: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/question-stem/a.ts 500 {"watchFile":3,"watchDirectory":0,"fallbackPolling":2} Project:  WatchType: Closed Script info
Info 176  [10:57:40.127] Search path: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/question-stem
Info 177  [10:57:40.127] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/question-stem/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/question-stem/a.ts Status: File added to open files impacted by this config file
Info 178  [10:57:40.127] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/question-stem/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/question-stem/a.ts Status: File added to open files impacted by this config file
Info 179  [10:57:40.127] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/question-stem/a.ts Status: File added to open files impacted by this config file
Info 180  [10:57:40.127] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/question-stem/a.ts Status: File added to open files impacted by this config file
Info 181  [10:57:40.127] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/question-stem/a.ts Status: File added to open files impacted by this config file
Info 182  [10:57:40.127] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/question-stem/a.ts Status: File added to open files impacted by this config file
Info 183  [10:57:40.127] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/question-stem/a.ts Status: File added to open files impacted by this config file
Info 184  [10:57:40.127] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/question-stem/a.ts Status: File added to open files impacted by this config file
Info 185  [10:57:40.127] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/question-stem/a.ts Status: File added to open files impacted by this config file
Info 186  [10:57:40.127] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/question-stem/a.ts Status: File added to open files impacted by this config file
Info 187  [10:57:40.127] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/projects/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/question-stem/a.ts Status: File added to open files impacted by this config file
Info 188  [10:57:40.127] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/projects/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/question-stem/a.ts Status: File added to open files impacted by this config file
Info 189  [10:57:40.127] ConfigFilePresence:: Current Watches: Config file:: File: /Users/lixiaokai/code/flame-design-biz/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/question-stem/a.ts Status: File added to open files impacted by this config file
Info 190  [10:57:40.127] For info: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/question-stem/a.ts :: Config file name: /Users/lixiaokai/code/flame-design-biz/tsconfig.json
Info 191  [10:57:40.128] Project '/Users/lixiaokai/code/flame-design-biz/tsconfig.json' (Configured)
	Files (462)

-----------------------------------------------
Open files: 
	FileName: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/question-stem/a.ts ProjectRootPath: undefined
		Projects: /Users/lixiaokai/code/flame-design-biz/tsconfig.json
Info 191  [10:57:42.860] Search path: /Users/lixiaokai/code/flame-design-biz/node_modules/@angular/core
Info 192  [10:57:42.861] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/node_modules/@angular/core/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: /Users/lixiaokai/code/flame-design-biz/node_modules/@angular/core/core.d.ts Status: File added to open files impacted by this config file
Info 193  [10:57:42.861] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/node_modules/@angular/core/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: /Users/lixiaokai/code/flame-design-biz/node_modules/@angular/core/core.d.ts Status: File added to open files impacted by this config file
Info 194  [10:57:42.861] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/node_modules/@angular/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: /Users/lixiaokai/code/flame-design-biz/node_modules/@angular/core/core.d.ts Status: File added to open files impacted by this config file
Info 195  [10:57:42.861] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/node_modules/@angular/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: /Users/lixiaokai/code/flame-design-biz/node_modules/@angular/core/core.d.ts Status: File added to open files impacted by this config file
Info 196  [10:57:42.861] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/node_modules/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: /Users/lixiaokai/code/flame-design-biz/node_modules/@angular/core/core.d.ts Status: File added to open files impacted by this config file
Info 197  [10:57:42.861] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/node_modules/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: /Users/lixiaokai/code/flame-design-biz/node_modules/@angular/core/core.d.ts Status: File added to open files impacted by this config file
Info 198  [10:57:42.861] For info: /Users/lixiaokai/code/flame-design-biz/node_modules/@angular/core/core.d.ts :: No config files found.
Info 199  [10:57:42.861] Starting updateGraphWorker: Project: /Users/lixiaokai/code/flame-design-biz/tsconfig.json
Info 200  [10:57:43.134] Finishing updateGraphWorker: Project: /Users/lixiaokai/code/flame-design-biz/tsconfig.json Version: 6 structureChanged: true Elapsed: 272.3506019115448ms
Info 201  [10:57:43.134] Different program with same set of files:: structureIsReused:: 0
Info 202  [10:57:43.142] Project '/Users/lixiaokai/code/flame-design-biz/tsconfig.json' (Configured)
	Files (462)

-----------------------------------------------
Open files: 
	FileName: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/question-stem/a.ts ProjectRootPath: undefined
		Projects: /Users/lixiaokai/code/flame-design-biz/tsconfig.json
	FileName: /Users/lixiaokai/code/flame-design-biz/node_modules/@angular/core/core.d.ts ProjectRootPath: undefined
		Projects: /Users/lixiaokai/code/flame-design-biz/tsconfig.json
Info 202  [10:57:43.153] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/node_modules/@angular/core/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles:  Status: File removed from open files impacted by this config file
Info 203  [10:57:43.153] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/node_modules/@angular/core/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles:  Status: File removed from open files impacted by this config file
Info 204  [10:57:43.153] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/node_modules/@angular/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles:  Status: File removed from open files impacted by this config file
Info 205  [10:57:43.153] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/node_modules/@angular/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles:  Status: File removed from open files impacted by this config file
Info 206  [10:57:43.153] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/node_modules/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles:  Status: File removed from open files impacted by this config file
Info 207  [10:57:43.153] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/node_modules/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles:  Status: File removed from open files impacted by this config file
Info 208  [10:57:43.153] Project '/Users/lixiaokai/code/flame-design-biz/tsconfig.json' (Configured)
	Files (462)

-----------------------------------------------
Open files: 
	FileName: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/question-stem/a.ts ProjectRootPath: undefined
		Projects: /Users/lixiaokai/code/flame-design-biz/tsconfig.json
Info 208  [10:57:43.443] Starting updateGraphWorker: Project: /Users/lixiaokai/code/flame-design-biz/tsconfig.json
Info 209  [10:57:43.859] Finishing updateGraphWorker: Project: /Users/lixiaokai/code/flame-design-biz/tsconfig.json Version: 7 structureChanged: true Elapsed: 416.6193460226059ms
Info 210  [10:57:43.860] Different program with same set of files:: structureIsReused:: 0
Info 211  [10:57:44.529] Starting updateGraphWorker: Project: /Users/lixiaokai/code/flame-design-biz/tsconfig.json
Info 212  [10:57:45.677] Finishing updateGraphWorker: Project: /Users/lixiaokai/code/flame-design-biz/tsconfig.json Version: 8 structureChanged: true Elapsed: 1146.7593740224838ms
Info 213  [10:57:45.677] Different program with same set of files:: structureIsReused:: 1
Info 214  [10:57:47.23] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/question-stem/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles:  Status: File removed from open files impacted by this config file
Info 215  [10:57:47.23] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/question-stem/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles:  Status: File removed from open files impacted by this config file
Info 216  [10:57:47.23] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles:  Status: File removed from open files impacted by this config file
Info 217  [10:57:47.23] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles:  Status: File removed from open files impacted by this config file
Info 218  [10:57:47.23] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles:  Status: File removed from open files impacted by this config file
Info 219  [10:57:47.23] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles:  Status: File removed from open files impacted by this config file
Info 220  [10:57:47.23] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles:  Status: File removed from open files impacted by this config file
Info 221  [10:57:47.23] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles:  Status: File removed from open files impacted by this config file
Info 222  [10:57:47.23] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles:  Status: File removed from open files impacted by this config file
Info 223  [10:57:47.23] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles:  Status: File removed from open files impacted by this config file
Info 224  [10:57:47.23] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/projects/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles:  Status: File removed from open files impacted by this config file
Info 225  [10:57:47.23] ConfigFilePresence:: Current Watches: :: File: /Users/lixiaokai/code/flame-design-biz/projects/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles:  Status: File removed from open files impacted by this config file
Info 226  [10:57:47.23] ConfigFilePresence:: Current Watches: Config file:: File: /Users/lixiaokai/code/flame-design-biz/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles:  Status: File removed from open files impacted by this config file
Info 227  [10:57:47.24] FileWatcher:: Added:: WatchInfo: /Users/lixiaokai/code/flame-design-biz/projects/flame-design-biz/src/lib/question-content/question-stem/a.ts 500 {"watchFile":3,"watchDirectory":0,"fallbackPolling":2} Project:  WatchType: Closed Script info
Info 228  [10:57:47.24] Project '/Users/lixiaokai/code/flame-design-biz/tsconfig.json' (Configured)
	Files (462)

-----------------------------------------------
Open files: 
Info 228  [10:57:47.313] Starting updateGraphWorker: Project: /Users/lixiaokai/code/flame-design-biz/tsconfig.json
Info 229  [10:57:47.388] Finishing updateGraphWorker: Project: /Users/lixiaokai/code/flame-design-biz/tsconfig.json Version: 9 structureChanged: true Elapsed: 75.20476508140564ms
Info 230  [10:57:47.388] Different program with same set of files:: structureIsReused:: 1
```

### **Screenshots**

![Jul-01-2021 10-45-40](https://user-images.githubusercontent.com/7534668/124057320-d5de6b00-da59-11eb-9e25-e1976a14444b.gif)

## 🌍  Your Environment
**Angular Version:**
```
Angular CLI: 10.2.3
Node: 12.22.1
OS: darwin x64

Angular: 10.2.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.3
@angular-devkit/build-angular   0.1002.3
@angular-devkit/core            10.2.3
@angular-devkit/schematics      10.2.3
@angular/cli                    10.2.3
@schematics/angular             10.2.3
@schematics/update              0.1002.3
ng-packagr                      10.1.2
rxjs                            6.6.7
typescript                      4.0.8
```

Extension Version:
<pre><code>
v12.1.0

</code></pre>

VSCode Version:
<pre><code>
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0
</code></pre>

Operating System:
<pre><code>
macOS Big Sur 11.4 (20F71)
</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment] 2021-07-01 18:18
That's pretty weird! I wasn't able to reproduce this with the directions given. Are you able to share a project that this can be reproduced in?

**Comment by atscott** [comment] 2021-07-14 18:36
@littlee quick ping on this. I still can't reproduce this in my own projects so it would be great if you could provide one that you're having trouble with.

**Comment by littlee** [comment] 2021-07-15 01:29
@atscott I finally solve it by completely uninstalling vscode & all extensions and re-install it again, it works fine so far

**Comment by atscott** [comment] 2021-07-16 19:08
Hmm, okay. I'm going to close this since we can't reproduce it anymore. Please do file a new issue if you come across the problem again!

**Closed by atscott** 2021-07-16 19:08 UTC
Labels: bug, needs repro
