### ISSUE TITLE
Intellisense starts up very slowly for large projects

### ISSUE THREAD

**Issue by JohnnyDevNull** [angular/vscode-ng-language-service#336] opened 2019-06-03 09:00 UTC
Original: https://github.com/angular/vscode-ng-language-service/issues/318

## Description:

Well i've tried now and for me the problems stay the same. Intellisense in a class to own property does take too long to pop up. With disabled language service it just works fine. Even though it is a reference on a class property itself.

But when i hover or force the intellisense it takes always ~ 20 and above seconds to load. Thats horrible. The only way to get it back is disabling the vs-code plugin.

![image](https://user-images.githubusercontent.com/5759334/58789337-2e7a7a00-85ee-11e9-9bf7-14216b9a01bf.png)

![image](https://user-images.githubusercontent.com/5759334/58789380-47832b00-85ee-11e9-8785-a68e4132dec8.png)

![image](https://user-images.githubusercontent.com/5759334/58789413-58cc3780-85ee-11e9-9423-9a68492c20d2.png)

**Extension-Log:**

![image](https://user-images.githubusercontent.com/5759334/58790127-0429bc00-85f0-11e9-97ad-721deb2f5286.png)

**My setup:**

* Big project with a lot of modules per lazy loading
* Some libraries like  DevExtreme, ng-bootstrap, lodash, moment, etc
* Our own internal angular library
* Angular Version 7.2.15
* Angular Language Service Plugin 0.800.0

## Reproduction:

I did take a look at the extensions log and played a bit around and the following i can say:

![image](https://user-images.githubusercontent.com/5759334/58790849-718a1c80-85f1-11e9-83a3-280e15d83654.png)

* **open only 1 file**, e.g. any component.ts
* take a look at the plugins debug output
* wait until **getTemplateReferences** comes in
* close the actual file and reopen it
* take a look at the plugins debug console, you should now see that everything has to be loaded again because of the **remove project** section
* it takes the same time as the first **getTemplateReferences**

## Possible reason:

I think the problem is, that the extension always initialize the complete project stack on each file open/close not as the default vscode behaviour the first time a file gets opened. This happens only when only one single file opend and directly closed. As long as other files stay opened the plugin keeps the data, but if you close also the last open file (editor) then the **project remove** section appears in the log and the plugin remove the loaded references. Now next time you open a new file it has to complete reinitialize the references.

![image](https://user-images.githubusercontent.com/5759334/58790966-ac8c5000-85f1-11e9-8422-e4d1be9a660f.png)

## Possible solution:

* Keep the references also when the last editor is closed and reinitialize only on window reload or startup or split it in small and complete reload. The small could be a reload of only changed/new/moved files and the complete on first file opened.
* Add a loading spinner like the default JS/TS initializing do, so that the developer get a response from the plugin that it's loading, if that is possible...

**Comment by JonWallsten** [comment] 2019-06-03 09:29
@JohnnyDevNull I think you might have the wrong version.
![image](https://user-images.githubusercontent.com/5993909/58791604-cf6b3400-85f2-11e9-8238-c3f263115160.png)

**Comment by JohnnyDevNull** [comment] 2019-06-03 09:35
@JonWallsten no i haven't. I can't upgrade all our 10+ projects angular versions.

The vscode plugin uses its own:

![image](https://user-images.githubusercontent.com/5759334/58792066-be6ef280-85f3-11e9-8356-88253a54d884.png)

**Comment by JohnnyDevNull** [comment] 2019-06-03 09:40
@JonWallsten may it be, but does it also reinitalize on each open/close action with the new?

**Comment by JonWallsten** [comment] 2019-06-03 09:54
I takes 7 seconds for me the first time, and then 0ms for the subsequent files.
![image](https://user-images.githubusercontent.com/5993909/58793365-3b02d080-85f6-11e9-9525-fc933f321ea3.png)

**Comment by JohnnyDevNull** [comment] 2019-06-03 10:01
Well, how big is your project?

I have here a pretty big project with ~ 100 modules loaded per lazy loading and some angular libraries. DevExtreme, ng-bootstrap, lodash, moment and oauth...

The process to reproduce...

1. open any component.ts
2. take a look at the plugins debug output
3. wait until getTemplateReferences comes in
4. close the actual file and reopen it
5. take a  look at the plugins debug console, you should now see that everything has to be loaded again because of the "remove project"
6. it takes the same time as the first getTemplateReferences

**Comment by JonWallsten** [comment] 2019-06-03 10:21
Let just say ours is tiny compared to yours. 
I checked my log again. I don't have those "remove project" at all.
And I can't reproduce with your steps. I also installed the old plugin again to check the log. 
It actually looks fine in the log, it's just super slow. I guess someone with better knowledge about this need to help you.

**Comment by JohnnyDevNull** [comment] 2019-06-03 10:48
it is important to know that you have to run it in administrator mode in windows to get more detail and i use the system setup instead of the users.

**Comment by JohnnyDevNull** [comment] 2019-06-03 10:52
Also one thing is importand... as long as you have other files open the cleanup won't happen. Only when you close all open files (editors) the **remove project** seaction appears and from that moment it has to initalize complete again.

So when you are a developer who like a clean editor with not much many open files then you run devinitly in this problem with the described initializing/cleanup loop from the angular plugin.

**Comment by jpike88** [comment] 2019-06-03 11:11
@JohnnyDevNull I'm super curious.

https://github.com/cyrilletuzi/vscode-typescript-angular-plugin

^ try this, and see if the issues remain. You're using inline templates I noticed, so I think it's worth seeing if this helps. I'm still trying to figure out whether to move to this one. Can you take a closer look at your CPU/memory usage while it hangs like that?

**Comment by nhustak** [comment] 2019-06-03 12:32
@JohnnyDevNull   I have replicated the issue per your description (I also have a large number of components, DevExtreme, etc).    Opened a single ts file.   Long delay.  Opened a second one.  Instant.  Closed both files.   Reopened single file.  Long delay.  Great find.  At least a quick work around is..never close all files 8).

**Comment by JonWallsten** [comment] 2019-06-03 12:45
@JohnnyDevNull That explains it. I usually just close all the files if there's some issue or something is slow. So it didn't affect me when I tried.

**Comment by kyliau** [comment] 2019-06-03 21:28
@JohnnyDevNull thank you for the feedback! I'm curious, has the language service ever worked for you?
As far as I know, the architecture of the language service has been this way since the first release.
Once I have the tsserver plugin working, I'd like to investigate if this issue could be solved by caching TS programs.

**Comment by JohnnyDevNull** [comment] 2019-06-04 05:45
In large projects not really. I'am a fan of having not much open editors so i often walking in this reinitializing loop. In our smaller projects i haven't recognized this issue, but since i'am on a migration project from migrating a old Java Swing ADF application to Angular this is a huge problem for me and my colleagues and you won't see any loading spinner that the plugin is loading. So for the enduser it seems that the IntelliSense is broken. It would be nice if there is a way to hang in a loading animation like the JS/TS Language Service does in the footer on the bottom left.

**Comment by jpike88** [comment] 2019-06-04 06:13
Would be great if google dedicated more resources to this, angular and TS go hand in hand, and vscode is pretty much what everyone uses for it...

**Comment by jpike88** [comment] 2019-06-04 08:09
Just letting you all know, I'm definitely noticing much larger processing times using that plugin than the one (now deprecated) which used the built in tsserver.

**Comment by JohnnyDevNull** [comment] 2019-06-04 09:32
I think the most problems coming from the duplicate tsserver running. I also recognize performance problems from jump to source or displaying library informations on hovering types and displaying inline docs with pressed CTRL and hovering. While here the debug output from the plugin looks smooth there is invisible blocking time between the **Search Path** step and the **Config file name**

Reproduction:

1. define something like this:

```ts
  public gridEditingOptions: DevExpress.ui.dxDataGridOptions['editing'] = {
    mode: 'batch',
    allowUpdating: true,
    allowAdding: true,
    allowDeleting: true,
    startEditAction: 'dblClick',
    selectTextOnEditStart: true,
    useIcons: true
  };
```

2. hovering the type goes mostly fast: 
![image](https://user-images.githubusercontent.com/5759334/58867740-4bc94a00-86bb-11e9-88e4-b014899829c4.png)

3. now move away hover it again and press and hold CTRL:
![image](https://user-images.githubusercontent.com/5759334/58868221-2d178300-86bc-11e9-94a9-7422d15e2e47.png)

Some times it works fast when only hovering, but mostly especially with pressed CTRL it takes some time, but the debug console looks clean.

**Comment by kyliau** [comment] 2019-11-12 22:02
Update: v0.900.0 should have solved most performance issues. It's a complete rewrite of the underlying language service, and much improvements have been made to speed up initial load time and incremental parsing.

**Comment by nhustak** [comment] 2019-11-12 22:13
That is awesome to hear.

**Comment by kyliau** [comment] 2019-11-12 22:30
Here's some highlights on what we did to improve performance:

1. Project management is now completely managed by TypeScript. 
The code was forked from TypeScript before, but now it has been completely removed.
2. Cache module resolution at startup
Earlier versions do not cache this data, and it's why performance suffered. We saw improvements in terms of number of filesystem operations by as much as 100x.
3. Better incremental parsing by carefully invalidating part of the Program. 
For example, changes to an external template will not change the Program, thus no extra computation.
4. Reuse single instance of StaticReflector and Resolver
These were thrown away whenever the Program changes, but now a single instance is used throughout the lifetime of the service.

All these changes are in version 9 of the language service. An RC version has been released and could be downloaded from the [Release](https://github.com/angular/vscode-ng-language-service/releases) page. The new extension will be published to the marketplace in a few weeks time.

**Comment by kyliau** [comment] 2019-11-25 19:48
The new extension is now live. Please download it from https://marketplace.visualstudio.com/items?itemName=Angular.ng-template
I'd like to close this issue for now. If there's any performance bugs that remain, please open a new issue. Thank you!

**Closed by kyliau** 2019-11-25 19:48 UTC
Labels: performance
