### ISSUE TITLE
Extension is locking files created under a directory that should be excluded by settings.json file

### ISSUE THREAD

**Issue by nicorac** [angular/vscode-ng-language-service#1587] opened 2021-12-23 14:44 UTC
### Description

I'm writing an ng+electron application.
Running `npm run build` will run several build steps:

1. run `build-ng` to build Angular app to `/.dist-angular`
2. run `build-electron` to build Electron app (together wih the result of step 1) to `/.dist-electron`
3. move files from `/.dist-electron/win-unpacked` to final `/dist`, which will be used for distribution
4. delete previous steps dirs `/.dist-angular` and `/.dist-electron`

I'm getting this error at step 3):

```
Error: EPERM: operation not permitted, rename './.dist-electron/win-unpacked' -> './dist'
    at Object.renameSync (fs.js:794:3)
    at Object.<anonymous> (C:\Sorgenti\electron-builder-test\build_scripts\postbuild-electron.js:15:4)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -4048,
  syscall: 'rename',
  code: 'EPERM',
  path: './.dist-electron/win-unpacked',
  dest: './dist'
}
```

Angular Language Service keeps a lock on `./.dist-electron/win-unpacked` folder, despite the fact I've excluded it in `.vscode/settings.json`:

```
{
    "angular.enable-strict-mode-prompt": false,
    "files.watcherExclude": {
      "**/node_modules/": true,
      "**/.dist-angular/**": true,
      "**/.dist-electron/**": true,
      "**/dist/**": true
    }
}
```

Killing this process
```
"C:\Program Files\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\user\.vscode\extensions\angular.ng-template-13.1.0\server --logToConsole --ngProbeLocations c:\Users\user\.vscode\extensions\angular.ng-template-13.1.0,c:\sources\electron-builder-test --includeAutomaticOptionalChainCompletions --includeCompletionsWithSnippetText --tsProbeLocations ,c:\Users\user\.vscode\extensions\angular.ng-template-13.1.0,c:\sources\electron-builder-test --node-ipc --clientProcessId=11984
```
is enough to let the build process to complete without errors.

I've prepared a test repository to reproduce the bug:
https://github.com/nicorac/electron-builder-test

## Reproduction

1. checkout the test repo above
2. run `npm install`
3. open at least one `.ts` file to let language server start
3. run `npm run build`

## 🌍  Your Environment
**Angular Version:**
<pre><code>Angular CLI: 12.1.4
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.1.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.4
@angular-devkit/build-angular   12.1.4
@angular-devkit/core            12.1.4
@angular-devkit/schematics      12.1.4
@angular/cli                    12.1.4
@schematics/angular             12.1.4
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

Extension Version:
<pre><code>13.1.0</code></pre>

VSCode Version:
<pre><code>Version: 1.63.2 (system setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042</code></pre>

Operating System:
<pre><code>Windows 10-20H2 Pro x64 build 19042.1415</code></pre>

**Comment by atscott** [comment] 2021-12-28 18:48
`files.watcherExclude` is for editor watchers/searches but does not apply to extensions. What you're looking for is the `watchOptions` of `tsserver`. Try adding this to your `tsconfig`:

```
  "watchOptions": {
    "excludeDirectories": [
      "**/.dist-angular/**",
      "**/.dist-electron/**",
      "**/dist/**"
    ],
  },
```

I had #1324 open to allow configuring the `watchOptions` of the extension in a similar way to `tsserver` rather than having to do it in each project's `tsconfig` but closed it due to lack of community interest.

Closing as duplicate of #1398 for the failure to rename the directory.

**Closed by atscott** 2021-12-28 18:48 UTC
Labels: bug
