### ISSUE TITLE
index value is not number error in template

### ISSUE THREAD

**Issue by 1antares1** [angular/vscode-ng-language-service#675] opened 2020-03-08 00:12 UTC
**Describe the bug**

Showing error for index value from ngFor is not numeric value.

```
(variable) i
Expected a numeric typeng(0)
```

**To Reproduce**

**Expected behavior**

**Logs**

Please attach two logs:

Console output (Go to toolbar --> View --> Output, and copy the contents)
Log file (Path is printed to the console output at startup)

**Screenshots**

![image](https://user-images.githubusercontent.com/14783925/76154274-ebcf5c00-60af-11ea-9b2c-c0b7d53c161d.png)

**Comment by ayazhafiz** [comment] 2020-03-08 00:56
This is a duplicate of #670. Can you please list the logs as requested in the issue template?

**Comment by ivanwonder** [comment] 2020-03-10 04:46
`(variable) i: index`
@1antares1 Looks like the language service infers the type of `i` to be `index` in your component context.

**Comment by ayazhafiz** [comment] 2020-03-11 01:34
Fixed by @ivanwonder's PR: angular/angular#35982. If you experience more of this, please open a new issue :)

**Closed by ayazhafiz** 2020-03-11 01:34 UTC
Labels: bug
