### ISSUE TITLE
v16.0 breaks renaming  (once again) 

### ISSUE THREAD

**Issue by vrubezhny** [angular/vscode-ng-language-service#1893] opened 2023-05-15 17:21 UTC
# 🐞 bug report

### Is this a regression?

Yes. The issue was fixed (I believe a few times already) last time -  for v.14 - #1685 

 Yes, the previous version in which this bug was not present was: ....

### Description

If, using WildWebDeveloper v.1.1.0 (embeds @anguaar/language-server v.16.0.0), try to remane a variable, a function, etc using `Refactorings->Rename` - no Rename Wizard appears. A message dialogue appears instead with the following message:

![Screenshot from 2023-05-15 16-03-28](https://github.com/angular/vscode-ng-language-service/assets/620781/ddf6d10a-4d2a-450d-a4f6-c1dac5525cfe)

Disabling the Algular Language Server use with TypeScript content type restores the Rename Wizard functionality.
So it looks like once again Algular LS overrides the renaming which doesn't allow built in TS renaming (Not proved though).

See: https://github.com/eclipse/wildwebdeveloper/issues/1209 

## Bug Type
What does this bug affect

- [ ] Angular Language Service VSCode extension
- [x] Angular Language Service server

## Reproduction

1. Using WildWebDeveloper v.1.1.0, create a General project. Create a simple TypeScript file with a variable or a function declaration. No need to have an Angular project to reproduce.
2. Set cursor into a name of variable/function created, Right-mouse click and select `Refactorings->Rename` context menu item. 
3. See "Rename - The Rename request is not valid at the given position` - like error message appeared instead of the Rename Wizard.

**Expected behavior**

The Rename Wizard is to appear with a suggestion to type a new name to continue the rename operation

### **Logs**

LS Logs between the invocation of `Refactorings->Rename` and the appearance of the error message (that appears instead of the Rename Wizard):

<pre><code>

[2023-05-15T16:49:46.978392068+02:00] LSP4E_TO_LANGUAGE_SERVER org.eclipse.wildwebdeveloper.jsts:
{"jsonrpc":"2.0","id":"44","method":"textDocument/prepareRename","params":{"textDocument":{"uri":"file:///home/jeremy/projects/runtime-wwd-0.15/test/test.ts"},"position":{"line":0,"character":12}}}

[2023-05-15T16:49:46.981353288+02:00] LANGUAGE_SERVER_TO_LSP4E org.eclipse.wildwebdeveloper.jsts:
{"jsonrpc":"2.0","id":"44","result":{"start":{"line":0,"character":9},"end":{"line":0,"character":13}}}

</code></pre>

No continuation containing `textDocument/rename` -like method appears because the Rename Wizard is not invoked.

### **Screenshots**

![Screenshot from 2023-05-15 16-03-28](https://github.com/angular/vscode-ng-language-service/assets/620781/ddf6d10a-4d2a-450d-a4f6-c1dac5525cfe)

## 🌍  Your Environment
**Angular Version:**
<pre><code>

`@angular/language-server` v.16.0.0

</code></pre>

Extension Version:
<pre><code>

`@angular/language-server` v./16.0.0

</code></pre>

Operating System:
<pre><code>

- Fedora 38,
- Eclipse JEE 2023-06 M2 + M2E-2.3.0 (snapshot) + WildWebDeveloper 1.1.0

</code></pre>

**Comment by atscott** [comment] 2023-05-19 15:13
I'm not seeing anything here that indicates this is an issue with the Angular Language Server rather than an issue with WildWebDeveloper's integration. The issue from v14 was entirely different and not reintroduced in v16. Closing unless there is more information from WildWebDeveloper about how this is a problem with our package rather than the Eclipse extension.

**Closed by atscott** 2023-05-19 15:13 UTC
Labels: bug

**Comment by vrubezhny** [comment] 2023-05-22 11:38
@atscott Well. Thanks for taking a look at this.

**Comment by vrubezhny** [comment] 2023-05-23 17:49
@atscott  Problem is that Angular LS reports that it has `prepareRename` capability, but being requested to prepare rename for a variable or a function in a TypeScript returns `null` (note that I'm talking on a plain simple TypeScript file that doesn't really uses any angular stuff):

```
[2023-05-23T19:32:53.975981187+02:00] LSP4E_TO_LANGUAGE_SERVER org.eclipse.wildwebdeveloper.angular:
{"jsonrpc":"2.0","id":"7","method":"textDocument/prepareRename","params":{"textDocument":{"uri":"file:///home/jeremy/projects/runtime-wwd-0.15/eslint/folding-test.ts"},"position":{"line":1,"character":11}}}

[2023-05-23T19:32:53.977718100+02:00] LANGUAGE_SERVER_TO_LSP4E org.eclipse.wildwebdeveloper.angular:
{"jsonrpc":"2.0","id":"7","result":null}
```

Is `prepareRename`/`rename` are really realized and functional or the `prepareRename` capability is erroneously reported?

**Comment by mickaelistria** [comment] 2023-05-23 18:40
I agress with @vrubezhny that what seems strange here is that Angular LS sometimes return a successful "preopareRename" result but is actually not capable of performing the rename...

**Comment by atscott** [comment] 2023-05-25 20:11
The Angular Language Service does provide some renaming in Angular-specific contexts in typescript files, including inline templates. This is why it indicates that there is rename capability in the files. This does not mean that it has to provide rename capability at all the same locations that typescript does. `null` is an allowed response for prepareRename, and means the given location is not valid for that provider. For the Angular Language Service, this is correct for a variable in a TypeScript file. In VSCode, if there are multiple rename providers, it continues to query each one until the first one gives a response: https://github.com/microsoft/vscode/blob/ea4d99921cc790d49194e897021faee02a1847f7/src/vs/editor/contrib/rename/rename.ts#L58-L72

I’m not aware of how eclipse handles this situation, but it seems like the problem is with Eclipse. Also worth noting that this behavior has not changed in v16 compared to previous versions.

**Comment by vrubezhny** [comment] 2023-05-25 21:56
@atscott Thanks for the explanation and an example!
