### ISSUE TITLE
Angular 15 Standalone Components support

### ISSUE THREAD

**Issue by sherifzanaty** [angular/vscode-ng-language-service#1839] opened 2022-12-13 17:11 UTC
When creating a standalone component that has its own dependency imports in the component's class, I get the template error "*** is not a known element" for those imported components, while "ng serve" runs successfully without any errors.

Does the Angular 15 Standalone Components feature is supported?  

Feature Type
Standalone Components support for Angular Language Service VSCode extension

Alternatives:
Using temporary NgModule to avoid template error highlights

**Comment by atscott** [comment] 2022-12-13 17:13
Are you using the most recent version of the extension? Yes, this is supported in the most recent version. 

Closing since this is supported in the most recent version of the extension and there's not enough information here to reproduce any issues.

**Closed by atscott** 2022-12-13 17:13 UTC
Labels: feature

**Comment by sherifzanaty** [comment] 2022-12-13 17:17
Yes, I'm using the most recent version v15.0.3, and tried uninstalling the extension and reinstalling it again and also tried different PCs with no success.
