### ISSUE TITLE
Update plugin to use Angular 6

### ISSUE THREAD

**Issue by thw0rted** [angular/vscode-ng-language-service#264] opened 2018-06-25 08:30 UTC
Plugin is still built against Angular 5, should be updated to Angular 6.  Might resolve #256 , and [this comment on an Angular issue](https://github.com/angular/angular/issues/18248#issuecomment-399703529) suggests that it's necessary for the new type checker to show up (?), which would make 

    <p *ngIf="foo">{{foo.length}}</p>

stop red-lining `foo.length` when `strictNullChecks` is turned on.

As an aside, if that comment is mistaken and that edge-case still isn't handled even when built against latest Angular, please let me know and I'll open a separate issue to make sure it gets tracked.  I thought this was what #71 was talking about but it's a separate case.  I'm hoping that this is an easy fix, and will also cover `*ngIf="foo && (foo.length > 2)"` red-lining `foo.length` (even though the and-operator should remove null from foo's type before evaluating).

**Comment by Sebastiandg7** [comment] 2018-06-26 23:46
Maybe duplicate of  #256

**Comment by thw0rted** [comment] 2018-06-27 07:11
I did reference that issue, but I think this should remain open as its own thing because a) it might be possible to resolve #256 without resolving this issue and b) it might be possible to build against Angular 6 without actually resolving the template-scope problem I give as an example.  I would like to make sure my specific problem (incorrect redlining in templates) actually gets resolved.

**Comment by aj-r** [comment] 2018-07-06 14:03
This plugin is basically unusable for us right now since we take advantage of TS 2.7 features like `strictPropertyInitialization`. Because of this our HTML files are covered in errors like this:

```
[Angular] Identifier 'xxx' is not defined. '<anonymous>' does not contain such a member
```

Angular 6 has been out for 2 months now - it would be nice to see this plugin updated.

**Comment by JitinDhillon** [comment] 2018-07-19 21:00
Is work even happening on this plugin? I see that the last commit was over 6 months ago.

**Comment by CodySchrank** [comment] 2018-07-23 04:45
@JitinDhillon Seems like this has been abandoned.  Unfortunately I don't know of any maintained forks or alternatives.

**Comment by thomas-parrish** [comment] 2018-07-23 12:46
Real shame that this has been abandoned.

**Comment by watabtme** [comment] 2018-08-14 21:00
@chuckjaz @DBosley is it possible to get some information regarding the Angular team's intention to keep this project alive? There are lots of glaring open issues at the moment and it seems like this project is abandoned. If you guys are no longer maintaining this, is it possible to assign someone else from the Angular team?

**Comment by universonic** [comment] 2018-08-17 07:44
Hey guys, I have just made a PR to the master branch in order to support the latest Angular v6. (#276 ). I need someone to help me to take a look at those changes.

**Comment by Teamop** [comment] 2018-08-30 11:33
v0.1.10 is out with angular-language-service 6.1 and TS 2.7, thanks @kyliau

**Comment by thw0rted** [comment] 2018-08-31 07:37
I still get the "does not contain such a member" error for `myControl.errors?.someErrorName`.  Is that expected to be fixed now that it's using the newer language service / TS version?

**Comment by magnusbakken** [comment] 2018-08-31 08:17
Likewise. I'm on version 0.1.10 now, but I still seem to be getting all the spurious errors I was getting before.

Here's a an example of a case where the language service complains about a nullable value even though I have a surrounding `*ngIf="model !== null` check.

![model-can-not-be-null](https://user-images.githubusercontent.com/284189/44901107-c4534280-ad06-11e8-971f-30e824a1bed1.png)

**Comment by thw0rted** [comment] 2018-08-31 08:48
Yeah, as far as I can tell the improved scoping for ngIf that's supposed to come with the new language service, isn't working.  Other kinds of narrowing don't work either.  For example, I have a class with a method `isFoo(x: any): x is Foo`.  The AOT compiler correctly recognizes this as narrowing the type of the passed variable to be `Foo`, but I get "does not contain such a member" errors in Code when I reference Foo members inside an `*ngIf="isFoo(thing)"`.

**Comment by zacnomore** [comment] 2019-06-03 19:25
This appears fixed a couple ways to sunday.
Up to 6:
https://github.com/angular/vscode-ng-language-service/commit/f5e23171bcfad1d3af55164f9a1ea57f5aa2e0f3

Then 7:
https://github.com/angular/vscode-ng-language-service/commit/2d9310db968aeabcc7948f250dc30323bdbf0379

And 8:
https://github.com/angular/vscode-ng-language-service/commit/c2df2563290e34579a1ff06478f66b8e0c0b07ba

**Comment by kyliau** [comment] 2019-06-03 21:19
Closing this, since as @zacnomore mentioned, the latest version is now using `@angular/language-service` version 8.
Moving forward, I'll make sure the extension is kept up-to-date with Angular release.

**Closed by kyliau** 2019-06-03 21:19 UTC
