### ISSUE TITLE
Type guard not working in View Engine

### ISSUE THREAD

**Issue by imike57** [angular/vscode-ng-language-service#843] opened 2020-07-03 19:01 UTC
Hello,

I have an object with a property wich can be from 2 different models. 

For example 

```typescript
interface Model1 {
  type: "model1",
  name: string,
  age: number
}

interface Model2 {
  type: "model2",
  nickname: string,
  age: number,
  address: {
    street: string,
    zipcode: string
  }
}

user: Model1 | Model2 = {
  type: "model1",
  name: "Toto",
  age: 18
}
```

then in my component template, I would like to test it to know which model is... That's why I added a key "type".. 

But, from the html view, it will show an error 

```html
<ng-container *ngIf="user.type === 'model2'; else mode1Template">
  {{user.nickname}}
  {{user.age}}
  {{user.address.zipcode}}
</ng-container>
<ng-template #mode1Template>
  {{user.name}}
</ng-template>
          
```
So I lose my Type definition inside this scope.. 
![image](https://user-images.githubusercontent.com/24215428/86492918-d7565400-bd6f-11ea-9706-f03c9f8b4090.png)

 
Only the shared properties are available.  If I do the same test in TS side, Typescript will know which model is. There is a way to fix ng language service to work like Typescript in this situation ? 

thanks

**Comment by ayazhafiz** [comment] 2020-07-03 19:26
This is not possible with the current implementation of the language service. Eventually there will be a version of the language service powered by the Ivy compiler that can do this; see the issue “Update on the status of the language service” pinned to this repository for more information.

________________________________
От: imike57 <notifications@github.com>
Отправлено: Friday, July 3, 2020 2:01:34 PM
Кому: angular/vscode-ng-language-service <vscode-ng-language-service@noreply.github.com>
Копия: Subscribed <subscribed@noreply.github.com>
Тема: [angular/vscode-ng-language-service] Type guard not working (#843)


Hello,

I have an object with a property wich can be from 2 different models.

For example

interface Model1 {
  type: "model1",
  name: string,
  age: number
}

interface Model2 {
  type: "model2",
  nickname: string,
  age: number,
  address: {
    street: string,
    zipcode: string
  }
}

user: Model1 | Model2 = {
  type: "model1",
  name: "Toto",
  age: 18
}

then in my component template, I would like to test it to know which model is... That's why I added a key "type"..

But, from the html view, it will show an error

<ng-container *ngIf="user.type === 'model2'; else mode1Template">
  {{user.nickname}}
  {{user.age}}
  {{user.address.zipcode}}
</ng-container>
<ng-template #mode1Template>
  {{user.name}}
</ng-template>


So I lose my Type definition inside this scope..
[image]<https://user-images.githubusercontent.com/24215428/86492918-d7565400-bd6f-11ea-9706-f03c9f8b4090.png>

Only the shared properties are available. If I do the same test in TS side, Typescript will know which model is. There is a way to fix ng language service to work like Typescript in this situation ?

thanks

**Comment by ayazhafiz** [comment] 2020-11-04 21:38
Closing as a dupe of #835

**Closed by ayazhafiz** 2020-11-04 21:38 UTC
Labels: bug
