### ISSUE TITLE
override modifier not supported

### ISSUE THREAD

**Issue by muuvmuuv** [angular/vscode-ng-language-service#1424] opened 2021-06-27 12:55 UTC
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

It is not possible to use the override modifier together with `@Input()`. 

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [x] Angular Language Service server

## Reproduction

1. ng new
2. Create an extended component with an override modifier on an input (noImplicitOverride)
3. Use the component in any template and add that input
4. "Can't bind to 'xxxx' since it isn't a known property of 'xxxxx'."

**Expected behavior**

Like without override

### **Logs**

Log file gives us deep insight into the behavior and performance of the extension. If the issue is a performance
problem or an error occured, please provide the output of the log file below.

Set Angular Log level to verbose.

<pre><code>

</code></pre>

### **Screenshots**

![Example Screenshot](./output.png)

## 🌍  Your Environment
**Angular Version:**
<pre><code>

Angular CLI: 12.1.0
Node: 16.3.0 (Unsupported)
Package Manager: npm 7.17.0
OS: darwin x64

Angular: 12.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.0
@angular-devkit/build-angular   12.1.0
@angular-devkit/core            12.1.0
@angular-devkit/schematics      12.1.0
@schematics/angular             12.1.0
rxjs                            6.6.7
typescript                      4.3.4
webpack                         5.40.0
</code></pre>

Extension Version:
<pre><code>

</code></pre>

VSCode Version:
<pre><code>

v12.0.5
</code></pre>

Operating System:
<pre><code>

macOS 11.4 (Silicon)
</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment] 2021-06-29 21:31
Ah, yes this looks like it would be addressed by updating to typescript 4.3. Closing as duplicate of #1386. Will add a note there about this issue as well.

**Closed by atscott** 2021-06-29 21:31 UTC
Labels: bug
