### ISSUE TITLE
The LS does not recognise components as being standalone

### ISSUE THREAD

**Issue by JulienLecoq** [angular/vscode-ng-language-service#2119] opened 2024-11-20 15:16 UTC
# 🐞 bug report

### Description

Since ``Angular 19``, components are standalone by default. However, the LS does not seems to take that into account. I've migrated my Angular app to Angular 19 so now all my components does not have anymore the ``standalone: true`` line but this cause errors to appears in every template and in every imports: [] because the LS does not consider my components to be standalone.

ps: I don't use VSCode but I use Neovim.

## Bug Type
What does this bug affect

- [ ] Angular Language Service VSCode extension
- [x] Angular Language Service server

## Reproduction

1. Create a new Angular project
2. Migrate the project to Angular 19
3. See the error in app.component.ts saying that 'imports' is only valid on a component that is standalone.

**Expected behavior**

No error should appear.

### **Screenshots**

![Image](https://github.com/user-attachments/assets/6b121391-0298-4075-b577-2b7c08029792)

![Image](https://github.com/user-attachments/assets/0dfcb97b-6faf-4a4f-b936-0d1583b71ff8)

## 🌍  Your Environment
**Angular Version:**

<pre><code>
Angular CLI: 19.0.0
Node: 20.14.0
Package Manager: npm 10.9.0
OS: darwin arm64

Angular: 19.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.0
@angular-devkit/build-angular   19.0.0
@angular-devkit/core            19.0.0
@angular-devkit/schematics      19.0.0
@schematics/angular             19.0.0
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.15.0
</code></pre>

Extension Version:
<pre><code>
v19.0.2
</code></pre>

Operating System:
<pre><code>
macOS Sequoia : 15.0.1
</code></pre>

**Comment by mrentmeister-tt** [comment] 2024-11-20 23:07
I am experiencing this issue as well after updating my Nx monorepo to v19. VSCode extension version 19.0.2.

**Comment by JulienLecoq** [comment] 2024-11-21 23:12
@mrentmeister-tt Mhh, did you try to downgrade the version to v19.0.0 if you can with VSCode? I'm using Mason which automatically manage the language server version so I can't do it with it. I'll try to do it manually without Mason tomorrow to see if it resolve the issue.

**Comment by HymanZHAN** [comment] 2024-11-22 05:18
Encountering the same issue in Neovim as well (also using Mason).

**Comment by alljinx** [comment] 2024-11-22 14:36
Same issue here.

**Comment by looshch** [comment] 2024-11-22 23:10
same here

**Comment by spock123** [comment] 2024-11-25 09:48
I can also add that opening our projects in a mono repo structure, reveals this issue.
Opening each project individually works well.

Hope for a resolution of this as its' very hard to work this way, our mono repo consists of both backend services and 5 angular projects, and we often need to edit multiple projects at the same time. Right now we are forced to use separate VSCode windows for each project.

**Comment by Ask-786** [comment] 2024-11-27 05:17
Did anybody find any workarounds?

**Comment by nagashimam** [comment] 2024-11-28 06:33
I'm using Mason, and re-installing @angular/language-service(not @angular/language-server) that is used by Mason solved  the issue in my case. It's like:

cd ~/.local/share/nvim/mason/packages/angular-language-server/node_modules/@angular/language-server
npm uninstall @angular/language-service
npm install @angular/language-service

**Comment by thaoula** [comment] 2024-11-28 10:55
We are getting the same issue and uninstalling does not fix the problem .. so I just set standalone: true as workaround. Not ideal but better than getting the error.

**Comment by spock123** [comment] 2024-11-28 11:37
@thaoula  We have thousands of components so we're not going to be able to go back and set standalone:true , unfortunately. For now, we are stuck with opening each sub projects in separate VS Code windows.

**Comment by thaoula** [comment] 2024-11-28 11:45
I do not believe it causes a build error .. so you could just set standalone: true when editing the component to suppress the error. It would be easy enough to find an replace standalone: true in the future.

**Comment by spock123** [comment] 2024-11-28 12:28
@thaoula  problem is we import many other components which in turn also import components. Any missing standalone flag  in any of these components will also trigger errors.

We have now disabled the Language Service altogether, because the issues were greater than the benefits.

**Comment by JulienLecoq** [comment] 2024-11-28 13:45
@spock123 But you can do a find & replace to change any:

``@Component({``

To:

```
@Component({
    standalone: true,
```

It takes like 30 seconds to do so.

**Comment by aMytho** [comment] 2024-11-29 03:23
I was also having the issue in neovim/mason. I tried uninstalling/reinstall/update, but that didn't work. However, I found a temporary solution. The problem was that the language service was set to a next/preview build, not the most recent build. The angular server was set to the latest version, but the angular service (a dependency of the server) was on an outdated version. 

cd `~/.local/share/nvim/mason/packages/angular-language-server`
Open the package-lock.json folder. Scroll to the `@angular/language-server` section and examine the dependencies. Mine showed that `@angular/language-service` was set to [19.0.0-next.6](https://www.npmjs.com/package/@angular/language-service/v/19.0.0-next.6)

It should be v19.0.1. (note that the latest version of the language server is 19.0.2, but the latest of the service is 19.0.1).

Change the version of the dependencies to be v19.0.1.
```json
    "node_modules/@angular/language-server": {
      "version": "19.0.2",
      "resolved": "https://registry.npmjs.org/@angular/language-server/-/language-server-19.0.2.tgz",
      "integrity": "sha512-vXDgGgSEzkgftr0+6u88uJr2ic62+fofN2r/G5KNp1CaZoI2zKZWSIo5ZpndIIaanAWaHWMIO8D50Ze2YM69DA==",
      "license": "MIT",
      "dependencies": {
        "@angular/language-service": "19.0.1", // This line was changed -------------------------------
        "vscode-html-languageservice": "^4.2.5",
        "vscode-jsonrpc": "6.0.0",
        "vscode-languageserver": "7.0.0",
        "vscode-languageserver-textdocument": "^1.0.7",
        "vscode-uri": "3.0.7"
      },
      "bin": {
        "ngserver": "bin/ngserver"
      },
      "engines": {
        "node": "^18.19.1 || ^20.11.1"
      }
    },
```

Scroll down to the language-service section. Change its version and URL to be the 19.0.1. **Remove the integrity check if one is listed**. I don't know how to get the new integrity check, but if you know how to locate that then you could replace it.
```json
    "node_modules/@angular/language-server/node_modules/@angular/language-service": {
      "version": "19.0.1",
      "resolved": "https://registry.npmjs.org/@angular/language-service/-/language-service-19.0.1.tgz",
      "license": "MIT",
      "engines": {
        "node": "^18.19.1 || ^20.11.1 || >=22.0.0"
      }
    },

```

Finally, run `npm i`

Everything is working now, but I'm guessing that a package update by mason would break it. I would like an easier fix than this, but this was enough for the moment.

**Comment by devversion** [comment] 2024-12-02 11:34
I don't know what the state of this issue is, but:

- `@angular/language-server` does point to the latest Angular v19 version now
- the latest language service version, released when v19 came out, _should_ work.

I suspect the issue most people are seeing here is that the VSCode extension picks _one_ version of a e.g. monorepo. So, if you have e.g. Angular v18 somewhere in your project, the extension will use and treat the lack of `standalone: true` as `standalone: false`— like it was the case with v18. Can someone with the problem verify this?

The logic is not great, so this could serve as a tracking issue, but we should verify this is the problem first.

**Comment by JulienLecoq** [comment] 2024-12-02 14:05
@aMytho Wonderfull, this works!

**Comment by JulienLecoq** [comment] 2024-12-02 14:10
@devversion For Neovim, the issue was related about how Mason manages the language server. The language server was set to use the language service ``v19.0.0-next.6`` instead of the ``v19.0.1``. So I guess we should open an issue in the Mason GitHub repo.

For VSCode I don't know since I'm not using it.

**Comment by Ask-786** [comment] 2024-12-02 15:53
a new version of `@angular/language-server` has been published now, so everything should work fine now.

**Comment by dzonatan** [comment] 2024-12-02 17:24
mason [has bumped the version too](https://github.com/mason-org/mason-registry/commit/7274b17c11a1adf1ff4569c7c622429d6cb75895), now it works fine for me.

**Comment by spock123** [comment] 2024-12-03 12:52
@Ask-786  Beautiful, works here also! Wonderful! Cheers

**Comment by prashantsaran** [comment] 2024-12-04 09:42
Angular does not provide import property for non-standalone component , you can do the same in the module , i.e., import RouterOutlet in the component's module and it will work.

**Comment by Ask-786** [comment] 2024-12-04 11:59
@prashantsaran We're discussing about angular 19  brother

**Comment by steventhorne** [comment] 2024-12-11 16:33
this has caused issues with projects using a version older than Angular 19, now. It incorrectly detects which angular is being used in the project and tells you that your components are standalone when they're not. Now I need to explicitly add `standalone: false` to all of my components to remove errors that are not actually errors.

**Comment by TobiasNoell** [comment] 2024-12-12 17:06
The issue still persists in VS code with Angular Language Service 19.0.3

**Comment by devversion** [comment] 2024-12-17 08:45
@TobiasNoell Do you have a workspace with multiple versions?

**Comment by TobiasNoell** [comment] 2024-12-17 12:03
> [@TobiasNoell](https://github.com/TobiasNoell) Do you have a workspace with multiple versions?

Yes, but after migrating the other app to Angular 19 as well it seems to be working now

**Comment by devversion** [comment] 2024-12-17 14:33
Exactly, thx for confirming. This is because, as said, the LS currently only sees a single version, choosing the lowest one in the workspace.. It's not ideal and causing these confusing issues.

I'm closing this one as the issue is in practice fixed— while the detection can be improved, and is a separate issue. More precisely, a feature request.

**Closed** 2024-12-17 14:33 UTC
Labels: bug
