### ISSUE TITLE
Identifier 'isActive' is not defined. 'RouterLinkActive' does not contain such a member

### ISSUE THREAD

**Issue by Legited** [angular/vscode-ng-language-service#112] opened 2017-06-20 00:59 UTC
#### Bug, feature request, or proposal:
Bug

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/core 4.2.2
@angular/language-service: 4.2.2
@angular/material: 2.0.0-beta.6

VScode Angular language service throws an error, when following the example from material navigation tabs:
```
<nav md-tab-nav-bar>
  <a md-tab-link
     *ngFor="let link of navLinks"
     [routerLink]="link"
     routerLinkActive #rla="routerLinkActive"
     [active]="rla.isActive">
    {{tabLink.label}}
  </a>
</nav>

```
Error: 

> Identifier 'isActive' is not defined. 'RouterLinkActive' does not contain such a member

What I have is: 
![screen shot 2017-06-19 at 2 33 35 pm](https://user-images.githubusercontent.com/13325924/27300138-a026aee6-54fc-11e7-83ed-cfe3a4f57042.png)

Although the application compiles and works as expected, is there a way to get rid of error?

**Comment by chuckjaz** [comment] 2017-06-22 16:39
Duplicate of #103

**Closed by chuckjaz** 2017-06-22 16:39 UTC
Labels: duplicate
