### ISSUE TITLE
Import necessary modules or components directly from the HTML

### ISSUE THREAD

**Issue by asphub** [angular/vscode-ng-language-service#2024] opened 2024-04-15 04:38 UTC
**Import necessary modules or components directly from the HTML**

# 🚀 feature request

### Description
 Need an option to import necessary modules or components directly from the HTML, at least for the standalone components.

### Feature Type
Implementing this feature would significantly enhance productivity by saving a considerable amount of time coding with Angular version 17 (mostly with standalone).

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

### Quick Fix
 Quick Fix bulb can be used for such imports.

### Screenshot

![image](https://github.com/angular/vscode-ng-language-service/assets/11062009/3c6b26b9-12fa-4c28-8a07-b8a2724af606)

**Comment by R-Bower** [comment] 2024-07-08 20:13
Duplicate: https://github.com/angular/vscode-ng-language-service/issues/1917

**Comment by atscott** [comment] 2024-07-08 20:15
Closing as duplicate of #1917

**Closed by atscott** 2024-07-08 20:15 UTC
Labels: feature
