### ISSUE TITLE
Showing error "cannot read property 'isSkipSelf' of null" and does not validate templates

### ISSUE THREAD

**Issue by mlakmal** [angular/vscode-ng-language-service#181] opened 2017-10-11 00:42 UTC
Using 
VSCode v1.17.1
Workspace typescript v2.5.3
Workspace Angular v4.4.4

instead of showing template validation messages, language service extension is showing below error
"Cannot read property 'isSkipSelf' of null"

![image](https://user-images.githubusercontent.com/2079040/31417085-680af910-adfb-11e7-9573-7d82d85aeac4.png)

**Comment by aitboudad** [comment] 2017-10-16 23:44
probably related to #183

**Comment by chuckjaz** [comment] 2017-12-30 18:04
Can you produce a project that reproduces this and supply a link to the repository?

**Comment by mrahhal** [comment] 2018-01-16 11:25
Also facing this and it's happening in a lot of places. Renders the whole service unusable in the template.

**Comment by fxck** [comment] 2018-01-17 08:52
@chuckjaz do you still need repro?

**Comment by mlakmal** [comment] 2018-01-29 15:10
it will take me sometime to get this setup on repo. basically this is happening when you reference package libraries that are part of your repo and we update master tsconfig paths section to setup the definitions.

Ex: tsconfig
`
"compilerOptions": {
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "pretty": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitUseStrict": false,
    "noFallthroughCasesInSwitch": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "suppressImplicitAnyIndexErrors": true,
    "declaration": false,
    "watch": false,
    "noEmitHelpers": true,
    "baseUrl": ".",
    "paths": {
      "@xyz/uxd": [
        "app/xyz/uxd/public_api"
      ]
    },
    "types": [
      "node",
      "core-js",
      "systemjs",
      "jquery",
      "custom",
      "jasmine"
    ]
  }
`

**Comment by matheo** [comment] 2018-03-07 02:32
Any news on this? it's annoying :(

**Comment by mrahhal** [comment] 2018-03-07 05:33
This stopped happening after updating everything to latest. @matheo maybe check that you have updated the language service extension.

**Comment by myflowpl** [comment] 2018-03-07 11:13
Just run on the same error
turns out I had error inside one of my custom components, it was mistake in import statement in TS file

after fixing the component TS import, the template error was gone

it would be nice to have better error message in this case

**Comment by matheo** [comment] 2018-03-13 00:34
@mrahhal I had the latest extension version
but I had to install `"@angular/language-service": "^5.2.8"` on my Angular 4.4 app to make it work :)
Thanks!

**Comment by jonyadamit** [comment] 2018-04-30 09:06
Happened to me after moving a component and some classes to a different folder.  
After fixing the imports the issue disappeared. (same as @myflowpl )

**Comment by samiujan** [comment] 2018-04-30 19:34
I disabled/reloaded and enabled/reloaded Angular Language Service and the error disappeared

**Comment by splincode** [comment] 2018-05-25 15:04
IDEA 2018.1

![image](https://user-images.githubusercontent.com/12021443/40551564-055ac7e8-6046-11e8-94c0-376591c20d57.png)

**Comment by F0rt1s** [comment] 2018-06-07 18:59
I get the same error in VS Code (most recent version).

**Comment by pburrows** [comment] 2018-06-13 16:03
Using WebStorm, uninstalling @angular/language-service from the project fixed the problem (and no functionality seems to be lost)

**Comment by Polyterative** [comment] 2018-06-20 12:32
Didn't work for me unfortunately in WebStorm

**Comment by chadbr** [comment] 2018-06-21 20:24
same error here on a random file... any way to diagnose?

**Comment by Polyterative** [comment] 2018-06-21 21:46
I was able to solve my issue installing the peerDependencies in the project containing my library. Somehow angular or material are interfering

**Comment by lemoinem** [comment] 2018-09-05 20:58
This error started happening randomly on a project (and templates that haven't been modified since) that was working perfectly with VS Code previous version.
Since we have no way of restarting the TS Service anymore, the only solution is to close and restart VS Code.
This is extremely disruptive.

**Comment by Aphax** [comment] 2018-09-13 14:13
I have the same error suddenly after changing the ngPackage.lib.entryFile, using ng-packagr, when running build : 
```
Cannot read property 'isSkipSelf' of null
TypeError: Cannot read property 'isSkipSelf' of null
    at ProviderElementContext._getDependency (C:\Workspace\csf\node_modules\@angular\compiler\bundles\compiler.umd.js:19521:18)
```
The error comes from Angular compiler

**Comment by csutorasr** [comment] 2018-10-08 10:54
For me unmet peer dependencies caused the problem. After installing them and restarting window everything is resolved.

**Comment by gerrillero** [comment] 2018-11-05 08:55
I got the same issue after installed "Paste JSON as Code" extension in Visual Code. Disabled this extension fix for me the problem.

**Comment by CodeMySofts** [comment] 2018-11-15 21:31
It happened to me today after adding a new dependency. Deleting node_modules and re-installing the packages solved it.

**Comment by spwinner2017** [comment] 2019-03-01 13:23
> I disabled/reloaded and enabled/reloaded Angular Language Service and the error disappeared

worked for me!!!

**Comment by simeyla** [comment] 2019-03-02 00:41
@chuckjaz Anyway this is a repro:

```
@Component({
     selector: '[rr-split-panel-pane',
     template: `<ng-template><ng-content></ng-content></ng-template>`
})
export class SplitPanelPaneComponent extends TemplatePortal
{
    constructor(templateRef: TemplateRef<any>, viewContainerRef: ViewContainerRef) {
        super(templateRef, viewContainerRef);
    }
}
```

Then I get the error doing this:

```
<rr-split-panel-pane>
      content
</rr-split-panel-pane>
```

Interestingly when the bug is fixed the error doesn't go away, hence why restarting might fix it.

I'm not going to tell you what's wrong with the above ;-)
Ok I suppose I should... But it should be pretty obvious. 

Might take a second to spot though :-)

**Comment by chlab** [comment] 2019-03-04 12:52
As others have said, the error is probably coming from somewhere else, it's just an unhelpful error message. What helped me, was running the native TS compiler (`npx tsc`) to see if there were any unresolved imports or similar (and fixing those).

**Comment by jschank** [comment] 2019-04-11 17:01
Please tell me how to disable whatever it is that is causing the rendering of the red squigglies in my code.

**Comment by stephanrauh** [comment] 2019-04-28 15:57
Today I saw this error after confusing an `@Input()` parameter with a constructor parameter. I.e., it should have been

````typescript
  @Input()
  public title: string;
  constructor() {}
````

but for some reason I wrote 

```typescript
constructor(public title: string) {}
```

Is it possible to generate a more helpful message in this case?

**Comment by kyliau** [comment] 2019-04-29 16:33
The original issue `Cannot read property "isSkipSelf" of null` has been fixed in https://github.com/angular/angular/pull/30075

**Comment by Hariprakash1997** [comment] 2019-04-30 08:34
Just close your vs code editor and reopen.It worked for me.

**Comment by tuongthovo** [comment] 2019-07-05 14:01
Restart VS Code solved the error for me, not sure what happen but it just disappeared

**Comment by dixitomkar1809** [comment] 2019-07-12 16:07
How I was able to solve this problem was to update the import statement for a service in my component file, please check your imports :)

**Comment by grantwhitaker06** [comment] 2019-07-29 21:18
Check that all modules in your template file with the error are imported. That was my mistake.

**Comment by bundenilesh** [comment] 2019-10-30 12:30
Close and reopen the VSCode

**Comment by kyliau** [comment] 2019-11-08 23:43
This was fixed in https://github.com/angular/angular/pull/30075

**Closed by kyliau** 2019-11-08 23:43 UTC
Labels: bug, needs repro
