### ISSUE TITLE
"Go to definition" for components in template should work even when strictTemplates=false

### ISSUE THREAD

**Issue by phuctv95** [angular/vscode-ng-language-service#1583] opened 2021-12-09 04:29 UTC
# 🚀 feature request

### Description
When a component is in an embedded view, I can not use the feature "Go to definition" for that component.

![image](https://user-images.githubusercontent.com/20752858/145333798-00f9ad46-2a97-4084-8b15-7385e53f1382.png)

I can set `strictTemplates=true` to workaround, but I think it's not relevant, because the `strictTemplates` is about type checking, and the "Go to definition" should work.

### Feature Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

### Describe the solution you'd like
I would like the "Go to definition" works even when `strictTemplates=false`.

### Describe alternatives you've considered
Set `strictTemplates=true`

**Comment by atscott** [comment] 2021-12-16 18:47
Duplicate of #1418. The current behavior is working as intended. The language service reflects the information made available to the compiler based on the compiler options. If the given compiler options make it so the element in the template is not checked, the language service should not provide information for it.

**Closed by atscott** 2021-12-16 18:47 UTC
Labels: feature
