### ISSUE TITLE
Bad compatibilty with ng-packagr

### ISSUE THREAD

**Issue by Iworb** [angular/vscode-ng-language-service#309] opened 2019-01-23 05:16 UTC
VSCode version: 1.30.2
Language service version: 7.1.4 (fails on 7.2.x aswell)
VSCode extension version: 0.1.11 (latest available).

Rebuilding library throwing this error in most cases until VSCode restart. Then first build is successful and then error throws again and again. Disabling extension fixing this bad behavior.

> BUILD ERROR
> EPERM: operation not permitted, unlink

**Comment by e-davidson** [comment] 2019-02-05 01:00
I'm having this issue as well.

See this issue too.
https://github.com/ng-packagr/ng-packagr/issues/837

**Comment by pfeigl** [comment] 2019-02-06 17:12
This is pretty much a duplicate of #224

**Comment by kyliau** [comment] 2019-11-11 22:09
Tracking it in https://github.com/angular/vscode-ng-language-service/issues/224.
This will be fixed in the v9 release.

**Closed by kyliau** 2019-11-11 22:09 UTC
