### ISSUE TITLE
ngcc error in vsCode with latest updates.

### ISSUE THREAD

**Issue by BribeFromTheHive** [angular/vscode-ng-language-service#1857] opened 2023-02-04 14:59 UTC
# 🐞 bug report

### Is this a regression?

 Not sure how to classify. It was a vsCode update that seems to have triggered this.

### Description

 `Angular extension might not work correctly because ngcc operation failed. Try to invoke ngcc manually by running 'npm/yarn run ngcc'. Please see the extension output for more information.`

## Bug Type
Affects vsCode with this extension enabled.

- [X] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

1. Open vsCode
2. Receive error from Angular Language Service (Extension)

**Expected behavior**

No error occurs.

### **Screenshots**

![image](https://user-images.githubusercontent.com/71581275/216774185-053eb74e-e57a-4d14-bc39-5e557b00868e.png)

## 🌍  Your Environment
**Angular Version:**

![image](https://user-images.githubusercontent.com/71581275/216778736-875842f7-0b44-4551-b371-05199451cd6b.png)
<pre><code>

(unable to get ng version, likely due to this error).

package.json shows @angular/cli at 15.1.3, other @angular/ components at 15.1.2. I changed them all to `latest`, ran npm install, and 0 packages were updated.

</code></pre>

Extension Version:
<pre><code>

v15.1.0

</code></pre>

VSCode Version:
<pre><code>

1.75.0
</code></pre>

Operating System:
<pre><code>

Windows 11
</code></pre>

**Comment by atscott** [comment] 2023-02-04 16:18
* Have you tried running ngcc manually as the error suggests? Does that result in an error as well?
* What version of Angular is your project using? Can you include a project that this error can be reproduced with? 
* Is there any more information about the failure in the logs ("Angular: Open Angular Server log" in the command palette)

**Comment by atscott** [comment] 2023-02-06 17:03
It seems likely that this is an issue with the project/workspace due to being able to run `ng version`. Closing as there's not sufficient information to determine that this is an issue with the extension and I have not been able to reproduce this myself.

**Closed by atscott** 2023-02-06 17:03 UTC
Labels: bug
