### ISSUE TITLE
form tag makes variables not to be recognized in templates

### ISSUE THREAD

**Issue by RoyiNamir** [angular/vscode-ng-language-service#315] opened 2019-02-13 18:16 UTC
Looking at a simple public variable which I have in the `ts` file  : 

      public displayMessage: { [key: string]: string } = {};

![image](https://user-images.githubusercontent.com/2842123/52733600-cfa3dd00-2fcb-11e9-809d-f310b7e9c3e7.png)

It is clearly shows that it doesn't recognize it.

[I know about the hacks that So provies](https://stackoverflow.com/a/53403416/859154) , making  only `truthy / falsy` `ngif's` : (which hides the problem)

![image](https://user-images.githubusercontent.com/2842123/52733699-05e15c80-2fcc-11e9-8d62-4ac00c794e8f.png)

It does work, but let's revert the code for now.

I think it's related to the FORM tag. Look what happens if I remove the form tag : 

No errors & intellisense works : 

![image](https://user-images.githubusercontent.com/2842123/52733788-450fad80-2fcc-11e9-8546-727abcdbec04.png)

I think there is a bug when a FORM tag appears.

Any solution ?

Version: 1.31.1 (user setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Extension version " 0.1.11"

**Comment by andrius-pra** [comment] 2019-09-02 17:43
Duplicate of #126
There is a fix here: angular/angular#29811

**Comment by kyliau** [comment] 2019-11-25 20:13
Will track issue in https://github.com/angular/vscode-ng-language-service/issues/126

**Closed by kyliau** 2019-11-25 20:13 UTC
