### ISSUE TITLE
Doest Not Work with Angular HTML Template and VS Code

### ISSUE THREAD

**Issue by jontiefer** [angular/vscode-ng-language-service#217] opened 2018-01-22 02:20 UTC
I'm not sure what I am doing wrong, but I cannot get any intellisense or editor support for Angular HTML templates with VS Code after installing this template..  It simply does not work.  Neither do I see any color coding or intellisense, everything is pretty much hand-typed like in notepad right now for me with Angular HTML templates.

**Comment by tkoenig89** [comment] 2018-01-22 14:21
@jontiefer did you have a look at the output section of VS Code? There you should find logs from the Language-Service plugin, which might give more details on your case.

**Comment by ankemp** [comment] 2018-01-23 18:14
Related: #214

**Comment by chuckjaz** [comment] 2018-01-23 23:02
Can you try the work around mentioned in #214?

**Comment by briancodes** [comment] 2018-01-25 09:52
I'm using Angular CLI v1.6.4
Angular Language Service: 5.2.1
TypeScript: 2.6.2

Up until two days ago I had intellisense and file reference links in my HTML templates. That functionality seems to be missing now. Think the latest release is causing some issue with my current setup (saw that the extension auto updated recently)

**Comment by rfuhrer** [comment] 2018-01-25 22:42
I tried the workaround in #214 and it didn't seem to change anything.  Maybe I did it wrong?  I didn't see the Angular Language Service version change both times I tired to run it.  I just ran `yarn remove @angular/language-service` and then closed VSCode and reopened it again.  

Here's what I get freshly opening VSCode on a html file and then trying to hover on a half completed variable name:
```
Search path: c:/git/PrimeCore/Prime.Core/ClientApp/app/vendor/tool-view
Config file name: c:/git/PrimeCore/Prime.Core/tsconfig.json
Angular Language Service: 5.2.1
TypeScript: 2.6.2
getTemplateReferences: 3446ms
Add recursive watcher for: c:/git/PrimeCore/Prime.Core
Opened configuration file c:/git/PrimeCore/Prime.Core/tsconfig.json
getTemplateReferences: 0ms
Angular Language Service: 5.2.1
TypeScript: 2.6.2
getTemplateReferences: 27ms
getDiagnostics: 4ms
getHoverAt: 0ms
getHoverAt: 1ms
```
after that, `getHoverAt` and `getCompletions` always takes 0ms and doesn't give any options.

**Comment by briancodes** [comment] 2018-01-25 23:30
@rfuhrer Did you run `yarn install` after the `yarn remove` to update the node_modules? Maybe `yarn clean cache`. It sounds like the language service is still present

**Comment by rfuhrer** [comment] 2018-01-26 00:05
You don't have to do a `yarn install` or  `yarn cache clean` after removing something as yarn actually keeps your node_modules clean and up to date.  I double checked and the language service folder was missing after the remove and reappeared after I re-added it.
I'm also running today's release of VSCode.  

It seems like there's just some kind of disconnect between the HTML and the .ts cause you can see the language service doing stuff while inside a .ts file and it's showing all the nice intellisense stuff:
```
Search path: c:/git/PrimeCore/Prime.Core/node_modules/@angular/material/dialog/typings
Config file name: c:/git/PrimeCore/Prime.Core/tsconfig.json
getTemplateReferences: 0ms
getTemplateReferences: 0ms
getTemplateReferences: 0ms
getCompletions: 1ms
getDiagnostics: 0ms
getHoverAt: 0ms
getHoverAt: 1ms
getCompletions: 0ms
```

**Comment by chuckjaz** [comment] 2018-01-26 01:42
Have you tried this with `0.1.8` of the extension?

#220 should address this issue.

**Comment by rfuhrer** [comment] 2018-01-26 01:57
Yeah it auto updated the extension as @briancodes mentioned. I could manually try installing it with the VSIX but it says 0.18 in the extension screen

**Comment by chuckjaz** [comment] 2018-01-26 02:02
The fact that `Angular Language Service: 5.2.1` is printed twice is an indication that a second project was created for the request. In this case, the language service did not find the `.html` file.

What is the `templateUrl` value you are using? Does the project compile cleanly in AOT?

**Comment by chuckjaz** [comment] 2018-01-26 02:04
@briancodes  Can you produce a project that I can clone that reproduces this?

**Comment by kukjevov** [comment] 2018-01-26 05:21
Same here, after upgrade to 0.1.8, it stopped working in `.html` files. I am goint to try to find out what is the problem :).

**Comment by kukjevov** [comment] 2018-01-26 05:22
Same here, after upgrade to 0.1.8, it stopped working in `.html` files. I am goint to try to find out what is the problem :).

**Comment by m-ghaoui** [comment] 2018-01-26 08:39
It's broken for me as well:

```
Angular Language Service: 5.2.1
TypeScript: 2.6.2
```

I've applied the workaround #214 but it still doesn't work.

**Comment by briancodes** [comment] 2018-01-26 12:03
@chuckjaz Hi. I created a new project with the latest CLI and Angular versions (updated to the latest stable released CLI today). Also have the latest stable VSCode version

https://github.com/briancodes/language-ext-issue217

I put in the details of what is occuring in the `README.md` file

**Comment by snys98** [comment] 2018-01-26 13:35
Angular Language Service: 5.2.1
Extension Version: 0.1.8
TypeScript Version: 2.4.2, 2.6.2 ,2.5.3, 2.7.0-insider

All failed...... emergency, could not working without it!

**Comment by ryanbuening** [comment] 2018-01-26 14:05
0.1.8 isn't working for me either with Angular 5.2.2, TypeScript 2.6.2, and VS Code 1.19.3.

My workaround currently is reverting vscode-ng-language-service to 0.1.7 found here: https://github.com/angular/vscode-ng-language-service/releases/tag/0.1.7

**Comment by rfuhrer** [comment] 2018-01-26 17:14
Can confirm that reverting to 0.1.7 made everything work properly again despite being on the latest version of angular, typescript and VSCode

**Comment by chuckjaz** [comment] 2018-01-26 17:22
@briancodes I cloned https://github.com/briancodes/language-ext-issue217 and it works for me.

I suspect that it might be an issue with paths on Windows so I am trying that now.

**Comment by briancodes** [comment] 2018-01-26 17:37
I'm going to wait and see if the Windows paths is the problem as mentioned by @chuckjaz 

Out of interest @ryanbuening , what's the process for reverting an extension? I'm guessing it's not supported by VSCode out of the box

**Comment by rfuhrer** [comment] 2018-01-26 17:46
@briancodes revert, bang out #223 in 5 minutes and call it 0.1.9 😄. This extension should just be made version 1.0 it's so damn useful and the "experimental" tag might scare some more conservative users. 🎉 

I'm sure it's just a stupid / vs \ error or something equally annoying thanks to windows amazing pathing

**Comment by chuckjaz** [comment] 2018-01-26 17:46
@briancodes I reproduced this in Windows. Investigating now.

**Comment by ryanbuening** [comment] 2018-01-26 19:19
> Out of interest @ryanbuening , what's the process for reverting an extension? I'm guessing it's not supported by VSCode out of the box

@briancodes You need to Disable Auto Updating Extensions and then select Install from VSIX...

![image](https://user-images.githubusercontent.com/812974/35456563-f1eea594-02a3-11e8-95d5-4d3ca204ceaf.png)

**Comment by chuckjaz** [comment] 2018-01-26 20:04
It is a path issue and an apparent change in TypeScirpt I was unaware of.

We pass the result of `path.join()` directly to TypeScript when initializing the compiler we should be calling `path.posix.join()`.

A temporary work around is to change the line:

```js
containingFile = path.join(this.options.basePath, 'index.ts');
```

to:

```js
containingFile = path.posix.join(this.options.basePath, 'index.ts');
```

in the file `language-service.umd.js` in the `@angular/language-service` package.

I will make this change in `@angular/language-service` and update the extension.

**Comment by chuckjaz** [comment] 2018-01-27 00:29
@briancodes @jontiefer @ryanbuening Can one of you (or anyone else on the thread) test https://github.com/angular/vscode-ng-language-service/releases/tag/0.1.9 on Windows using your projects?

I believe this fixes the Windows issue as described above.

**Comment by rfuhrer** [comment] 2018-01-27 00:38
@chuckjaz Great Success!
![image](https://user-images.githubusercontent.com/2529744/35466297-c1b9d9c2-02bf-11e8-8148-90cb5b7114bf.png)

**Comment by chuckjaz** [comment] 2018-01-27 00:42
@rfuhrer Thanks!

**Comment by briancodes** [comment] 2018-01-27 10:31
@chuckjaz I didn't realised how much I used this language extension was until it stopped working! Great job

**Comment by m-ghaoui** [comment] 2018-01-27 11:08
Good stuff! Lesson learned: Next time I'll mention I'm on Windows when making a comment.

**Comment by michaeljmonte** [comment] 2018-02-10 19:47
Having this same problem again. 
Platform: Windows
`PS C:\Dev\Programming\Ang5Tutorial\angular-tour-of-heroes> npm list @angular/language-service
angular-tour-of-heroes@0.0.0 C:\Dev\Programming\Ang5Tutorial\angular-tour-of-heroes
`-- @angular/language-service@5.2.4

PS C:\Dev\Programming\Ang5Tutorial\angular-tour-of-heroes> npm list typescript
angular-tour-of-heroes@0.0.0 C:\Dev\Programming\Ang5Tutorial\angular-tour-of-heroes
+-- @angular/cli@1.6.8
| +-- @angular-devkit/build-optimizer@0.0.42
| | `-- typescript@2.6.2
| `-- @schematics/angular@0.1.17
|   `-- typescript@2.6.2
`-- typescript@2.6.2

PS C:\Dev\Programming\Ang5Tutorial\angular-tour-of-heroes>`

Maybe I goofed?

**Comment by cvgaviao** [comment] 2018-02-21 00:03
Maybe I didn't understand how this plugin should be used. 
But I just saw in the Contributions tab that the File Extensions for an 'Angular Template' are **.ng**, **.ngml** and **.ng.html**.  
When I changed the extension of my template file from .html to .ng.html, the language have changed to AngularTemplate and I started to receive values in the intelisense that I was not receiving before. for example: *ngIf, *ngFor and the component properties.
But I loose the tag colors.

**Comment by Hotell** [comment] 2018-03-26 12:56
It works now. Just make sure you have no TypeScript errors which was issue in my usecase 

https://github.com/Hotell/react-tools-for-better-angular-apps/pull/2

can this be closed @chuckjaz  ?

thanks!

**Comment by Inori-Lover** [comment] 2018-06-25 03:03
@michaeljmonte i run `npm uninstall -D typescript @angular/language-service` and the plugin work fine again.

**Comment by Inori-Lover** [comment] 2018-06-25 03:15
@michaeljmonte after change typescript version same as vscode's; or[ change "typescript.tsdk" to "./node_modules/typescript/lib"](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions), the plugin work again; hope it can help you

**Comment by Borongaj** [comment] 2018-08-06 14:41
Still not work on Mac since Angular 6...

**Comment by thovo** [comment] 2018-10-03 16:13
I tried to install the extension manually but it didn't work with my project now:
Angular 6 and Typescript 2.7.2

Is there any work around this issue because I need this work like before ?

**Comment by bouillonpi** [comment] 2018-10-11 18:40
Same here, the completion does not work on vscode for a `ng new app`.
- Angular 6.1.9
- Typescript 2.7.2

**Comment by WESquad-spires** [comment] 2018-10-16 08:28
Same, not working.

- Ubuntu 18.04 (x64)
- Angular CLI: 6.1.5
- Node: 10.6.0
- Typescript 2.9.2

**Comment by coffeymatt** [comment] 2018-11-12 11:51
Not working for me in HTML files at all, no completion, no go-to

- Angular 7.0.3
- Typescript 3.1.6
- VS Code extension: 0.1.10

**Comment by chenxxzhe** [comment] 2019-03-26 02:39
I had this problem too, but finally I found that I set wrong syntax in `.html` file (I had set wxml).
so I changed the syntax, and it work.

**Comment by JiaHongL** [comment] 2019-09-08 02:44
ry it, may be solved

VSCode - User Settings

"editor.snippetSuggestions": "top",

to

"editor.snippetSuggestions": "inline",

**Comment by kyliau** [comment] 2019-11-23 00:51
Closing this, since issue was solved in https://github.com/angular/vscode-ng-language-service/issues/217#issuecomment-360890538

**Closed by kyliau** 2019-11-23 00:51 UTC
Labels: bug
