### ISSUE TITLE
String literals throws errors

### ISSUE THREAD

**Issue by Dovernh** [angular/vscode-ng-language-service#334] opened 2019-05-29 15:04 UTC
This issue is re-occurring again. I see it was reported Dec 12, 2016

class FooCmp {
  something: 'foo' | 'bar';
}
<div *ngIf="something === 'foo'"></div>
throws

'Expected the operants to be of similar type or any'

**Comment by sbreakey** [comment] 2019-07-05 07:17
Duplicate of https://github.com/angular/vscode-ng-language-service/issues/231?

**Comment by Alek-S** [comment] 2019-08-02 19:54
@sbreakey this is slightly different to issue referenced (231). That issue is related to union types of string or a number, this is an issue specific to string literal types of possible string values.

**Comment by kyliau** [comment] 2019-08-17 17:18
There's already an existing test for this: https://github.com/angular/angular/blob/5f76de1d71ac40654b5eef2d58747a713aab5c06/packages/language-service/test/diagnostics_spec.ts#L195-L210
Could you please provide an example of your code?

**Comment by kyliau** [comment] 2019-08-29 20:17
Closing this for now since there's already a fix. Please open a new issue if problem persists. Thanks!

**Closed by kyliau** 2019-08-29 20:17 UTC
Labels: needs repro
