### ISSUE TITLE
Unable to rename & delete folder

### ISSUE THREAD

**Issue by jaytonic** [angular/vscode-ng-language-service#1445] opened 2021-07-12 17:18 UTC
Issue Type: <b>Bug</b>

Open an angular solution
rename/delete a folder
a tooltip with an error indicates the file is in use.

Extension version: 12.1.1
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz (20 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (17.40GB free)|
|Process Argv|--crash-reporter-id 9e3fb019-9ddb-490d-8312-a993519df887|
|Screen Reader|no|
|VM|80%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30322571
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805cf:30301675
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by atscott** [comment] 2021-07-12 17:29
Duplicate of #1398

**Closed by atscott** 2021-07-12 17:29 UTC
