### ISSUE TITLE
VS Code Slow and using a Ton of CPU

### ISSUE THREAD

**Issue by josephhelmrich** [angular/vscode-ng-language-service#1841] opened 2022-12-20 19:22 UTC
Type: <b>Performance Issue</b>

My VS Code is using a lot of CPU and running very slow.  I disabled the Angular Language Services and the issue goes away.  I have had this extension running for years without any problems.  It just started happening around December 15th-16th

Extension version: 15.0.3
VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.91GB (17.79GB free)|
|Process Argv|--folder-uri file:///d%3A/Git/Cdw.WebUi.PricingAdmin --crash-reporter-id 1ea037e2-9b65-412e-862d-84fd2791b9b6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   108	 42792	code main
    0	   252	  2528	   window (Running Extensions - Cdw.WebUi.PricingAdmin - Visual Studio Code)
    0	    42	 12640	   utility-network-service
    0	   115	 13808	   shared-process
    0	    81	 24844	     ptyHost
    0	     5	 20224	       C:\Windows\System32\cmd.exe
    0	     7	 25360	       console-window-host (Windows internal process)
    0	    87	 34492	     fileWatcher
    0	    94	 18644	   issue-reporter
    0	    25	 20816	   crashpad-handler
    0	   101	 22308	   gpu-process
    0	   153	 42700	   extensionHost
    9	   611	  9960	     "D:\Program Files\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "d:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName C:\Users\JOEHEL\AppData\Local\Temp\vscode-typescript\d2c9ac95a338835d8e33\tscancellation-fb22a940635bf3fcb8cb.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
    0	   102	 22012	       "D:\Program Files\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "d:/Program Files/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js" --globalTypingsCacheLocation C:/Users/JOEHEL/AppData/Local/Microsoft/TypeScript/4.9 --enableTelemetry --typesMapLocation "d:/Program Files/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/typesMap.json" --validateDefaultNpmLocation
    0	   127	 27892	     "D:\Program Files\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "d:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName C:\Users\JOEHEL\AppData\Local\Temp\vscode-typescript\d2c9ac95a338835d8e33\tscancellation-2090128563d2a32481bb.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
    9	   592	 31716	     "D:\Program Files\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\JOEHEL\.vscode\extensions\angular.ng-template-15.0.3\server --logToConsole --ngProbeLocations c:\Users\JOEHEL\.vscode\extensions\angular.ng-template-15.0.3,d:\Git\Cdw.WebUi.PricingAdmin --includeAutomaticOptionalChainCompletions --includeCompletionsWithSnippetText --tsProbeLocations ,c:\Users\JOEHEL\.vscode\extensions\angular.ng-template-15.0.3,d:\Git\Cdw.WebUi.PricingAdmin --node-ipc --clientProcessId=42700
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Running Extensions - Cdw.WebUi.PricingAdmin - Visual Studio Code)
|    Folder (Cdw.WebUi.PricingAdmin): 7396 files
|      File types: json(5361) dll(973) pack(159) svg(97) html(91) ts(81)
|                  cs(70) cache(51) scss(42) pdb(35)
|      Conf files: csproj(7) settings.json(1) sln(1) package.json(1)
|                  tsconfig.json(1);
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by atscott** [comment] 2022-12-20 19:26
Closing as duplicate of #1840.  Are you able to pinpoint the issue to a particular version rather than a date?

**Closed by atscott** 2022-12-20 19:26 UTC
