### ISSUE TITLE
VE language service restarting nonstop when running ng serve

### ISSUE THREAD

**Issue by vaindil** [angular/vscode-ng-language-service#1132] opened 2021-02-19 16:06 UTC
**Describe the bug**

I reverted back to the VE language service because the Ivy one crashes quite frequently, but now on 11.2.2 the VE language service restarts basically nonstop when running `ng serve`. It restarts for no reason somewhat frequently when not running `ng serve` (which never/very rarely happened before 11.2.0), but now it's happening constantly with `ng serve`.

**To Reproduce**

I don't have a definitive reproduction, but running `ng serve` on a project seems to trigger it.

**Expected behavior**

The language service shouldn't restart all the time.

**Logs**

All that's in my output is below. I'm happy to share the log file as well, but there's way too much to censor from it so I would need to share it privately.

```
[Info  - 10:41:22 AM] Angular language server process ID: 5048
[Info  - 10:41:22 AM] Using typescript/lib/tsserverlibrary v4.1.5 from c:\Repos\<snip>\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 10:41:22 AM] Using @angular/language-service v11.2.1 from c:\Users\<snip>\.vscode-insiders\extensions\angular.ng-template-11.2.2\node_modules\@angular\language-service\bundles\language-service.js
[Info  - 10:41:22 AM] Log file: c:\Users\<snip>\AppData\Roaming\Code - Insiders\logs\20210219T093903\exthost1\Angular.ng-template\nglangsvc.log

<some lines trimmed, all the same as below but with different timestamps>

[Info  - 10:58:15 AM] Enabling VE language service for c:/Repos/<snip>/tsconfig.json.
[Info  - 10:58:18 AM] Enabling VE language service for c:/Repos/<snip>/tsconfig.json.
[Info  - 10:58:23 AM] Enabling VE language service for c:/Repos/<snip>/tsconfig.json.
[Info  - 10:58:35 AM] Enabling VE language service for c:/Repos/<snip>/tsconfig.json.
[Info  - 10:58:43 AM] Enabling VE language service for c:/Repos/<snip>/tsconfig.json.
[Info  - 10:58:58 AM] Enabling VE language service for c:/Repos/<snip>/tsconfig.json.
```

**Screenshots**

N/A

**Additional context**

I believe this started with 11.2.0.

**Comment by kyliau** [comment] 2021-03-02 18:51
@vaindil it looks like you are using vscode insider. Does the same behavior occur when you switch to the stable build?
Please send us the log file: c:\Users\<snip>\AppData\Roaming\Code - Insiders\logs\20210219T093903\exthost1\Angular.ng-template\nglangsvc.log
Without the logs, it is hard for us to debug. I tried to run `ng serve` in a new project, but I could not reproduce the bug. It looks like some background process might be updating node_modules which triggers project reload.

**Comment by vaindil** [comment] 2021-03-02 18:53
I'm happy to send the log file, but it's too much for me to censor. Do you have somewhere I can share it privately?

**Comment by kyliau** [comment] 2021-03-02 19:23
@vaindil You can send it to kyliau@angular.io thank you very much!

**Comment by kyliau** [comment] 2021-03-02 20:23
@vaindil Thanks for the log file! It looks like some process is editing your `tsconfig.json`, which triggers a project reload via the file watcher. I don't see any changes before and after though. 
I see six log lines similar to the following:
```
Info 271  [12:14:5.507] Loading new project: Change in config file detected
Info 7560 [13:50:45.275] Loading new project: Change in config file detected
Info 9225 [14:29:11.727] Loading new project: Change in config file detected
Info 14521[15:0:36.205] Loading new project: Change in config file detected
Info 18080[16:8:39.941] Loading new project: Change in config file detected
Info 22825[17:12:37.211] Loading new project: Change in config file detected
```

I don't think this is caused by `ng serve`. In order to eliminate it as a potential cause, could you please open the project in vscode without running `ng serve` and check if you still see the log lines above?

**Comment by vaindil** [comment] 2021-03-09 16:10
I haven't been able to reproduce this again, it was happening all the time and it seems to have stopped now. I do occasionally see it even with the Ivy language service, but I'll try to see what's editing the file and report back. You can probably close this card if you want. Thank you, and sorry!

**Comment by atscott** [comment] 2021-03-23 22:05
@vaindil - Thanks for the info. Let's close this for now, but please feel free to open a new ticket if something new comes up.

**Closed by atscott** 2021-03-23 22:05 UTC
Labels: bug, view engine
