### ISSUE TITLE
VSCode: How to stop the output window from showing itself during an Angular build?

### ISSUE THREAD

**Issue by linocatucci** [angular/vscode-ng-language-service#170] opened 2017-09-16 07:49 UTC
I have VSCode, latest version. And I don't want to see the output window when compiling my angular application.

Does anybody know how to disable the auto pop up of the output window?

**Comment by matthewmeyer** [comment] 2017-11-17 23:26
Part of the problem is that the plugin is not watching the files that are included in the tsconfig.json project definition. Instead it is watching all files recursively under the directory where is locates tsconfig.json file. This probably includes your output folder which causes the plugin to detect file changes like mad. 

If you are able you might relocate your tsconfig file into your src folder and see if that helps.

**Comment by snewell92** [comment] 2017-11-20 18:23
Possibly related to #187 ?

**Comment by dgrahn** [comment] 2017-12-12 13:45
Any progress on this?

**Comment by chuckjaz** [comment] 2017-12-30 17:49
This was fixed in #195. It will be in the next release of the plugin

**Closed by chuckjaz** 2017-12-30 17:49 UTC
