### ISSUE TITLE
SERVER ERROR: Cannot read property 'lineNumberToInfo' of undefined

### ISSUE THREAD

**Issue by fvilers** [angular/vscode-ng-language-service#218] opened 2018-01-22 12:34 UTC
Hi, here's an error I encounter regularly. Here's the stack trace:

```
[Error - 13:31:31] SERVER ERROR: Cannot read property 'lineNumberToInfo' of undefined
TypeError: Cannot read property 'lineNumberToInfo' of undefined
    at LSHost.lineOffsetToPosition (C:\Users\Fabian\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:659:29)
    at C:\Users\Fabian\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:1448:86
    at Array.map (native)
    at ProjectService.lineOffsetsToPositions (C:\Users\Fabian\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:1448:30)
    at TextDocuments.getServiceInfo (C:\Users\Fabian\.vscode\extensions\Angular.ng-template-0.1.7\server\documents.js:216:54)
    at C:\Users\Fabian\.vscode\extensions\Angular.ng-template-0.1.7\server\server.js:169:24
    at logErrors (C:\Users\Fabian\.vscode\extensions\Angular.ng-template-0.1.7\server\server.js:139:16)
    at C:\Users\Fabian\.vscode\extensions\Angular.ng-template-0.1.7\server\server.js:168:61
    at handleRequest (C:\Users\Fabian\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\vscode-jsonrpc\lib\main.js:237:37)
    at process.callback (C:\Users\Fabian\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\vscode-jsonrpc\lib\main.js:483:13)
[Error - 13:31:31] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'lineNumberToInfo' of undefined
  Code: -32603 
```

What can I do to fix it?

Thanks for your help!

**Comment by chuckjaz** [comment] 2018-01-23 23:31
@fvilers Do you have (or can you produce) a project that I can clone that reproduces this?

**Comment by fvilers** [comment] 2018-01-25 09:05
Hi @chuckjaz, I'm sorry but I can't share the project I'm working on. The errors happen randomly, but it seems that they are more frequent after several branch changes (git).

**Comment by kyliau** [comment] 2019-11-11 23:52
Closing this, since this has been fixed. Please open a new issue otherwise. Thank you!

**Closed by kyliau** 2019-11-11 23:52 UTC
Labels: bug, needs repro
