### ISSUE TITLE
HTML referencing fails after version 14.0.0 of the extension

### ISSUE THREAD

**Issue by ZioCain** [angular/vscode-ng-language-service#1772] opened 2022-10-06 09:43 UTC
# 🐞 bug report

### Is this a regression?

I'm currently using version 14.0.0 to make this work properly

### Description

I'm using a codebase that has Angular 5 an another codebase with Angular10.2, either way, any variable in the HTML template of any given component (doesn't matter if that's an actual component or a page) won't be checked by the plugin.
Meaning that while in the 14.0.0 version a non-existing class property will be marked as non-existent, the above version won't even check it; furthermore, trying to "Go to Definition" will only work with v14.0.0, while newer version will just state "Cannot find any reference" or something like that.

You can most likely try this with a very sample code:
HTML
```
<div *ngIf="show">
Show me
</div>
```
TS:
```
@Component({
  selector: "app-mycomponent",
  templateUrl: "mycomponent.html"
})
export class MyComponent{
constructor(){}
}
```
As you can see the `show` properties doesn't even exist, but this plugin won't say a word about it in newer versions.

## Bug Type
What does this bug affect

- [X] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

1. Have an HTML template with some properties in it (like in`*ngIf` or `{{}}` or property-bindings)
2. Select given variable and right-click it, then "Go to definition"
3. Nothing found (even if it exists)

**Expected behavior**
Going to its definition if it exists

## 🌍  Your Environment
**Angular Version:**
<pre><code>

Angular CLI: 13.2.5
Node: 16.10.0
Package Manager: npm 7.24.0
OS: darwin x64

Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1302.5 (cli-only)
@angular-devkit/core         13.2.5 (cli-only)
@angular-devkit/schematics   13.2.5 (cli-only)
@schematics/angular          13.2.5 (cli-only)
rxjs                         5.5.12
typescript                   2.8.4
</code></pre>
Also happens with other project:
<pre><code>
Angular CLI: 12.1.4
Node: 16.10.0 (Unsupported)
Package Manager: npm 7.24.0
OS: darwin x64

Angular: 12.1.5
... common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.4 (cli-only)
@angular-devkit/build-angular   12.1.4
@angular-devkit/core            12.0.5
@angular-devkit/schematics      13.3.5
@angular/cli                    12.1.4
@angular/language-service       12.0.5
@schematics/angular             12.1.4
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

Extension Version:
<pre><code>

Happens with version higher than 14.0.0
</code></pre>

VSCode Version:
<pre><code>

1.71.2 (latest)
</code></pre>

Operating System:
<pre><code>

Mac OSX v12.6
</code></pre>

Extension options:
<pre><code>
// no specific config, default settings are set
</code></pre>

**Anything else relevant?**

I also have installed (always have been):
- Mikael.Angular-BeastCode
- cyrilletuzi.angular-schematics
- johnpapa.Angular2

**Comment by atscott** [comment] 2022-10-06 10:09
Duplicate of #1753
https://github.com/angular/vscode-ng-language-service/issues/1753#issuecomment-1252471732

**Closed by atscott** 2022-10-06 10:09 UTC
Labels: bug
