### ISSUE TITLE
Bug with syntax highlighting in v0.900.6 and higher when using type assertion

### ISSUE THREAD

**Issue by carboneum87** [angular/vscode-ng-language-service#629] opened 2020-02-12 12:30 UTC
I have noticed that there is a bug in syntax highlighting when you use a template reference variable inside a structural directive with type assertion.

1. Install vscode-ng-language-service v0.900.6 or higher
2. Change the color theme of vscode to 'Dark+ (default dark)'
3. Use a structural directive and type assertion, e.g. some `condition as con`
4. Write a template reference variable inside the element with the structural directive
5. See error

Expected behavior:
Syntax highlighting should not mark the part with template reference variable in red

Screenshots:

- Syntax highlighting with v0.900.6:
![image](https://user-images.githubusercontent.com/34030404/74335121-c0509e80-4d9b-11ea-972e-f03e00c087fe.png)

- Syntax highlighting with v0.900.5:
![image](https://user-images.githubusercontent.com/34030404/74335165-e0805d80-4d9b-11ea-92cc-19ef085e760a.png)

**Comment by ayazhafiz** [comment] 2020-02-12 15:24
Dupe of #575

**Closed by ayazhafiz** 2020-02-12 15:24 UTC
Labels: bug
