### ISSUE TITLE
Go To Definition not working in template on component tags with a directive

### ISSUE THREAD

**Issue by suisoku** [angular/vscode-ng-language-service#1219] opened 2021-03-20 19:43 UTC
Hello, I reopened the issue because I am still struggling with this bug, this time with more details and reproducibility :

Describe the bug

Go To Definition not working in template on component tags with the directive *ngfor (or any other directives in VSCode using the latest ALS vs code extension

To Reproduce

Using the latest environment:

- Angular CLI: 11.2.5
- Node: 15.11.0
- OS: linux x64 (through WSL)
- Angular: 11.2.6 / Ivy Workspace: Yes
- Latest  VS Code ALS version v11.2.8

1. run command ng new test
2. generate a test component and use the selector name in app.component.ts

This is what I have if I hover to show the declaration without adding a directive
![image](https://user-images.githubusercontent.com/35864417/111883441-a9777500-89bb-11eb-8880-879e78bd3abf.png)

F12 on <component-name *ngFor=".."> in VSCode I have "No definition found for component-name"
![image](https://user-images.githubusercontent.com/35864417/111883424-7f25b780-89bb-11eb-9e8b-bdbb5bea7790.png)

Expected behavior

It should get me to the definition of the component

ALS Log output:

[Info  - 6:56:24 PM] Angular language server process ID: 3381
[Info  - 6:56:24 PM] Using typescript/lib/tsserverlibrary v4.1.5 from /home/noureddine/.vscode-server/extensions/angular.ng-template-11.2.8/node_modules/typescript/lib/tsserverlibrary.js
[Info  - 6:56:24 PM] Using @angular/language-service/bundles/ivy v11.2.5 from /home/noureddine/.vscode-server/extensions/angular.ng-template-11.2.8/node_modules/@angular/language-service/bundles/ivy.js
[Info  - 6:56:24 PM] Log file: /home/noureddine/.vscode-server/data/logs/20210320T184454/exthost2/Angular.ng-template/nglangsvc.log
[Error - 6:56:30 PM] No config file for /home/noureddine/NodeFeed/client/src/app/core/components/page-header/page-header.component.html
[Error - 6:56:34 PM] No config file for /home/noureddine/NodeFeed/client/src/app/core/components/page-header/page-header.component.html
[Info  - 6:56:36 PM] Enabling Ivy language service for /home/noureddine/NodeFeed/client/tsconfig.json.

Additional context
I have tried in 2 different projects with the same issue, I tried to disable other potential interfering extensions without result either.
When I roll back to an earlier version done 6 months ago (v0.1000.8) the issue disappears
Edit: **By pure desperation I created another project with strict mode On and oddly enough it solved the issue :D**
So I moved forward and changed the settings manually to make it strict on my main project and solved the problem too, so i'm not sure If this issue should remain open or the bug on strict mode Off should be dealt with

**Comment by ganshiqingyuan** [comment] 2021-03-22 06:20
i have the same problem

**Comment by atscott** [comment] 2021-03-22 15:37
I believe we will likely close this as working as intended. It sounds like an issue with the options you've set for `angularCompilerOptions`. Unlike the old version of the language service, we aim to provide the exact information used when your program compiles. This means that if you tell the compiler to ignore template bodies, you do not get information or diagnostics in the language service inside template bodies.

Could you provide the contents of your `tsconfig`'s `angularCompilerOptions`? This information would also be provided in the server logs (run the command "Open Angular Server log" and search for "Angular compiler options").

**Comment by suisoku** [comment] 2021-03-22 19:52
While executing the command `ng new testproject` the CLI asks you if you want strict mode applied to your project. I didn't set manually any option in tsconfig or angular.json and still didn't work, but here is the difference between the 2 modes (see comments with // strict mode:

```
/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true, //strict mode 
    "strict": true, //strict mode 
    "noImplicitReturns": true, //strict mode 
    "noFallthroughCasesInSwitch": true, //strict mode 
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true, //strict mode 
    "strictInputAccessModifiers": true, //strict mode 
    "strictTemplates": true //strict mode 
  }
}
```
Unless Angular plans to remove the option to select strict mode off, I believe ALS should work out of the box with Angular CLI

**Comment by atscott** [comment] 2021-03-22 20:04
@suisoku Thanks for the additional context. Angular CLI is making `strictTemplates` the default in v12; this is also when the "experimental Ivy" LS will become the default. Closing as this is working as expected.

**Closed by atscott** 2021-03-22 20:04 UTC
Labels: discussion, needs clarification
