### ISSUE TITLE
Gray out protected component methods and properties that are not used

### ISSUE THREAD

**Issue by snebjorn** [angular/vscode-ng-language-service#1877] opened 2023-03-09 20:49 UTC
# 🚀 feature request

### Description
Angular 14 introduced the ability to make methods and properties `protected` and the template would still have access to them. This is great.
It would be even better if the methods and properties that are not being used would be grayed out. Like other unused code bits.

### Feature Type

- [x] Angular Language Service VSCode extension
- [x] Angular Language Service server

### Describe the solution you'd like
When a component method/property is made `protected` and it's not being used then it should be grayed out.

### Describe alternatives you've considered

None

### Anything else relevant?

Components can be derived from so it might be a bit tricky. But maybe it's possible to check if a component is being derived from and make a decision based on that.

**Comment by atscott** [comment] 2023-03-09 20:52
Marking this as a general duplicate of https://github.com/angular/vscode-ng-language-service/issues/162. Knowing that there are 0 references would be required to do this at all and generally accomplishes the same thing. Rather than color, the visual representation of something being unused would be the codelens.

**Closed by atscott** 2023-03-09 20:52 UTC
Labels: feature
