### ISSUE TITLE
bug: expected the operants to be of similar type or any

### ISSUE THREAD

**Issue by dylanvdmerwe** [angular/vscode-ng-language-service#465] opened 2019-11-27 09:26 UTC
**Describe the bug**

When you have an `ngFor` that contains a `let i = index`, using the `i` variable later in the template is highlighted as an error.

For example:
![image](https://user-images.githubusercontent.com/2852839/69710273-c96c9080-1107-11ea-9c9a-66a923b4bf49.png)

"Expected the operants to be of similar type or any" if the error that is shown.

![image](https://user-images.githubusercontent.com/2852839/69710875-d0e06980-1108-11ea-8866-77712342bb20.png)

This was not an error before 0.900.0.

**Expected behavior**

The underlined error is not valid as angular (even `--prod`) builds and runs correctly.

**Comment by ayazhafiz** [comment] 2019-11-27 15:34
Duplicate of #460. Tracking there.

**Closed by ayazhafiz** 2019-11-27 15:34 UTC
Labels: bug
