### ISSUE TITLE
ctrl + click in the template is not working.

### ISSUE THREAD

**Issue by sanket-bhalerao** [angular/vscode-ng-language-service#1064] opened 2021-01-15 08:33 UTC
Issue Type: <b>Bug</b>

ctrl + click in the template is not working.
angular version: 8.x
extension version: 0.1100.3

Extension version: 0.1100.3
VS Code version: Code - Insiders 1.53.0-insider (1a6eef3170be2a11751ee50d450328d458f7bfac, 2021-01-15T05:15:40.826Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (4.57GB free)|
|Process Argv|--crash-reporter-id 340e0eb9-5b34-4206-9e2e-bd86fc3b2cf3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
wsl2promptcf:30219163
vstry244:30244315
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorercf:30219167
openfilemenucf:30219169
pythonvsded773:30223139
pythonvspyt600cf:30241728
core-portspanelcf:30233468

```

</details>

**Comment by keatkeat87** [comment] 2021-01-15 10:20
same problem here, after update to latest v0.1100.3.

**Comment by sanket-bhalerao** [comment] 2021-01-15 10:32
I downgraded to `v0.1100.2`, it's working fine with `v0.1100.2`.

**Comment by bubliq** [comment] 2021-01-15 12:58
[Duplicate?](https://github.com/angular/vscode-ng-language-service/issues/1063)

**Comment by kyliau** [comment] 2021-01-15 21:41
Duplicate of #1063

**Closed by kyliau** 2021-01-15 21:41 UTC
