### ISSUE TITLE
Two Extensions In VS Code Marketplace

### ISSUE THREAD

**Issue by Meligy** [angular/vscode-ng-language-service#159] opened 2017-08-31 01:53 UTC
As mentioned in https://github.com/angular/vscode-ng-language-service/issues/142#issuecomment-326166288

![image](https://user-images.githubusercontent.com/171637/29902508-fb169112-8e41-11e7-95d0-162c14da24c2.png)

It seems that version 0.1.6 is showing as a totally different extension in the marketplace.

So now this leaves you with 2 extensions, and the one that shows first and has most downloads / stars, is the one with an old version, 0.1.4.

**Comment by chuckjaz** [comment] 2017-08-31 02:21
This is a duplicate of #157

**Closed by chuckjaz** 2017-08-31 02:21 UTC
Labels: duplicate
