### ISSUE TITLE
SERVER ERROR: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by SpiraMira** [angular/vscode-ng-language-service#124] opened 2017-07-03 18:59 UTC
Hi - I get the error below consistently from the language server after hovering over certain tags in this html:

> <div id="grid-container">
    <dx-button id="gridDeleteSelected"
        text="Clear Selected Certifications"
        [height]="34"
        [width]="195"
        [disabled]="!selectedItems.length"
        (onClick)="deleteRecords()">
    </dx-button>
    <dx-data-grid 
        id="gridContainer"
        [dataSource]="dataSource"
        (onContentReady)="onContentReady($event)"
        (onCellPrepared)="onCellPrepared($event)"      
        (onSelectionChanged)="selectionChanged($event)"
        (onToolbarPreparing)="onToolbarPreparing($event)">    
        <dxo-paging [enabled]="true"></dxo-paging>
        <dxo-editing 
            mode="form"
            [allowUpdating]="true"
            [allowAdding]="true"
            [allowDeleting]="true">
        </dxo-editing>

These are devextreme-angular widget tags. Hover issues arise with the option tags dxo-...
Using latest and greatest vs code 1.13.1 + extensions (especially essentials(papa) , angular2-inline)
I'm pretty sure these errors starting popping up after my upgrade to 1.13.1.

Any help is  appreciated...

Regards

**ERROR**:

> [Error - 2:42:48 PM] SERVER ERROR: Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at SymbolWrapper.get [as name] (/Users/me/.vscode/extensions/Angular.ng-template-0.1.4/server/node_modules/@angular/language-service/bundles/language-service.umd.js:48080:46)
    at OverrideKindSymbol.get [as name] (/Users/me/.vscode/extensions/Angular.ng-template-0.1.4/server/node_modules/@angular/language-service/bundles/language-service.umd.js:50434:43)
    at hoverTextOf (/Users/me/.vscode/extensions/Angular.ng-template-0.1.4/server/node_modules/@angular/language-service/bundles/language-service.umd.js:50595:71)
    at getHover (/Users/me/.vscode/extensions/Angular.ng-template-0.1.4/server/node_modules/@angular/language-service/bundles/language-service.umd.js:50591:24)
    at LanguageServiceImpl.getHoverAt (/Users/me/.vscode/extensions/Angular.ng-template-0.1.4/server/node_modules/@angular/language-service/bundles/language-service.umd.js:50662:20)
    at /Users/me/.vscode/extensions/Angular.ng-template-0.1.4/server/editorServices.js:2705:68
    at time (/Users/me/.vscode/extensions/Angular.ng-template-0.1.4/server/editorServices.js:2687:22)
    at Object.getHoverAt (/Users/me/.vscode/extensions/Angular.ng-template-0.1.4/server/editorServices.js:2705:20)
    at /Users/me/.vscode/extensions/Angular.ng-template-0.1.4/server/server.js:171:30
    at logErrors (/Users/me/.vscode/extensions/Angular.ng-template-0.1.4/server/server.js:139:16)
[Error - 2:42:48 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'name' of undefined
  Code: -32603 
[Error - 2:42:49 PM] SERVER ERROR: Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at SymbolWrapper.get [as name] (/Users/me/.vscode/extensions/Angular.ng-template-0.1.4/server/node_modules/@angular/language-service/bundles/language-service.umd.js:48080:46)
    at OverrideKindSymbol.get [as name] (/Users/me/.vscode/extensions/Angular.ng-template-0.1.4/server/node_modules/@angular/language-service/bundles/language-service.umd.js:50434:43)
    at hoverTextOf (/Users/me/.vscode/extensions/Angular.ng-template-0.1.4/server/node_modules/@angular/language-service/bundles/language-service.umd.js:50595:71)
    at getHover (/Users/me/.vscode/extensions/Angular.ng-template-0.1.4/server/node_modules/@angular/language-service/bundles/language-service.umd.js:50591:24)
    at LanguageServiceImpl.getHoverAt (/Users/me/.vscode/extensions/Angular.ng-template-0.1.4/server/node_modules/@angular/language-service/bundles/language-service.umd.js:50662:20)
    at /Users/me/.vscode/extensions/Angular.ng-template-0.1.4/server/editorServices.js:2705:68
    at time (/Users/me/.vscode/extensions/Angular.ng-template-0.1.4/server/editorServices.js:2687:22)
    at Object.getHoverAt (/Users/me/.vscode/extensions/Angular.ng-template-0.1.4/server/editorServices.js:2705:20)
    at /Users/me/.vscode/extensions/Angular.ng-template-0.1.4/server/server.js:171:30
    at logErrors (/Users/me/.vscode/extensions/Angular.ng-template-0.1.4/server/server.js:139:16)
[Error - 2:42:49 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'name' of undefined
  Code: -32603

**Comment by chuckjaz** [comment] 2017-07-06 18:18
This is a duplicate of #119

**Closed by chuckjaz** 2017-07-06 18:18 UTC
Labels: duplicate
