### ISSUE TITLE
Ivy LS: duplicate results for autocomplete, quick info, etc outside of templates

### ISSUE THREAD

**Issue by Memeplexx** [angular/vscode-ng-language-service#1110] opened 2021-02-15 19:39 UTC
**Describe the bug**

The latest version, v11.2.0, seems to have added 2 regression bugs:
1) One that prevents autocompletion of class variables in templates
2) Another which causes duplicate auto-complete options outside templates
I'm including both bug reports here as I feel they may be related.

**To Reproduce**

1. Upgrade to the latest version of Angular-CLI
2. Create a new project

Bug 1:
1. Go to app.component.html
2. Remove all HTML
3. attempt to get the language service to autocomplete options for class members (eg try to get it to detect `title`)
![image](https://user-images.githubusercontent.com/17923511/107986488-d27ba300-6fd4-11eb-8ce7-9a4bd798b580.png)

Bug 2:
1. Wait for up to 1 minute
2. Anywhere in the project, for example, the `app.module.ts`, press ctrl+space
3. Note that all auto-completed options have been duplicated
![image](https://user-images.githubusercontent.com/17923511/107985950-c8a57000-6fd3-11eb-8372-e9aef189a4d7.png)

**Expected behavior**

1. I expect to get autocompletion in the template (as seen in bug 1)
2. I expect not to see duplicate autocomplete options outside of templates (as seen in bug 2)

**Logs**

Please attach two logs:

1. Console output (Go to toolbar --> View --> Output, and copy the contents)
- Nothing showing 
2. Log file (Path is printed to the console output at startup)
- Not sure what this means, sorry

**Additional context**

I'm using Windows 10
Angular CLI version 11.2.0
I tried to reproduce this in another window (in a React project) and could not do so
If I downgrade to 11.1.3 things all work as expected

**Comment by ivanwonder** [comment] 2021-02-16 05:32
duplicate #1109

**Comment by atscott** [comment] 2021-02-16 20:21
The cause of this is indeed a duplicate of #1109, but I'm also leaving this one open because we can address the duplicate results issue by adding a safeguard when our language service plugin fails to register.

**Closed** 2021-02-17 19:06 UTC
Labels: bug
