### ISSUE TITLE
auto import Module or another standalone Component in template like WebStorm for VS CODE (The most popular and best text editor)

### ISSUE THREAD

**Issue by tu-hai** [angular/vscode-ng-language-service#1774] opened 2022-10-07 02:25 UTC
![good job](https://user-images.githubusercontent.com/37888689/194453352-ff2183d1-9cdc-44ff-9971-574d5fc2985e.jpg)
**Is your feature request related to a problem? Please describe.**

# 🚀 feature request

### Description
 A clear and concise description of the problem or missing capability...
Angular 14 version with standalone on VS code does not automatically import other standalone components or modules in .html file for example: automatically Or suggests to import MatCardModule in
https://github.com/component if HTML has tag </mat -card>
### Feature Type
What does this bug affect

- [ ] Angular Language Service VSCode extension
- [ ] Angular Language Service server

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

Automatically or hint to import other modules or standalone components in the html if the component is not already imported for VS code
### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by pkozlowski-opensource** [comment] 2022-10-07 08:29
Duplicate of #47689

**Comment by atscott** [comment] 2022-10-07 21:36
Closing as duplicate of https://github.com/angular/vscode-ng-language-service/issues/1501. This is actively being worked on and should land in v15/15.1

**Closed by atscott** 2022-10-07 21:36 UTC
Labels: feature
