### ISSUE TITLE
Support Environments without the DOM (NativeScript)

### ISSUE THREAD

**Issue by wSedlacek** [angular/vscode-ng-language-service#1502] opened 2021-09-06 19:46 UTC
**Is your feature request related to a problem? Please describe.**

Yes, usage in NativeScript is quite cumbersome requiring some type hacks. 

# 🚀 feature request

### Description

The language service plugin seems to look at the `document.createElement()` typing to determine types for native elements. On web this is fine but in NativeScript this throws if you remove the DOM types from the project. 

Because NativeScript doesn't have access to the DOM providing these types seems like it could cause false positives elsewhere.

I have hacked my way around this by making a type declaration for `document.createElement()` in my project which resolves the native script components.

It would be nice if there was a way to configure this in a way that was less hacky.

### Feature Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [x] Angular Language Service server

### Describe the solution you'd like
If there was a way to automatically detect native script types or a setting to control what types to look at for element creation that would be fantastic.

The bare minimum would be not throwing with `document.createElement()` is not available. 

### Describe alternatives you've considered

Potential this could be solved on the NativeScript side by providing the type in their modules but declaring a type for document.createElement seems a bit hacky if there no implementation on the global object backing up that declaration. 

### Anything else relevant?

The default schema for Angular relies on DOM elements too so the no error schema has to be used with NativeScript. Perhaps looking at that schema would be safer than the global document type.
That said it would be nice to be able to customize that schema for environments like NativeScript without completely opting out.

**Comment by atscott** [comment] 2021-09-07 18:50
Closing as duplicate of https://github.com/angular/angular/issues/12045. Since the language service relies on compiler output for typechecking, this is more specifically a compiler feature than it is language service related.

**Closed by atscott** 2021-09-07 18:50 UTC
Labels: feature
