### ISSUE TITLE
Event binding behavior very weird in VSCode

### ISSUE THREAD

**Issue by doggy8088** [angular/vscode-ng-language-service#474] opened 2019-12-04 17:02 UTC
**Describe the bug**

Please watch this video I recorded.

https://youtu.be/QxY4O76Zl4A

**To Reproduce**

1. find a tag
2. add a `(click)=""` event binding
3. Unable to find right event when typing

**Expected behavior**

I expected to enter right event binding format.

**Logs**

N/A

**Screenshots**

https://youtu.be/QxY4O76Zl4A

**Additional context**

I'm using version `0.900.0`. When I downgrade to version `0.802.3`, the problem is gone.

**Comment by Sampath-Lokuge** [comment] 2019-12-04 17:27
Yes, this is not working on the latest version `v0.900.0.`. I hope we'll have a fix soon.

**Comment by ayazhafiz** [comment] 2019-12-04 21:36
@doggy8088 @Sampath-Lokuge thank you for the report! My understanding of the bug report is that when you start typing an event binding inside a parentheses, you expect a completion for that event but do not get it:

```html
<div (cli|) ></div>
         ^ expect "click" completion here
```

Is this correct?

**Comment by doggy8088** [comment] 2019-12-05 02:39
@ayazhafiz Yes, that was the expected behavior.

**Comment by Sampath-Lokuge** [comment] 2019-12-05 11:14
@ayazhafiz You can see the GIF here too: https://github.com/johnpapa/vscode-angular-snippets/issues/101#issuecomment-561738202

**Comment by iamcco** [comment] 2019-12-06 04:16
It's weird, I use the same LSP and do not have this issue. don't know if it's vscode's issue

the LSP response the `(click)` item:

``` json
{
        "label": "(click)",
        "kind": 10,
        "detail": "attribute",
        "sortText": "click",
        "textEdit": {
            "range": {
                "start": {
                    "line": 13,
                    "character": 6
                },
                "end": {
                    "line": 13,
                    "character": 6
                }
            },
            "newText": "(click)"
        }
    }
```

**Comment by ayazhafiz** [comment] 2019-12-06 05:02
The issue is that currently, there are two ways to complete a `(click)` binding:

```html
<div cli|></div>
        ^ completing "(click)" will give
<div (click)></div>
```

```html
<div (cli|)></div>
         ^ completing "(click)" will give
<div ((click))></div>
```

In the second, I think the expectation is that a "click" completion is available, giving

```html
<div (cli|)></div>
         ^ completing "click" will give
<div (click)></div>
```

**Comment by ivanwonder** [comment] 2019-12-07 13:22
> It's weird, I use the same LSP and do not have this issue. don't know if it's vscode's issue
> 
> the LSP response the `(click)` item:
> 
> ```json
> {
>         "label": "(click)",
>         "kind": 10,
>         "detail": "attribute",
>         "sortText": "click",
>         "textEdit": {
>             "range": {
>                 "start": {
>                     "line": 13,
>                     "character": 6
>                 },
>                 "end": {
>                     "line": 13,
>                     "character": 6
>                 }
>             },
>             "newText": "(click)"
>         }
>     }
> ```

It's still a little different from the previous version whose range contains `()`

```json
{
        "label": "(click)",
        "kind": 10,
        "detail": "attribute",
        "sortText": "click",
        "textEdit": {
            "range": {
                "start": {
                    "line": 13,
                    "character": 5
                },
                "end": {
                    "line": 13,
                    "character": 7
                }
            },
            "newText": "(click)"
        }
    }
```

Or use [`filterText: "click"`](https://github.com/microsoft/vscode-languageserver-node/blob/dd78cba181136e057cfcc4bb7bc17c7c78877648/types/src/main.ts#L1494)

**Comment by ayazhafiz** [comment] 2019-12-07 15:06
Yes. The reason they differ is because the language service now explicitly tells an editor what text to replace, and in the past the editor got to make that choice. One fix is to provide more precise completions (eg only event bindings in an event binding) and/or conditionally allow the replacement span to include non-identifier characters (https://github.com/angular/angular/blob/master/packages/language-service/src/completions.ts#L48-L51)

**Comment by ivanwonder** [comment] 2019-12-08 04:00
So, I think it should tell the vscode to filter the `CompletionItem` by `click`, now it uses the label `(click)`.
```
<div (cli|) ></div>
         ^ expect "click" completion here
```
It's weird, in my vscode, it can't match the label `(click)`, but it's ok for `click`.

**Comment by shifenis** [comment] 2019-12-09 11:16
Anyone have any workaround?

**Comment by kyliau** [comment] 2019-12-16 20:46
This bug requires multiple PRs for a proper fix.
First PR: https://github.com/angular/angular/pull/34440
I hope to get it fixed by end of this week (December 20)

**Comment by kyliau** [comment] 2019-12-17 02:58
Second PR: https://github.com/angular/angular/pull/34445
This should completely fix the problem.
I'll try to get this into 9.0.0-rc.7 so that the fix can go out this week.

**Closed** 2019-12-18 17:13 UTC
Labels: bug
