### ISSUE TITLE
Syntax highlighting breaks when using nullish coalescing in template wrapped with square brackets

### ISSUE THREAD

**Issue by laggage** [angular/vscode-ng-language-service#1739] opened 2022-08-09 07:54 UTC
# 🐞 bug report

### Description

Using nullish coalescing in template wrapped with square brackets, the syntax highlighting breaks.

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

1. Create or use any project
2. Write a nullish check like `<span ngClass="[value ?? 'value', value2]"></span>`

### **Screenshots**

<img width="963" alt="image" src="https://user-images.githubusercontent.com/38829279/183589761-e25621be-4bcb-4451-a6e7-15ec05bb33ad.png">

## 🌍  Your Environment
**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.3.9
Node: 16.13.1
Package Manager: npm 8.11.0
OS: darwin x64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.6
@angular-devkit/build-angular   13.3.9
@angular-devkit/core            13.3.9
@angular-devkit/schematics      13.3.9
@angular/cdk                    13.3.9
@angular/cli                    13.3.9
@schematics/angular             13.3.9
rxjs                            7.4.0
typescript                      4.5.4
</code></pre>

Extension Version:
<pre><code>
v14.1.0
</code></pre>

VSCode Version:
<pre><code>
Version: 1.70.0 (Universal)
</code></pre>

Operating System:
<pre><code>
macos 12.5 (21G72)
</code></pre>

**Comment by atscott** [comment] 2023-11-13 20:13
I wasn't able to reproduce this using the latest version of the extension. Closing as unable to reproduce.

**Closed by atscott** 2023-11-13 20:13 UTC
Labels: bug
