### ISSUE TITLE
When installing this plugin it breaks intelligence

### ISSUE THREAD

**Issue by okonon** [angular/vscode-ng-language-service#73] opened 2017-04-07 22:41 UTC
vscode: 1.11.1
Steps to reproduce:
1. On any sample project make sure intelligence is working 
2. Install plugin
3. Try to use intelligence and observe that it is stuck on "loading..." indicator
4. Uninstall/disable the plugin and observe that intelligence is working again.

@chuckjaz this might be related to https://github.com/angular/vscode-ng-language-service/issues/67

**Comment by okonon** [comment] 2017-04-07 22:53
@chuckjaz This might be the same as #62  
Attaching zip of sample project:
[node-course.zip](https://github.com/angular/vscode-ng-language-service/files/907032/node-course.zip)

**Comment by chuckjaz** [comment] 2017-04-10 19:16
@okonon I tried the .zip file attached and cannot reproduce it. If it is similar to #62 then it would have to not contain a `tsconfig.json` file. Is that what you were trying to reproduce or can you reproduce with what you sent?

**Comment by okonon** [comment] 2017-04-10 22:19
I don't think the issue is project specific if you disable the plug-in the problem goes away by zombie processes are still present

**Comment by okonon** [comment] 2017-04-10 22:20
You my other colleagues have noticed the same thing told him about the plug in the nay installed we all have to disable it and install it in order for our machines to be usable dude to the  CPU usage

**Comment by chuckjaz** [comment] 2017-04-13 21:37
I believe this is now fixed in `0.1.3`.

**Closed by chuckjaz** 2017-04-13 21:37 UTC
Labels: bug, needs repro
