### ISSUE TITLE
Load the angular language service only in configured projects

### ISSUE THREAD

**Issue by kaname-png** [angular/vscode-ng-language-service#1700] opened 2022-06-20 16:18 UTC
# 🚀 feature request

### Description
 As far as I see the plugin always starts with any project even if it is not Angular and only TypeScript, I think it would be nice to be able to configure in which projects you need the plugin to start and start the angular language service.

This leads to unnecessary resource usage.

### Feature Type
What does this bug affect

- [X] Angular Language Service VSCode extension
- [ ] Angular Language Service server

### Describe the solution you'd like
 An option to set in which projects the angular language service will start.

### Describe alternatives you've considered
 Disable the plugin manually every time I'm in a non-angular project.

### Anything else relevant?

No.

**Comment by atscott** [comment] 2022-06-21 15:50
Closing as duplicate of https://github.com/angular/vscode-ng-language-service/issues/481 in spirit.

While a single project might not include Angular, there may be another project in the workspace that does. Because extensions run per workspace, it's harder to determine at startup if the extension applies or not. We already do [quick exits](https://github.com/angular/vscode-ng-language-service/blob/main/client/src/client.ts#L82) from requests if the file is not in an Angular project. This result is cached for the file and already quick and inexpensive. There would be very minimal savings for disabling the plugin altogether.

**Closed by atscott** 2022-06-21 15:50 UTC
Labels: feature
