### ISSUE TITLE
V14.0 doesn't work

### ISSUE THREAD

**Issue by Kcorab** [angular/vscode-ng-language-service#1683] opened 2022-06-05 09:38 UTC
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 13.3.1

### Description

It simply doesn't work. The completion in template (html) doesn't list my variables. See the screenshot, please. I try this with different Angular versions like 11, 13 and 14. Same behavior. If I downgrade to V13.3.1 it works but of curse only for Angular versions < 14.
![bug_image_1](https://user-images.githubusercontent.com/7406477/172044252-5dbec484-86e2-4ef8-bbe2-812ef6f5d89a.png)

## Bug Type

I doen't know.

### **Screenshots**

![bug_image_2](https://user-images.githubusercontent.com/7406477/172044503-e5cfa96c-3b04-4bbf-88d3-48b54e3bbdef.png)

**Comment by dotkext** [comment] 2022-06-06 09:31
There is a problem with variable name refactor too.

"Element can't be renamed. Delegating to Angular Language Service".

**Comment by atscott** [comment] 2022-06-06 15:46
Please provide a reproduction.

**Comment by ivanwonder** [comment] 2022-06-07 15:19
> There is a problem with variable name refactor too.
> 
> "Element can't be renamed. Delegating to Angular Language Service".

through my observation, when the cursor is at the end of the name, the compiler skips the node and breaks the rename. You can try to move the cursor ahead and retry.

https://github.com/angular/angular/blob/627cdf31a39bc7a3bf587e3a25d6f84dacb55308/packages/language-service/src/ts_utils.ts#L16

**Comment by t-bowersox** [comment] 2022-06-07 15:31
> > There is a problem with variable name refactor too.
> > "Element can't be renamed. Delegating to Angular Language Service".
> 
> through my observation, when the cursor is at the end of the name, the compiler skips the node and breaks the rename. You can try to move the cursor ahead and retry.
> 
> https://github.com/angular/angular/blob/627cdf31a39bc7a3bf587e3a25d6f84dacb55308/packages/language-service/src/ts_utils.ts#L16

That has been my experience, as well. I had logging enabled for the extension when I reproduced this. Here's a video and log excerpt if it's helpful:

https://user-images.githubusercontent.com/11789189/172420586-cacb340e-6a46-4deb-a61a-44dc07d3c8a7.mov

```
Info 1488 [11:25:12.580] -----------------------------------------------
Perf 1489 [11:25:12.750] LanguageService#LsReferencesAndRenames: {"events":{"GenerateTcb":105,"ReuseTypeCheckFile":1,"UpdateTypeCheckProgram":1},"phases":{"Unaccounted":10,"TcbGeneration":441938,"TcbUpdateProgram":528739,"LsReferencesAndRenames":168964},"memory":{"TtcUpdateProgram":576233884}}
```

If I clicked somewhere in the middle of `newForm` and try again, the rename worked.

**Comment by x-strong** [comment] 2022-06-08 03:56
> Please provide a reproduction. I was unable to reproduce this on Mac or Linux with any Angular project using various versions.

Try on Windows 10.

**Comment by atscott** [comment] 2022-06-08 17:32
@x-strong done. I could not reproduce this on Windows 10 either. Angular language service features are working as expected. Tested projects using Angular v12, 13, and 14. 

Closing as unable to reproduce. If the problem still exists in your application, please open a new issue and follow the instructions in the issue template, including a reproduction.

**Closed by atscott** 2022-06-08 17:32 UTC
Labels: bug, needs repro
