### ISSUE TITLE
add the setting to enable or disable AOT Diagnostic messages

### ISSUE THREAD

**Issue by 1203623465** [angular/vscode-ng-language-service#804] opened 2020-06-03 07:59 UTC
I think maybe you can add a setting to turn off or turn on AOT Diagnostic

**Comment by ayazhafiz** [comment] 2020-06-09 01:40
Is this a duplicate of #308?

**Comment by 1203623465** [comment] 2020-06-09 01:50
Sorry, I didn't notice that 308 already exists. I have the same idea as him. I hope that this feature will be added in subsequent versions.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hafiz"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月9日(星期二) 上午9:40
收件人:&nbsp;"angular/vscode-ng-language-service"<vscode-ng-language-service@noreply.github.com&gt;;
抄送:&nbsp;"#97"<1203623465@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [angular/vscode-ng-language-service] add the setting to enable or disable AOT Diagnostic messages (#804)





 
Is this a duplicate of #308?

**Comment by ayazhafiz** [comment] 2020-06-09 01:51
Yeah there is some thought of this but little resources to do it right now. We welcome any community contributions though!

I am closing this as a duplicate.

**Closed by ayazhafiz** 2020-06-09 01:51 UTC
Labels: feature
