### ISSUE TITLE
[(ngModel)] is not working with this extension v17.2.2, even prevents rendering.

### ISSUE THREAD

**Issue by icpcbot1209** [angular/vscode-ng-language-service#2015] opened 2024-03-12 21:31 UTC
I've wasted a lot of time why ngModel is marked as a bug.
Even angular building is failed because of this "error".
After disabling Angular Language Service extension, it worked fine.
I even thought ngModel is not working anymore with new version of Angular and Ionic.
Why this extension even dare prevents building?
And what's wrong with ngModel?

![image](https://github.com/angular/vscode-ng-language-service/assets/64293836/97d7157f-6f4b-4e19-907f-bb41ae98a7ef)

**Comment by atscott** [comment] 2024-03-12 21:36
Duplicate of https://github.com/angular/vscode-ng-language-service/issues/2001

See https://github.com/angular/vscode-ng-language-service/issues/2001#issuecomment-1971905871 for potential workarounds

**Closed by atscott** 2024-03-12 21:36 UTC
Labels: bug

**Comment by Alijavedofficial** [comment] 2024-03-13 15:21
The ngModel directive is part of Angular's FormsModule, which is used for template-driven forms. If you're encountering issues with ngModel, it's crucial to ensure that FormsModule is imported in your module.
