### ISSUE TITLE
CTRL + CLICK  on web-component should open corresponding html file.

### ISSUE THREAD

**Issue by ubaidazad** [angular/vscode-ng-language-service#83] opened 2017-04-17 06:29 UTC
clicking on web-component in html file, should open the corresponding .html file , if `templateUrl `is present in the `@Component `Directive.

**Comment by kyliau** [comment] 2019-08-19 17:53
Closing this since it's a duplicate of https://github.com/angular/vscode-ng-language-service/issues/111

**Closed by kyliau** 2019-08-19 17:53 UTC
Labels: enhancement
