### ISSUE TITLE
Error for getCompletions: Error: Debug Failure. 

### ISSUE THREAD

**Issue by fvilers** [angular/vscode-ng-language-service#219] opened 2018-01-22 13:18 UTC
Hi there,

One more error I get very often:

```
Error for getCompletions:
    Error: Debug Failure. 
    at tryReuseStructureFromOldProgram (C:\Users\Fabian\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\typescript\lib\typescript.js:69547:22)
    at Object.createProgram (C:\Users\Fabian\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\typescript\lib\typescript.js:69310:34)
    at synchronizeHostData (C:\Users\Fabian\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\typescript\lib\typescript.js:89172:33)
    at Object.getProgram (C:\Users\Fabian\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\typescript\lib\typescript.js:89273:13)
    at TypeScriptServiceHost.getSourceFile (C:\Users\Fabian\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:39172:31)
    at TypeScriptServiceHost.getTemplateAt (C:\Users\Fabian\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:39090:31)
    at LanguageServiceImpl.getTemplateAstAtPosition (C:\Users\Fabian\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:38819:34)
    at LanguageServiceImpl.getCompletionsAt (C:\Users\Fabian\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:38801:33)
    at C:\Users\Fabian\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:2706:72
    at time (C:\Users\Fabian\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:2695:22)
```

Thanks for your help!

**Comment by chuckjaz** [comment] 2018-01-23 23:32
@fvilers Again, can you produce a project I can clone that reproduces this?

**Comment by fvilers** [comment] 2018-01-25 09:05
Hi @chuckjaz, I'm sorry but I can't share the project I'm working on. The errors happen randomly, but it seems that they are more frequent after several branch changes (git).

**Comment by t-hervey** [comment] 2018-02-27 03:45
Hi @chuckjaz, I have have this happening pretty consistently on a project that I have.  Included is a zip file of the entire project. 

Just noticed in the output that I'm getting the above error as well as this one:

> Error for getDiagnostics:
    Error: Debug Failure. False expression.
    at checkChangeRange (C:\Users\Travis\.vscode\extensions\Angular.ng-template-0.1.9\server\node_modules\typescript\lib\typescript.js:19193:26)
    at Object.updateSourceFile (C:\Users\Travis\.vscode\extensions\Angular.ng-template-0.1.9\server\node_modules\typescript\lib\typescript.js:18827:13)
    at Object.updateSourceFile (C:\Users\Travis\.vscode\extensions\Angular.ng-template-0.1.9\server\node_modules\typescript\lib\typescript.js:13144:47)
    at Object.updateLanguageServiceSourceFile (C:\Users\Travis\.vscode\extensions\Angular.ng-template-0.1.9\server\node_modules\typescript\lib\typescript.js:95555:44)
    at acquireOrUpdateDocument (C:\Users\Travis\.vscode\extensions\Angular.ng-template-0.1.9\server\node_modules\typescript\lib\typescript.js:80801:43)
    at Object.updateDocumentWithKey (C:\Users\Travis\.vscode\extensions\Angular.ng-template-0.1.9\server\node_modules\typescript\lib\typescript.js:80781:20)
    at Object.getOrCreateSourceFileByPath [as getSourceFileByPath] (C:\Users\Travis\.vscode\extensions\Angular.ng-template-0.1.9\server\node_modules\typescript\lib\typescript.js:95789:49)
    at tryReuseStructureFromOldProgram (C:\Users\Travis\.vscode\extensions\Angular.ng-template-0.1.9\server\node_modules\typescript\lib\typescript.js:72291:28)
    at Object.createProgram (C:\Users\Travis\.vscode\extensions\Angular.ng-template-0.1.9\server\node_modules\typescript\lib\typescript.js:72004:34)
    at synchronizeHostData (C:\Users\Travis\.vscode\extensions\Angular.ng-template-0.1.9\server\node_modules\typescript\lib\typescript.js:95724:26)

and

> Error for getCompletions:
    Error: Debug Failure. False expression.
    at tryReuseStructureFromOldProgram (C:\Users\Travis\.vscode\extensions\Angular.ng-template-0.1.9\server\node_modules\typescript\lib\typescript.js:72261:22)
    at Object.createProgram (C:\Users\Travis\.vscode\extensions\Angular.ng-template-0.1.9\server\node_modules\typescript\lib\typescript.js:72004:34)
    at synchronizeHostData (C:\Users\Travis\.vscode\extensions\Angular.ng-template-0.1.9\server\node_modules\typescript\lib\typescript.js:95724:26)
    at Object.getProgram (C:\Users\Travis\.vscode\extensions\Angular.ng-template-0.1.9\server\node_modules\typescript\lib\typescript.js:95798:13)
    at TypeScriptServiceHost.getSourceFile (C:\Users\Travis\.vscode\extensions\Angular.ng-template-0.1.9\server\node_modules\@angular\language-service\bundles\language-service.umd.js:58705:31)
    at TypeScriptServiceHost.getTemplateAt (C:\Users\Travis\.vscode\extensions\Angular.ng-template-0.1.9\server\node_modules\@angular\language-service\bundles\language-service.umd.js:58613:31)
    at LanguageServiceImpl.getTemplateAstAtPosition (C:\Users\Travis\.vscode\extensions\Angular.ng-template-0.1.9\server\node_modules\@angular\language-service\bundles\language-service.umd.js:58352:34)
    at LanguageServiceImpl.getCompletionsAt (C:\Users\Travis\.vscode\extensions\Angular.ng-template-0.1.9\server\node_modules\@angular\language-service\bundles\language-service.umd.js:58334:33)
    at C:\Users\Travis\.vscode\extensions\Angular.ng-template-0.1.9\server\editorServices.js:2706:72
    at time (C:\Users\Travis\.vscode\extensions\Angular.ng-template-0.1.9\server\editorServices.js:2695:22)

Those errors occur anytime I try to type something in the component.html file.

[src.zip](https://github.com/angular/vscode-ng-language-service/files/1761142/src.zip)

Using VS Code 1.20.1 and Angular Language Service 0.1.9 on Windows 10 Pro 

Hope this helps, I'd really like to be able to use this extension.

Thanks!

**Comment by t-hervey** [comment] 2018-02-27 03:54
So something else interesting I found, I can't reproduce this on my machine when the source files are local to my machine.  Originally I was editing these files over a samba network share and were getting the above errors.  When I copied them to my local machine this extension worked fine.

**Comment by kyliau** [comment] 2019-11-09 00:15
Closing this, I believe this has already been fixed. Please open a new issue otherwise, thank you!

**Closed by kyliau** 2019-11-09 00:15 UTC
Labels: bug, needs repro
