### ISSUE TITLE
User-defined pipe not found

### ISSUE THREAD

**Issue by aaron-bond** [angular/vscode-ng-language-service#98] opened 2017-05-20 14:40 UTC
When I have a pipe on a component, the language service tells me it can't find it - even though the app builds without a problem and the pipe is correctly detected.

![capture](https://cloud.githubusercontent.com/assets/14099631/26276624/a9b63e32-3d72-11e7-9471-1c73068fde31.PNG)

**Comment by rolandoldengarm** [comment] 2017-06-08 08:20
Yep I've got the same problem! I've got the pipe defined in a shared module, and in the feature module I've imported the shared module. 
Builds fine, but it's not detected in the language service.

**Comment by chuckjaz** [comment] 2017-06-20 22:02
@aaron-bond Do you have a repo or a .zip file that reproduces this issue?

**Comment by bmayen** [comment] 2017-10-18 21:23
Same here. I see this happen when the pipe's module is imported in a SharedModule, included in that module's `exports`, and then imported into a feature module. Components in the feature module will show this error.

**Comment by JWess** [comment] 2018-03-20 18:40
I have the exact same problem as @rolandoldengarm . My pipe is defined in, and exported from, a SharedModule. The SharedModule is imported into my AppModule. app.component.html uses my pipe, but VSCode shows the error `The pipe 'pipeNameHere' could not be found.`.

**Comment by RMo-Sloth** [comment] 2018-09-22 14:29
I had an issue exactly as described in this post. But it was because I referred to the pipes in an incorrect manner. Not angular.

I had a pipe like:

```
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'url'
})

export class UrlPipe implements PipeTransform {

  transform(value: string ): string {
    return `url(${value})`;
  }

}
```

and in the template I would refer to it as:

```
<div [style.background]="backgroundUrl | UrlPipe">
```

This would result in the exact situation described in this issue. However I should have refered to the name you defined in the @Pipe decorator and not the name of the class ( which is used to register it in your module ).

```
<div [style.background]="backgroundUrl | url">
```

I am not sure if this will solve the issues described ( since there isn't a lot of code provided ). But it just might be what happened.

**Comment by kyliau** [comment] 2020-01-13 20:35
Closing this, since original issue is more than two years old. If problem persists, please open a new issue with screenshot, code example, and log information. Thanks!

**Closed by kyliau** 2020-01-13 20:35 UTC
Labels: bug, needs repro
