### ISSUE TITLE
Advance template tag parameter suggestion

### ISSUE THREAD

**Issue by netdjw** [angular/vscode-ng-language-service#855] opened 2020-07-11 08:43 UTC
Hi there!

I just started use your extension, and it's very poweful tool to speed up my work. And at this point I have a comment that would make the work even faster.

In the HTML template I type this string:

```html
<ng-container *ngi
```
Your extension show me suggestions to `ngIf` and if I hit then I get this result:

```html
<ng-container *ngIf
```

But it would be much more better this result:

```html
<ng-container *ngIf=""
```
And even more better if you could put the cursor between the `""` signs. This small modification can help type faster and prevent many typos. And it would be similar like the basic working of VSCode's HTML tag parameter suggestions.

**Comment by ivanwonder** [comment] 2020-07-13 01:17
duplicate #521

**Comment by ayazhafiz** [comment] 2020-11-03 22:57
Closing as a dupe of 521, as @ivanwonder mentioned.

**Closed by ayazhafiz** 2020-11-03 22:57 UTC
Labels: feature
