### ISSUE TITLE
Trying to install a specific version following the README. Can't find the .vsix files ( only sources ) in the release tab.

### ISSUE THREAD

**Issue by elira** [angular/vscode-ng-language-service#868] opened 2020-07-21 11:27 UTC
I'm trying to downgrade to 10.0003. But can't find the vsix file.
This is probably a misunderstanding by me. But I would appreciate some help. Thanks.
**To Reproduce**

1. Go to the releases tab [releases tab](https://github.com/angular/vscode-ng-language-service/releases)
2. Try to find a download link to the .vsix file.
3. No link found

**Expected behavior**
A link to the .vsix file should be found on the page.
**Screenshots**

![image](https://user-images.githubusercontent.com/405275/88049630-2963eb80-cb5e-11ea-95d3-b827eec87a08.png)

**Comment by rjlopezdev** [comment] 2020-07-21 12:36
Hi @elira 
`v0.1000.4`seems to be broken for me too.
You can downgrade to `v0.1000.3` by right-click on extension & selecting that version.

![image](https://user-images.githubusercontent.com/18118062/88055545-77c5ba00-cb5f-11ea-89f5-308ded3ec0b4.png)

**Comment by elira** [comment] 2020-07-21 13:25
Thanks @rjlopezdev. You saved me. Downgraded successfully.
The for the downgrade: "Go to definition from template files was not working for me in 0.1004"

**Comment by kyliau** [comment] 2020-07-31 00:37
Duplicate of https://github.com/angular/vscode-ng-language-service/issues/859 which has been fixed with the release of v0.1000.7
Going forward, we will make sure to attach the vsix files in each release.

**Closed by kyliau** 2020-07-31 00:37 UTC
Labels: bug
