### ISSUE TITLE
Support property rename for template of angular components

### ISSUE THREAD

**Issue by laggage** [angular/vscode-ng-language-service#1632] opened 2022-04-26 03:55 UTC
Rename a component property doesn't update template when initiated from ts.
It works when initiated from template though.

```ts
// mycomp.component.ts
@Component({
  selector: 'my-comp',
  templateUrl: './mycomp.component.html'.
})
export class MyComponent {
  foo: any;
} 
```

```html
<!-- mycomp.component.html -->
<div>{{ foo }}</div>
```
foo won't get renamed in html when rename (highlight + F2) initiated from ts.
foo will get renamed in ts when rename initiated from html.
Single file component (ts)

```ts
@Component({
  selector: 'my-comp',
  template: `<div>{{ foo }}</div>`
})
class MyComp {
  foo: any;
}
```
- Rename worked if initiated from html template;
- foo will not get renamed in html when rename initiated from within class.

https://github.com/microsoft/vscode/issues/142298

**Comment by ivanwonder** [comment] 2022-04-26 12:20
Duplicate of #1609 
Or you can try the release here: https://github.com/angular/vscode-ng-language-service/releases/tag/v14.0.0-next.0.

**Comment by atscott** [comment] 2022-04-26 15:01
That’s right. @ivanwonder was able to find a workaround to the VSCode limitation that made us disable the renaming in TS files. It’s available in the linked v14 pre-release.

**Closed by atscott** 2022-04-26 15:01 UTC
Labels: feature
