### ISSUE TITLE
Support optional chaining in template

### ISSUE THREAD

**Issue by marcelnem** [angular/vscode-ng-language-service#149] opened 2017-08-18 14:22 UTC
in 0.1.4 on Windows 10

`errors?.required` is highlighted as an error

<div class="container">

    <form (submit)="onSubmit()" novalidate #f="ngForm" (ngSubmit)="onSubmit(f)">
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" [(ngModel)]="user.name" name="name" #userName="ngModel" minLength="2" required>
            <div *ngIf="userName.touched && userName.errors?.required" class="alert alert-danger">Name is required</div>
        </div>
        <div class="form-group">
            <label for="name">Email</label>
            <input type="text" class="form-control" [(ngModel)]="user.email" name="email" #userEmail="ngModel" required>
        </div>
        <div class="form-group">
            <label for="age">Phone</label>
            <input type="number" class="form-control" [(ngModel)]="user.phone" #userPhone="ngModel" name="phone" minlength="10">
        </div>
        <input type="submit" value="Submit" class="btn btn-success">
    </form>
</div>

![image](https://user-images.githubusercontent.com/6547340/29462941-4be9d6a0-8431-11e7-81da-63866f8d6c97.png)

**Comment by Kurtz1993** [comment] 2017-08-28 02:49
Also happening on OS X 10.11.6 (El Capitan).

OS: OS X 10.11.6
Extension version: 0.1.4
VS Code version: 1.15.1

**Comment by Duanthse03268** [comment] 2017-08-31 04:20
I also got this problem on Window 10 x64
Extension version 0.1.7
VS Code version 1.15.1
Please fix it soon

**Comment by matthew-ch** [comment] 2017-09-26 06:42
Same problem here.
Error is: 'Identifier 'errors' is not defined. 'NgModel' does not contain such a member'.

OS: macOS 10.13 
Extension: 0.1.7
VS Code: 1.16.1
Angular: 4.4.3
Typescript: 2.5.2

**Comment by imomer** [comment] 2017-10-03 09:43
Same problem! Any solution?

**Comment by VladBozhinovski** [comment] 2017-10-04 10:56
Make sure u import 
`import { FormsModule, Validators } from '@angular/forms';`

**Comment by imomer** [comment] 2017-10-04 12:15
Should I import it in the app.module or in my component where the form is exist?

**Comment by VladBozhinovski** [comment] 2017-10-04 13:15
@imomer In the component mate

**Comment by PBartrina** [comment] 2017-10-09 12:47
The @angular/forms imports mentioned by @VladBozhinovski won't solve it. 

The template mark as error every elvis operator used at the last point. For example

`Object?.son` is marked as error
`Object?.son?.son` is marked as error
`Object.son?.son` is marked as error
`Object?.son.son` is valid

**Comment by imomer** [comment] 2017-10-09 13:09
Yeah didn't work me either...

**Comment by ultra2mh** [comment] 2017-11-22 05:42
i have same problem .... any solution ?

**Comment by SlashD9** [comment] 2017-12-03 22:51
Same Issue, has anyone found a fix?

**Comment by pahofmann** [comment] 2017-12-19 22:00
Same issue here. Any ideas yet?

**Comment by Abdullahdevops** [comment] 2017-12-21 08:52
I also got this problem any solutions

**Comment by ToxSickCoder** [comment] 2017-12-22 11:44
Same here.

**Comment by mezubeen** [comment] 2017-12-26 03:15
it seems like I'm not alone :)

**Comment by Duanthse03268** [comment] 2017-12-26 03:37
So many people got this problem. You guys can prevent it like 'email?.error.required'

**Comment by morhys** [comment] 2018-01-06 01:16
@Duanthse03268 this worked by removing the red line error but still get the following console error, any idea why ?

`FoodFormComponent.html:9 ERROR TypeError: Cannot read property 'minlength' of undefined
    at Object.eval [as updateDirectives] (FoodFormComponent.html:10)
    at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js:13056)
    at checkAndUpdateView (core.es5.js:12236)
    at callViewAction (core.es5.js:12601)
    at execComponentViewsAction (core.es5.js:12533)
    at checkAndUpdateView (core.es5.js:12242)
    at callViewAction (core.es5.js:12601)
    at execComponentViewsAction (core.es5.js:12533)
    at checkAndUpdateView (core.es5.js:12242)
    at callWithDebugContext (core.es5.js:13456)`

**Comment by niblux** [comment] 2018-01-06 01:16
@Duanthse03268 this worked by removing the red line error but still get the following console error, any idea why ? `FoodFormComponent.html:9
ERROR TypeError: Cannot read property 'minlength' of undefined at Object.eval [as updateDirectives] (FoodFormComponent.html:10)
at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js:13056) at checkAndUpdateView (core.es5.js:12236) at callViewAction
(core.es5.js:12601) at execComponentViewsAction (core.es5.js:12533) at checkAndUpdateView (core.es5.js:12242) at callViewAction
(core.es5.js:12601) at execComponentViewsAction (core.es5.js:12533) at checkAndUpdateView (core.es5.js:12242) at callWithDebugContext
(core.es5.js:13456)`

**Comment by Duanthse03268** [comment] 2018-01-06 02:25
Make sure u import
import { FormsModule, Validators } from '@angular/forms';

**Comment by joonashak** [comment] 2018-01-08 21:08
None of the solutions in this thread resolve the issue. I made an example as simple as possible to make sure nothing else was messing it up:

![screen shot 2018-01-08 at 22 56 53](https://user-images.githubusercontent.com/18666321/34692016-4249e67e-f4c7-11e7-9d6f-6757d01d076d.png)

FormModule and Validators have been imported from @angular/forms. I also tested [the solution](https://github.com/angular/vscode-ng-language-service/issues/149#issuecomment-353912332) by @Duanthse03268, and not only does it not resolve the red line issue, it also causes an error in console when the state of myField changes (TypeError: Cannot read property 'required' of null).

My implementation works without errors in the browser but retains the (supposedly incorrect) red line in editor (VSCode). Gists of the files in question (everything else you can simply 'ng new...' to reproduce):

[app.module.ts](https://gist.github.com/joonashak/a161c80d8184585df85958c8609f01bf)
[app.component.ts](https://gist.github.com/joonashak/c71ce032a99d088484747f8b688cfa20)
[app.component.html](https://gist.github.com/joonashak/5750dad903e8050f5e9dab998dd3dcb4)

Versions:

Extension: 0.1.7
VSCode: 1.19.1
Angular CLI: 1.6.3
Node: 9.2.1
OS: macOS 10.12.6
Angular: 5.1.3
Chrome: 63.0.3239.84

**Comment by Duanthse03268** [comment] 2018-01-09 01:45
Why did not you try to use 'myfield?.error.required' .

**Comment by joonashak** [comment] 2018-01-09 08:30
I did try it, just as I wrote in my previous comment: "not only does it not resolve the red line issue, it also causes an error in console when the state of myField changes (TypeError: Cannot read property 'required' of null)".

So, to elaborate, 'myField?.errors.required' does not work and causes the above error message to be displayed in console. The '?' has to be written after 'errors' in order to have this code work in browser without error message, yet does not solve the original issue of incorrect red line in editor.

**Comment by Rawr421** [comment] 2018-01-10 15:58
This is extremely annoying as the red lines are there still but the functionality works.  I agree with joonashak as the solutions presented do not work and trying both formats do not resolve the issue.

**Comment by coder925** [comment] 2018-01-10 21:11
For me @Duanthse03268 suggested solution of `myControl?.errors?.required'` is working (both in template-driven forms and reactive forms).

In @joonashak case, I believe it has to do with that **myField** is not a public variable in _app.component.ts_, nor a [template reference variable](https://angular.io/guide/template-syntax#template-reference-variables--var-) in _app.component.html_ .

If you access [your control](https://angular.io/api/forms/AbstractControl) via `form.controls` or add `@ViewChild('myFieldControl') myFieldControl;` in the component it does not show an error:
 
![image](https://user-images.githubusercontent.com/24881789/34794889-74ef29b0-f650-11e7-9a40-cdc18b6b1838.png)

**Comment by Ahnset** [comment] 2018-01-18 00:52
this worked for me:
<div *ngIf="clientFirstName?.errors?.required

I Hope it helps you

**Comment by brunobertechini** [comment] 2018-01-23 00:01
Only workarounds :(

**Comment by neha16k** [comment] 2018-02-06 10:07
IntelliJ throws the same error for me. But the implementation works even with the errors in the browser. Workaround by @Ahnset worked for me. Would like to know what is this syntax and how is it working now?

**Comment by adickenscheidt** [comment] 2018-02-09 15:35
I found that this error appears every time you reference a property which is defined as 'any'. Another workaround is using the bracket property annotation, clientFirstName?.errors['required'] which is also pretty stupid.

**Comment by Nomadzy** [comment] 2018-02-23 14:48
Its getting worst, with the latest update of vscode, my file tree has become more like a christmas tree :christmas_tree:

**Comment by kdawg1406** [comment] 2018-02-27 02:55
@adickenscheidt thank you for the workaround. Works great, agree dumb for now.

**Comment by SrdanTop** [comment] 2018-03-10 14:20
removed Angular Language Service

**Comment by Kant2** [comment] 2018-03-19 16:53
@Duanthse03268 Your function work! Thanks.

**Comment by KobiHason** [comment] 2018-03-20 11:57
@adickenscheidt 
Thanks this solution work for me

**Comment by rao53** [comment] 2018-04-18 15:26
It worked. Much appreciated @Duanthse03268

**Comment by robbiegod** [comment] 2018-04-25 20:54
@Duanthse03268 Your function work! But what does it mean exactly?

**Comment by imchaitanya9** [comment] 2018-05-02 06:54
It doesn't work for nested object property
`<mat-select [(ngModel)]="object?.object?.property" name="property" #property="ngModel">`
getting supercool parsing errors on `object?.object?.property`

**Comment by MarkPhillips** [comment] 2018-05-08 17:27
email.errors['required']  worked for me

**Comment by MisterRaj** [comment] 2018-05-11 07:48
@guignol1981  Solution worked for me.

**Comment by renemaldonado** [comment] 2018-05-22 16:30
Using this worked for me: <div *ngIf="clientFirstName?.errors.required
Only  the element name needs the ? mark. It's not so ugly

**Comment by jgill248** [comment] 2018-05-25 13:44
I have the same issue, but none of the proposed solutions have worked:
"form?.get('name').errors.required"
"form?.get('name').errors.['required']"
"form?.get('name').errors?.required"

**Comment by antonheck** [comment] 2018-05-25 14:38
Hello try it like this. 
Form.hasError('required');

**Comment by jgill248** [comment] 2018-05-29 19:27
That worked for me.  Thanks @antonheck

**Comment by herzinger** [comment] 2018-06-05 16:57
there are a few workarounds, each better for different situation, yes. But that is not the issue. I shouldn't have to write my code differently, including ugly, hacky sintaxe, only to appease an IDE extension, when what I wrote was right from the start.

**Comment by fredgate** [comment] 2018-06-09 17:20
I have exactly same problem and message with this similar code :
```
class MyComponent {
  form: FormGroup;
}
```
with lines like this in the template :
```
<app-errors [control]="form.controls.email">
```

Error message :

> Identifier 'email' is not defined. '__type' does not contain such a member

Problem is caused by fields of type like (it occurs with AbstractControl or something else of course) :
```
{  [key: string]: AbstractControl;  };
```

I have this message in Visual Studio Code (Windows) and Angular Language Services, but not with `ng lint`.

**Comment by tmrony** [comment] 2018-06-21 07:56
Best solution so far:
https://github.com/angular/vscode-ng-language-service/issues/126#issuecomment-366200219

**Comment by trungkmy** [comment] 2018-06-30 15:17
Thanks tmrony, the best solution after many days looking...

**Comment by trungkmy** [comment] 2018-06-30 15:29
Thanks tmrony, best solution after many days searching...

**Comment by boban984** [comment] 2018-07-12 12:00
Actually it's supposed to be like this, the error highlight is shown because the "errors" property of "AbstractControl" has no strictly defined properties, it's of type "[ValidationErrors](https://angular.io/api/forms/ValidationErrors)"

So directly accessing a validation rule is causing the error, in my case accessing it using square bracket notation solves the issue.

(btw even if i access the validation property directly i am not getting compilation errors, the app works fine either way)

![image](https://user-images.githubusercontent.com/1124994/42631651-06b1c172-85db-11e8-90d8-9853475bca84.png)

**Comment by jardelsimao** [comment] 2018-07-31 20:43
@adickenscheidt Solution worked for me! thanks

**Comment by riakharisma** [comment] 2018-08-02 09:16
"price.errors['required']"    --> Worked
"!!price.errors.required"     --> Worked

**Comment by ADomeika** [comment] 2018-08-10 15:53
"price?.errors?.required" should also work, because my "fullname?.errors?.required" works

**Comment by roniaxe** [comment] 2018-08-15 21:34
> "price.errors['required']" --> Worked

That doesn't trigger the compiler 'identifier is not defined' but it's not a good solution, because if errors object is null, it will error on the console about it.

**Comment by mikesun23** [comment] 2018-08-28 08:03
@boban984 
this is the winner solution and explanation.

**Comment by thw0rted** [comment] 2018-08-31 07:51
I was glad to find the `hasError()` method discussed here, it's certainly the clearest way to show the intent of the template conditional and I think I'll try to use it exclusively going forward.

However... nobody is addressing the root cause of the problem, and it's been an issue with the language service for something like a year now.  The `errors` property has a key index signature (`[key: string]: any`) which means that in TS code, the statement `myControl.errors.anythingYouLike` will compile cleanly, no matter what strict-mode flags you have set.  This is correct, because the entire point of having an index signature like that is to be able to create arbitrary properties at runtime, and access them by either dot-notation or index-notation.  The language service allows index-notation, which is why `control?.errors['required']` works, but flags dot-notation as incorrect, which is an error.

**Comment by zhaoqian** [comment] 2018-10-07 03:44
three solutions:
`
<span *ngIf=" username.errors['email']">must be email</span>
<span *ngIf="!!username?.errors.email">must be email</span>
<span *ngIf="username.hasError('email')">must be email</span>
`
I like the third best

**Comment by vaibhavphutane** [comment] 2018-11-04 18:20
@boban984 Great solution and explanation

**Comment by makitodev** [comment] 2018-11-14 18:02
thnks, works for me!. 👍🏼
i hate view Errors on console 😬

**Comment by marlonpatrick10** [comment] 2018-11-21 15:55
> Hello try it like this.
> Form.hasError('required');

This was the most elegant solution, and really works for all cases: myForm.hasError('required', 'myField')

**Comment by bePericon** [comment] 2019-02-17 18:03
I solved this problem in this way:
# example.component.ts:
`
this.myForm = this.formBuilder.group({
      field: ['', [Validators.required, Validators.maxLength(10)]]
});

get getField() { return this.myForm.get('field'); }
`
# example.component.html:
`
<div *ngIf="getField.errors" class="invalid-feedback">
  <div *ngIf="getField.hasError('required')"> Text required </div>
  <div *ngIf="getField.hasError('maxlength')"> Text maxLength </div>
</div>
`
I hope to be helpful.

**Comment by andrecontdi** [comment] 2019-03-29 00:28
Perfect @bePericon this works for me! 
Thanks!

**Comment by sohana08** [comment] 2019-04-08 10:00
<input type="text"  formControlName="name" class="form-control" placeholder="Full name">
            <div *ngIf="submitted && f['name'].errors" class="alert alert-danger">
              <div *ngIf="f['name'].errors.required">Full Name is required</div>
            </div>

try this. It worked for me in Angular 7

**Comment by sohana08** [comment] 2019-04-08 10:01
` <input type="text"  formControlName="name" class="form-control" placeholder="Full name">
            <div *ngIf="submitted && f['name'].errors" class="alert alert-danger">
              <div *ngIf="f['name'].errors.required">Full Name is required</div>
             </div>`

**Comment by JounQin** [comment] 2019-06-15 15:02
So indexSoo  after two years, it has not been fixed? 🤣
related: https://github.com/angular/vscode-ng-language-service/issues/110

**Comment by Dacomis** [comment] 2019-07-10 11:33
I had TS Lint activated with interfered.
After I disabled it and restart the app everything was ok and the errors disappeared.
Then I uninstalled TS Lint. :))
For me, everything worked perfectly but the IDE (VS Code) showed me errors.

**Comment by boban984** [comment] 2019-07-16 07:17
> So after two years, it has not been fixed? 🤣
> related: #110

It's not a bug, it's exactly the way it should work

**Comment by dtromblee** [comment] 2019-07-24 17:52
If this is expected functionality, can the documentation be updated? (see [here](https://angular.io/guide/form-validation#template-driven-validation) for one example).

This clearly infers the raw property accessors of `ngModel` can be used, where this thread has established they definitely cannot.

**Comment by thw0rted** [comment] 2019-07-25 08:57
Actually is it fixed?  I switched to hasError ages ago, but now I'm trying and failing to reproduce the error.  `myControl.errors.maxlength` doesn't generate any red squiggly for me.

**Comment by dtromblee** [comment] 2019-07-25 18:17
@thw0rted so, upon retest with `myControl.errors.required` and `.pattern` and realized I missed the `required` attribute on the input tag, they don't quite work.

`Required` mostly works, though there were some odd errors that popped up (missed capturing them and they're inconsistent unfortunately), and `pattern` fires when the pattern is wrong but doesn't seem to update when the patterns correct.

Also, I have the same vsCode language extension, and I still see squigglies strangely.

Going to stick with `.hasError` solution for the moment, and probably would still recommend the docs get updated, at least to have that as a clearer/best practice use.

**Comment by Angelo191** [comment] 2019-08-08 15:40
> I found that this error appears every time you reference a property which is defined as 'any'. Another workaround is using the bracket property annotation, clientFirstName?.errors['required'] which is also pretty stupid.

This removed the errors for me. For reference, the code worked even when the errors were outlined, I just don't like seeing red lines in my code.

**Comment by shiftgeist** [comment] 2019-08-09 12:19
Yes putting in the key in as a string removes the red lines.

But you lose features like correct spelling and auto-completion with this.

**Comment by Chrisssel** [comment] 2019-11-26 19:17
**Same issue.** 

f.email.errors.email.required Fails
!!f.email.errors.email.required Fails
f.email?.errors.email.required Fails
f?.email?.errors.email.required Fails
f.email.error.['required'] Fails
f.email?.error.['required'] Fails

**This worked for me:**

f['email'].errors.required

**Comment by ayazhafiz** [comment] 2019-11-26 19:44
Should be fixed with https://github.com/angular/angular/pull/33884.

**Closed** 2019-11-27 00:28 UTC
Labels: bug
