### ISSUE TITLE
@include (@mixin) breaks syntax highlighting in Standalone components

### ISSUE THREAD

**Issue by mparpaillon** [angular/vscode-ng-language-service#1950] opened 2023-11-02 08:14 UTC
# 🐞 bug report

### Is this a regression?

No I don't think this ever worked

### Description

Here's a mixin media query

```scss
@mixin mobile {
  @media (max-width: 600px) {
    @content;
  }
}
```

Here's a standalone component using it

```ts
@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  selector: "h-my-row",
  template: ` Something `,
  styles: [
    `
      @import "media-queries";

      :host {
        display: flex;
        flex-wrap: wrap;
        gap: var(--h-spacing-medium);

        @include mobile {
          flex-direction: column;
        }
      }
    `,
  ],
  imports: [CommonModule, FormSelectComponent],
})
export class MyRowComponent {}
```

Here's how it looks.

![Capture d’écran 2023-11-02 à 09 06 15](https://github.com/angular/vscode-ng-language-service/assets/1062115/fa287f96-d468-4198-af11-e80fc1aabd70)

So the `@include mobile`is written in white. Not great but that's ok

The real issue is when I add a second @include to it

![Capture d’écran 2023-11-02 à 09 07 00](https://github.com/angular/vscode-ng-language-service/assets/1062115/cf685b0f-9c6f-4e0b-81fc-f9db316b3d4c)

So now the second @include is properly colored (even if the first one is still white) but now the rest of the component syntax highlight seems broken. See the red brackets and the white `export class`? And everything else inside the class will be broken too.

## Bug Type

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## 🌍  Your Environment
**Angular Version:**
<pre><code>
Angular: 16.2.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.8
@angular-devkit/build-angular   16.2.6
@angular-devkit/core            16.1.8
@angular-devkit/schematics      16.2.6
@angular/cdk                    16.2.8
@angular/cli                    16.2.6
@schematics/angular             12.2.18
zone.js                         0.13.3
</code></pre>

Extension Version:
<pre><code>
v16.1.8
</code></pre>

VSCode Version:
<pre><code>
v1.83.1

</code></pre>

Operating System:
<pre><code>
Mac OS Sonoma 14.0
</code></pre>

**Comment by atscott** [comment] 2023-11-02 13:09
Look like a duplicate of https://github.com/angular/vscode-ng-language-service/issues/1255

**Closed by atscott** 2023-11-02 13:09 UTC
Labels: bug
