### ISSUE TITLE
the tooltip suggestions and references were being duplicated

### ISSUE THREAD

**Issue by Kevin-ESDM** [angular/vscode-ng-language-service#1113] opened 2021-02-16 09:50 UTC
Issue Type: <b>Bug</b>

add angular language services extension
(also enabled are TSLint, LiveServer, Code Runner and Bracket Pair Colorizer)
Extension version: 11.2.0
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (5.21GB free)|
|Process Argv|--crash-reporter-id 4977db17-fc91-405a-9cb3-6436f39958b3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt600cf:30251589

```

</details>

**Comment by SuneRadich** [comment] 2021-02-16 14:13
I see the same. The double entry disappears if I turn off 'Experimental-ivy' in the preferences. Seems VS Code has some built in logic that does the same thing?

**Comment by Kevin-ESDM** [comment] 2021-02-16 14:22
"The double entry disappears if I turn off 'Experimental-ivy' in the preferences" - this also fixed the problem for me. I think this is related to other issues too.

**Comment by atscott** [comment] 2021-02-16 20:20
Duplicate of #1110

**Closed by atscott** 2021-02-16 20:20 UTC
