### ISSUE TITLE
Publish to OpenVSX

### ISSUE THREAD

**Issue by filiptronicek** [angular/vscode-ng-language-service#1586] opened 2021-12-17 16:40 UTC
# 🚀 feature request

### Description

Unfortunately, Microsoft prohibits the usage of the MS Extension Marketplace by any other non-microsoft products. Because of this, we kindly ask you to take the ownership of your namespace in OpenVSX and publish there as well.

OpenVSX is a vendor neutral alternative to the MS Marketplace used by all other derivatives of VS Code like Gitpod, OpenVSCode, VSCodium, Theia based IDEs, and so on.

### Feature Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

### Describe the solution you'd like
The docs for publishing the extension are here: [eclipse/openvsx/wiki/Publishing-Extensions](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). Technically this should be straightforward. You get a token and call `ovsx publish` with it. For example, this is how RedHat publishes their java extension: https://github.com/redhat-developer/vscode-java/blob/5d4f8d58b8e919534800ca7bc41e8513c288f573/Jenkinsfile#L78-L82.

### Describe alternatives you've considered
We currently are trying to publish this extension in the https://github.com/open-vsx/publish-extensions repo, but this really is not ideal, because if something fails, the turnaround time is very long, the namespace isn't verified, there is a delay with new versions etc. Also, this process is broken because of https://github.com/angular/vscode-ng-language-service/issues/1585.

### Anything else relevant?

Please let me know if you are open to receive a PR contributing a release GitHub Action both to the Microsoft Marketplace and OpenVSX. I'd love to help out!

**Comment by atscott** [comment] 2021-12-17 18:45
Duplicate of #1362

**Closed by atscott** 2021-12-17 18:45 UTC
Labels: feature
