### ISSUE TITLE
Angular Language Service v15.0.3 causes intellisense to be so slow that vscode becomes unusable

### ISSUE THREAD

**Issue by mobotpsmocko** [angular/vscode-ng-language-service#1840] opened 2022-12-15 18:03 UTC
Recently I have noticed that intellisense quit working or is so slow that it either does nothing or takes so long to do anything that I have to abandon it and resort to searching. I see that this was a problem in v 11 but seems that it has re-appeared in v 15. I am working on a very large angular project that started in Angular 2 and is now on Angular 14.2.6. It seems as though the upgrade from 13 to 14 may have had an impact but am not sure. The language extension version is v15.0.3. 

Previous versions worked fine, I usually do not keep track of extension updates as I have the them set to auto update..

- [x ] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction
1) Open any component and add a few properties.
2) try to set the property by typing this. 
a small box that says loading pops up and nothing get populated for quite a long time if at all.

This also happens when you try to declare a property or field that is of a model type. It no longer suggests anything just "loading".
Go to Definition and Go to Implementation is also effected.

**Expected behavior**
you should get a list of available values to choose from.

I tried disabling all extensions and re-enabling them one by one and things broke after re-enabling the language service extension.

## 🌍  Your Environment

Angular CLI: 14.2.6
Node: 16.18.0
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 14.2.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.6
@angular-devkit/build-angular   14.2.6
@angular-devkit/core            14.2.6
@angular-devkit/schematics      14.2.6
@angular/cdk                    14.2.5
@angular/flex-layout            14.0.0-beta.41
@angular/material               14.2.5
@schematics/angular             14.2.6
rxjs                            7.5.7
typescript                      4.7.4

Extension Version:
Extension version is 15.0.3

VSCode Version:
Version: 1.74.1 (user setup)
Commit: 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
Date: 2022-12-14T10:30:51.966Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

Operating System:
Edition	Windows 10 Enterprise LTSC
Version	21H2
Installed on	‎10/‎20/‎2022
OS build	19044.2251
Experience	Windows Feature Experience Pack 120.2212.4180.0

I can provide logs if needed...just did not do it in advance

**Comment by atscott** [comment] 2022-12-15 22:27
@mobotpsmocko are you able to identify exactly what version this started happening with? That would help us narrow down the list of changes that made this happen.

**Comment by mobotpsmocko** [comment] 2023-01-17 18:00
@atscott I am not sure what version this started in. I am on 15.1.0.  It is still very slow when trying to navigate to functions or properties and the autocomplete is useless at this point. I did a profile on extensions which I am attaching if that might help. Going to try and disable all extensions again to see if I can find the one causing the issue.
[CPU-20230117T174044.153Z.zip](https://github.com/angular/vscode-ng-language-service/files/10438066/CPU-20230117T174044.153Z.zip)

**Comment by atscott** [comment] 2023-01-17 18:16
@mobotpsmocko Hmm, that is surprising since I expected #1842 to solve the issue. I'll merge #1849 and publish a pre-release version of the extension so you can see if completely disabling Angular code actions solves the issue. 

Unfortunately I'm not seeing anything in the CPU profile worth noting. There's a lot of PII info removed and I don't see any recognizable functions from the extension taking up a lot of the total time. The [issue template](https://github.com/angular/vscode-ng-language-service/issues/new) includes some instructions for enabling verbose logs that would include some useful timing information that would look like this:
```
Perf 78   [10:15:25.872] LanguageService#LsDiagnostics: {"events":{"GenerateTcb":1,"UpdateTypeCheckProgram":1},"phases":{"Unaccounted":8,"TcbUpdateProgram":18764,"TtcDiagnostics":3322,"LsDiagnostics":1783},"memory":{"TtcUpdateProgram":145915508}}
Perf 79   [10:15:26.452] LanguageService#LsComponentLocations: {"events":{},"phases":{"Unaccounted":8,"LsComponentLocations":94},"memory":{}}
Perf 80   [10:15:26.584] LanguageService#LsQuickInfo: {"events":{},"phases":{"Unaccounted":7,"TtcSymbol":563,"LsQuickInfo":5711},"memory":{}}
Perf 81   [10:15:28.661] LanguageService#LsQuickInfo: {"events":{},"phases":{"Unaccounted":6,"TtcSymbol":1,"LsQuickInfo":859},"memory":{}}
```
Could you include some of that?

**Comment by atscott** [comment] 2023-01-17 20:58
Closed automatically by tooling. Reopening until it’s determined that disabling code actions resolved the perf issues.

**Comment by arturgawlik** [comment] 2023-01-24 11:22
hey, I still face this issue on:
Angular Language Service: 15.1.0
VS Code Version: 1.74.3

Do we have any update on that?

**Comment by atscott** [comment] 2023-01-24 11:28
@arturgawlik no root causes have been identified due to a lack of reproductions, identified versions, detailed profiles, or logs. It would be helpful to have more input from users experiencing issues. See https://github.com/angular/vscode-ng-language-service/issues/1840#issuecomment-1385837488 for directions to include tracing logs.

**Comment by jpike88** [comment] 2023-01-26 05:57
I have a similar issue, and initially blamed eslint for it. But after moving from eslint to Rome, the problem persists.

See issue, I've attached traces already

https://github.com/microsoft/vscode/issues/171691

**Comment by jpike88** [comment] 2023-01-26 05:58
I should note: this isn't related to intellisense, it's far more serious. But it may be related

**Comment by atscott** [comment] 2023-01-26 17:11
@jpike88 Are you able to provide the verbose logs from the Angular Language Service?

**Comment by jpike88** [comment] 2023-01-27 03:41
I'm noticing an issue in the log, DirectoryWatcher events for files that aren't in my Angular project.

I have my workspace file in the root dir, and my angular project in a 'client' folder, my server project in a 'server' folder, and so on. Yet, the angular json, all angular related dependencies sit inside the client folder.

Shouldn't this extension be limiting what it's watching to the directory actually containing the above?

**Comment by jpike88** [comment] 2023-01-28 06:10
Ok so the above logs are expected?

**Comment by atscott** [comment] 2023-01-28 15:55
Yes

**Comment by snisar** [comment] 2023-01-30 07:53
We are having similar performance issues (2 developers). Running in a Windows 10 VM with 32GB memory. 

Our set-up is a .NET Angular project, so the Angular project sits in a ClientApp folder within the .NET project. We run 2 VS Code instances, one in the root of the project for working on the back-end and one on the ClientApp folder for Angular front-end work.

Auto-completion is really slow as mentioned above, but we find the plugin also affects the performance of the .NET back-end as well (both editing and running the app itself). Disabling the extension improves performance drastically.

**Comment by atscott** [comment] 2023-01-30 17:01
@snisar I haven't observed any performance issues on my woefully underpowered Windows 10 machine so additional information would be helpful. Unanswered questions at the moment: 

1. What is the first extension version did starts happening with?
1. https://github.com/microsoft/vscode/issues/171691 seems to indicate an issue when using tasks and a hang in the problem collector. Are you using tasks and/or a custom problemMatcher? If so, does the issue still occur if you remove the `problemMatcher`?
2. Download the [pre-release version](https://github.com/angular/vscode-ng-language-service/releases/tag/v15.2.0-next.0) and disable code actions in the Angular extension options. Does the issue still occur?
3. Can you reproduce the issue in [this project](https://github.com/atscott/ng-speed-rebuild)? In the past, we've been able to reproduce performance problems with this large example project.
4. If you disable all other extensions, is the issue still present?
5. If you use a clean install of VSCode with no custom settings, is the issue still present?

**Comment by wesselvdv** [comment] 2023-02-03 10:45
I have exactly the same issue. I have to disable the extension to be able to make use of IntelliSense.

**Comment by wesselvdv** [comment] 2023-02-03 11:29
I managed to isolate it to the combination of 2 extensions. Having both this one and (`GraphQL: Language Feature Support`)[https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql] enabled is causing the extreme slowness in intellisense.

Seems they have also noticed this: https://github.com/graphql/graphiql/issues/2063

**Comment by atscott** [comment] 2023-02-06 16:59
> For me it takes up to 10 seconds to go to a definition with this extension enabled. Seems I have another package that's causing similar issues. Disabling that one, and disabling the code actions is resolving this for me!

@wesselvdv Do you mean that downloading the pre-release version and disabling code actions solved the issue for you? Or the issue persisted until you disabled another extension as well?

**Comment by atscott** [comment] 2023-02-07 20:11
FYI, at the moment the feature to disable code actions has been reverted and _will not_ be released in the final version of 15.2 in two weeks because we have not been able to confirm that this has helped with the performance issues. 

If you are experiencing performance issues, please download the [pre-release version](https://github.com/angular/vscode-ng-language-service/releases/tag/v15.2.0-next.0) and disable code actions in the Angular extension options to see if that resolves it? If we can confirm that this helps, we can make sure the feature is added back and included in the final version.

**Comment by mobotpsmocko** [comment] 2023-02-08 13:30
At this point I have the extension disabled and still see slowness so not sure that the extension was the only culprit now.

**Comment by wesselvdv** [comment] 2023-02-12 10:31
> > For me it takes up to 10 seconds to go to a definition with this extension enabled. Seems I have another package that's causing similar issues. Disabling that one, and disabling the code actions is resolving this for me!
> 
> @wesselvdv Do you mean that downloading the pre-release version and disabling code actions solved the issue for you? Or the issue persisted until you disabled another extension as well?

The issue seems to persist until I disable another extension. Seems that a more complex interplay of certain extensions causes this slowness. Smells like some internal mechanism that's causing this, which is triggered by multiple extensions.

**Comment by BenRacicot** [comment] 2023-02-22 18:00
@wesselvdv I'm not sure if other extensions are the culprit in my case. I have disabled all extensions and still get 

> The Angular Language Service server crashed 5 times in the last 3 minutes. The server will not be restarted.
This just began happening today:

Updated vsix [v15.2.0-next.0](https://github.com/angular/vscode-ng-language-service/releases/tag/v15.2.0-next.0) per https://github.com/angular/vscode-ng-language-service/issues/1840#issuecomment-1419413823 

Same crash every restart.

Version: 1.75.1 (Universal)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:59.000Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes

**Comment by atscott** [comment] 2023-02-22 18:03
@BenRacicot This report is for slowness, not crashes. I suspect you are running in to typescript version incompatibilities (see https://github.com/angular/vscode-ng-language-service/issues/1855)

**Comment by ConnorMcDonough** [comment] 2023-03-12 04:08
I have noticed this issue too. It has made using VS code to work on my angular project unusable. I have tried everything I can think of. If I delete my node_modules folder it becomes fast again but I need my node_modules folder to properly run my app. I am not sure "whos" fault it is but I need some kind of solution, this is killing me. I have spent days trying to figure this out

**Comment by atscott** [comment] 2023-03-16 19:31
Because the extension produces diagnostics to the problems panel, there is a possibility it is affected by the VSCode memory leak with problem matchers (https://github.com/microsoft/vscode/issues/174511#event-8630512473). This has recently been fixed and is included in the insiders release (https://code.visualstudio.com/insiders/). It might be useful to check if using that version of VSCode resolves the issue.

**Comment by MTstomachTM** [comment] 2023-03-20 04:02
I'm also having similar issue, but the Angular Language Service just crashed rather than slowing intellisense. Already using VSCode insiders. I can only pinpoint the trigger on my system, which is using `clr-dropdown` or `clr-dg-column` from [Clarity Angular](https://github.com/vmware-clarity/ng-clarity). I also open an [issue](https://github.com/vmware-clarity/ng-clarity/issues/569) on their repo.
I hope this is helping.

**Comment by atscott** [comment] 2023-04-16 23:23
Closing as unable to reproduce. It’s possible upstream memory leaks (https://github.com/angular/vscode-ng-language-service/issues/1840#issuecomment-1472628450) coincided with the 15.0.3 release.

**Closed by atscott** 2023-04-16 23:23 UTC
Labels: bug
