### ISSUE TITLE
Syntax highlighting breaks after use dot inside square brackets

### ISSUE THREAD

**Issue by Zaleck-a** [angular/vscode-ng-language-service#2005] opened 2024-02-14 17:14 UTC
# 🐞 bug report

### Is this a regression?

No, it isn't

### Description

Syntax highlighting breaks after use dot inside square brackets

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

1. Go to create any DOM element in angular template
2. Inside class create a property of type object, **e.g**: `testConfiguration: {name: 'th'}`
3. Create an enum, **e.g**: ` enum BaseColumnNames {th = 'th'}`
4. Finally in the element add if directive and use the property by selecting it with enum

**Expected behavior**

It should be worked with this kind of syntax without changing the colors

## 🌍  Your Environment
**Angular Version:**
<pre><code>
16.2.12
</code></pre>

Extension Version:
<pre><code>
17.2.1
</code></pre>

VSCode Version:
<pre><code>
1.86.1 
</code></pre>

Operating System:
<pre><code>
macOs Sonoma Version 14.1.2
</code></pre>

Screenshot:
<pre><code>

<img width="470" alt="image" src="https://github.com/angular/vscode-ng-language-service/assets/68852208/4f032069-3b3e-4edd-a380-fa409cce65e3">

**Comment by atscott** [comment] 2024-02-15 20:08
Duplicate of #1989. The Vue syntax highlighting is taking over right in the middle of property binding and breaks Angular syntax highlighting. You will need to disable Vue syntax highlighting to resolve this issue.

**Closed by atscott** 2024-02-15 20:08 UTC
Labels: bug
