### ISSUE TITLE
Slow typescript and template completions with vscode-ng-language-service active

### ISSUE THREAD

**Issue by gayanper** [angular/vscode-ng-language-service#350] opened 2019-08-09 03:38 UTC
### Steps to Reproduce:

1. Open a medium size angular project with with around 18K lines of typescript code
The initialization of the language server takes around 2 mins.

2. Now open a typescript file and try to invoke code completions. That's takes around 10-20 secs to get the completion list. 

3. The second invocation is fast.

4. Now open another typescript file and invoke code completions. That's takes around 10-20 secs again

5. This is same for html files as well when completing template code.

This problem is not there if i disable the vscode-ng-language-servic plugin.

### Enviroment
VSCode Version: 1.36.1
OS Version: Windows 10 (1903)
angular.ng-template : 0.801.1

### Angular Version
Angular CLI: 7.2.3
Node: 10.15.0
OS: win32 x64
Angular: 7.2.0
... animations, cdk, common, compiler, core, forms
... platform-browser, platform-browser-dynamic, router

@angular-devkit/architect 0.12.3 (cli-only)
@angular-devkit/core 7.2.3 (cli-only)
@angular-devkit/schematics 7.2.3 (cli-only)
@schematics/angular 7.2.3 (cli-only)
@schematics/update 0.12.3 (cli-only)
rxjs 6.5.2
typescript 3.1.3

**Comment by gayanper** [comment] 2019-08-09 16:00
The improvement done at https://github.com/angular/vscode-ng-language-service/issues/339 will solve this issue.

**Comment by JohnnyDevNull** [comment] 2019-08-19 07:16
Posssible duplicate of https://github.com/angular/vscode-ng-language-service/issues/336

**Closed** 2019-08-23 19:51 UTC
