### ISSUE TITLE
Unable to fold/unfold html blocks in typescript files

### ISSUE THREAD

**Issue by Taras-R** [angular/vscode-ng-language-service#1878] opened 2023-03-10 12:07 UTC
# 🐞 bug report

### Is this a regression?

 No

### Description

 In my current project with Angular 15.1 i use inline html templates in components. First i mentioned that i can not fold and unfold html blocks in ts files, but did not pay much attention to it. When components became big enough it appeared to be more important. I opened my previous project built with Angular 15.0 and it works there like a charm. Same machine, language service. The only difference i can tell is the Angular and typescript version. Actually when workspace loads i can hover mouse over number lines and see fold/unfold icons, then they disappear while editor loads and appear again after 5sec. In Angular v15.1 they disappear and don't appear after that.

## Reproduction

1. Open VSCode
2. Wait while workspace completely loads
3. Open typescript file with component html template
4. Hover mouse over left numbered lines column

**Expected behavior**
1. User should be able to see icons to fold/unfold html blocks
2. Clicking on icon should fold/unfold code

### **Screenshots**
Newly created clean project with Angular 15.1 simple test component

![Angular-v15 1](https://user-images.githubusercontent.com/8331527/224308939-a41019ea-ea33-482c-8186-41ca4fa668ce.png)

Old project with Angular 15.0 same component

![angular-v15 0](https://user-images.githubusercontent.com/8331527/224309023-c6ddcced-9413-47fb-8339-32f0279c4299.png)

## 🌍  Your Environment
**Angular Version:**
Version that doesn't work
<pre><code>Angular CLI: 15.1.6
Node: 18.12.1
Package Manager: npm 8.19.2
OS: darwin arm64

Angular: 15.2.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.2
@angular-devkit/build-angular   15.2.2
@angular-devkit/core            15.2.2
@angular-devkit/schematics      15.1.6
@angular/cli                    15.1.6
@schematics/angular             15.1.6
rxjs                            7.8.0
typescript                      4.9.5
</code></pre>

Version that works fine
<pre><code>Angular CLI: 15.0.3
Node: 18.12.1
Package Manager: npm 8.19.2
OS: darwin arm64

Angular: 15.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.3
@angular-devkit/build-angular   15.0.3
@angular-devkit/core            15.0.3
@angular-devkit/schematics      15.0.3
@angular/cdk                    15.0.2
@angular/material               15.0.2
@schematics/angular             15.0.3
rxjs                            7.5.7
typescript                      4.8.4
</code></pre>

Extension Version:
<pre><code>v15.2.0</code></pre>

VSCode Version:
<pre><code>Version: 1.76.1</code></pre>

Operating System:
<pre><code>macOS Monterey 12.6.3</code></pre>

Extension options:
All options are unchanged

Thank you.

**Comment by atscott** [comment] 2023-03-11 00:27
I wasn't able to reproduce this myself. I'm still getting folding ranges in the inline templates in Angular projects with v15.1. Could you upload a sample project? 

Also, could you do the following: 

* go to the extension options and set the server trace level to "verbose" 
![image](https://user-images.githubusercontent.com/479713/224453160-4f26b882-8b54-4c53-868d-2d5a2c11db12.png)

* Open the "Angular Language Service" output in the output tab
* Open your component with the inline template
* Look for the `foldingRange` trace
![image](https://user-images.githubusercontent.com/479713/224453206-a578d23d-ba1e-43e3-8868-6153828b3e26.png)

**Comment by Taras-R** [comment] 2023-03-11 09:22
@atscott thank you for your response. Indeed, when i compared output for folding range it appeared that in one project there is correct response
<pre><code>Result: [
    {
        "startLine": 8,
        "endLine": 10
    },
    {
        "startLine": 7,
        "endLine": 11
    }
]</code></pre>

while another one returns just an empty array

<pre><code>Result: []</code></pre>

After tries and errors, comparing all configuration files and packages i think i figured out what causes the issue.  I downgraded typescript version installed in package.json from
<pre>"typescript": "~4.9.4"</pre>
to
<pre>"typescript": "~4.8.2"</pre>
and it works now fine, output for folding range is exactly the same. Please let me know if you need more debugging on this, thanks.

**Comment by atscott** [comment] 2023-03-13 16:29
@Taras-R Thanks for the additional information. Even when installing 4.8.2 in the example project, I can't reproduce this issue. Would you be able to provide a sample project?

**Comment by Taras-R** [comment] 2023-03-13 17:24
Sure thing @atscott here is repo https://github.com/Taras-R/angular-language-service-test Just test component added to clean application.
Typescript version is originally ~4.9.4. To make html folding downgrade it to ~4.8.2. Let me know if you need other help from my side, thanks.

**Comment by markmals** [comment] 2023-04-25 15:23
Another interesting tidbit: When you use `> Developer: Reload Window` in VS Code, you can see the code folding chevrons appear next to the template string for just a second upon reload before they disappear, so something but be overriding them

**Comment by markmals** [comment] 2023-05-04 02:07
I can confirm that this issue still persists with `ng-language-service` v16.0.0 and Angular 16.0.0. I've updated my reproduction to the latest version to demonstrate this: https://github.com/markmals/ng-code-folding-repro

**Comment by jpduckwo** [comment] 2023-05-31 03:44
We've just updated to Angular 16 and are experiencing this same bug - any advice to workaround would be much appreciated

**Comment by jpduckwo** [comment] 2023-07-06 04:40
This is so annoying, anyone got a workaround hack?

**Comment by jpduckwo** [comment] 2023-07-06 04:55
Ahh this extension seems to workaround the issue by folding on indentation only
https://marketplace.visualstudio.com/items?itemName=felicio.vscode-fold

**Comment by markmals** [comment] 2023-07-17 20:24
This is fixed for me as of [`v16.1.4`](https://github.com/angular/vscode-ng-language-service/releases/tag/v16.1.4)

**Comment by jpduckwo** [comment] 2023-07-17 23:43
Still broken for me too :-(

**Comment by Taras-R** [comment] 2023-08-10 06:29
@markmals @jpduckwo just updated Angular Language Service to v16.1.8 and it works, html is parsed and folding enabled. Angular project version v15.1.0.

**Comment by jpduckwo** [comment] 2023-08-10 22:43
Hmm still not working for me, it appears to work once after restarting viscose then quickly stops working again. Angular v16

**Comment by jpduckwo** [comment] 2023-08-14 03:55
Can anyone point me in the right direction of where this functionality is handled in the extension? It's driving me so nuts that I can't fold my code I need to try and fix this and I'll see if I can come up with a pull request

**Comment by markmals** [comment] 2023-08-14 13:57
@jpduckwo this is probably where I would start: https://github.com/angular/vscode-ng-language-service/blob/5b2cdeec63b0c99b55c673bba407370bc731a8e1/server/src/session.ts#L822-L840

**Comment by atscott** [comment] 2023-11-13 19:27
Closing as unable to reproduce at this point. I can see the issue when installing some older versions of the extension but cannot reproduce it with the latest release (17.0.2). 

If after upgrade the problem still exists in your application please [open a new issue](https://github.com/angular/vscode-ng-language-service/issues/new/choose) and follow the instructions in the issue template.

**Closed by atscott** 2023-11-13 19:27 UTC
Labels: bug

**Comment by jpduckwo** [comment] 2023-11-13 22:30
🎉 Thank you, working for me!

**Comment by Taras-R** [comment] 2023-11-14 07:55
@atscott works for me as well. Thanks.
