### ISSUE TITLE
Unable to use F2 Rename Symbol, Error: "No result. Delegating rename to the Angular Language Service."

### ISSUE THREAD

**Issue by Omzig** [angular/vscode-ng-language-service#1686] opened 2022-06-07 16:02 UTC
Issue Type: <b>Bug</b>

1) Press F2 to rename a method
2) Error "No result. Delegating rename to the Angular Language Service."

Expected symbol to rename.

Cross Repo Bug Report:
- https://github.com/microsoft/TypeScript/issues/49417

Version Info:
Extension version: 14.0.0
VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|31.81GB (16.77GB free)|
|Process Argv|C:\\Users\\matt_m\\source\\repos\\HealthMonitor\\HealthMonitorWeb --crash-reporter-id 4463eded-65a5-47b2-a227-ccf5495bd012|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by atscott** [comment] 2022-06-07 16:05
duplicate of https://github.com/angular/vscode-ng-language-service/issues/1685

**Closed as not planned by atscott** 2022-06-07 16:05 UTC
