### ISSUE TITLE
Tab-completion is much slower with Ivy enabled

### ISSUE THREAD

**Issue by magnusbakken** [angular/vscode-ng-language-service#1127] opened 2021-02-18 10:55 UTC
**Describe the bug**

In my project, IntelliSense is significantly slower when Ivy is enabled.

**To Reproduce**

I can go to any TS-file, start typing something, and wait for the suggestion box to pop up. Without Ivy enabled this happens almost instantaneously, after an initial loading time the first time you do it. With Ivy enabled it takes almost 10 seconds, every time.

**Expected behavior**

Ivy shouldn't be that much slower at providing suggestions compared to the old engine.

**Logs**

***Without Ivy***
[Info  - 11:49:53 AM] Angular language server process ID: 4632
[Info  - 11:49:53 AM] Using typescript/lib/tsserverlibrary v4.1.5 from f:\git\ProntoWeb\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 11:49:53 AM] Using @angular/language-service v11.2.0 from c:\Users\magnus.bakken\.vscode\extensions\angular.ng-template-11.2.1\node_modules\@angular\language-service\bundles\language-service.js
[Info  - 11:49:53 AM] Log file: c:\Users\magnus.bakken\AppData\Roaming\Code\logs\20210218T114948\exthost1\Angular.ng-template\nglangsvc.log
[Info  - 11:50:08 AM] Enabling VE language service for f:/git/ProntoWeb/tsconfig.json.
[nglangsvc.log](https://github.com/angular/vscode-ng-language-service/files/6002224/nglangsvc.log)

***With Ivy***
[Info  - 11:51:36 AM] Angular language server process ID: 17672
[Info  - 11:51:36 AM] Using typescript/lib/tsserverlibrary v4.1.5 from f:\git\ProntoWeb\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 11:51:36 AM] Using @angular/language-service/bundles/ivy v11.2.0 from c:\Users\magnus.bakken\.vscode\extensions\angular.ng-template-11.2.1\node_modules\@angular\language-service\bundles\ivy.js
[Info  - 11:51:36 AM] Log file: c:\Users\magnus.bakken\AppData\Roaming\Code\logs\20210218T115129\exthost1\Angular.ng-template\nglangsvc.log
[Info  - 11:51:49 AM] Enabling Ivy language service for f:/git/ProntoWeb/tsconfig.json.
[nglangsvc.log](https://github.com/angular/vscode-ng-language-service/files/6002240/nglangsvc.log)

**Screenshots**

***Without Ivy***
![tab-completion-no-ivy](https://user-images.githubusercontent.com/284189/108346617-ddeeea00-71df-11eb-9d03-3c6c7d5af9c9.gif)

***With Ivy***
![tab-completion-ivy](https://user-images.githubusercontent.com/284189/108346628-e0e9da80-71df-11eb-908c-caf43cafeab6.gif)

**Comment by andrius-pra** [comment] 2021-02-18 17:04
I have same problem. Extension works fine in external template, but not usable in typescript files. CPU profile files:
[IVY in ts file.cpuprofile.zip](https://github.com/angular/vscode-ng-language-service/files/6004571/IVY.in.ts.file.cpuprofile.zip)
[NON-IVY in ts file.cpuprofile.zip](https://github.com/angular/vscode-ng-language-service/files/6004572/NON-IVY.in.ts.file.cpuprofile.zip)

**Comment by rogerfar** [comment] 2021-02-18 21:56
Here it usually starts completely failing after an hour or so, tab completion is unbearably slow up to the point where it simply refuses. Only a vscode restart works.

**Comment by objt-mni** [comment] 2021-02-19 10:37
#1104

**Comment by atscott** [comment] 2021-02-19 17:51
duplicate of #1104

**Closed by atscott** 2021-02-19 17:51 UTC
Labels: bug
