### ISSUE TITLE
Cannot read property 'flags'

### ISSUE THREAD

**Issue by julianobrasil** [angular/vscode-ng-language-service#119] opened 2017-06-24 12:15 UTC
Recently I've been seen this error message very often:

`
[Error - 09:03:32] SERVER ERROR: Cannot read property 'flags' of undefined
TypeError: Cannot read property 'flags' of undefined
    at SymbolWrapper.members (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:48129:29)
    at findInputBinding (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:50394:40)
    at Object.visitDirectiveProperty (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:50367:32)
    at BoundDirectivePropertyAst.visit (C:\....\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:17332:24)
    at locateSymbol (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:50314:22)
    at getHover (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:50589:18)
    at LanguageServiceImpl.getHoverAt (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:50662:20)
    at C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:2705:68
    at time (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:2687:22)
    at Object.getHoverAt (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:2705:20)
[Error - 09:03:32] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'flags' of undefined
  Code: -32603 
`

I'm using 0.1.4 version and:

@angular/cli: 1.1.3
node: 6.10.3
os: win32 x64
@angular/animations: 4.2.4
@angular/common: 4.2.4
@angular/compiler: 4.2.4
@angular/compiler-cli: 4.2.4
@angular/core: 4.2.4
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.2.4
@angular/http: 4.2.4
@angular/language-service: 4.2.4
@angular/material: 2.0.0-beta.7
@angular/platform-browser: 4.2.4
@angular/platform-browser-dynamic: 4.2.4
@angular/platform-server: 4.2.4
@angular/router: 4.2.4
@angular/cli: 1.1.3

![image](https://user-images.githubusercontent.com/25405143/27508528-a507d862-58bd-11e7-8c0b-22f56607b734.png)

**Comment by chuckjaz** [comment] 2017-06-25 20:26
Do you have some example code that demonstrates this? There is not enough information in the stack trace to narrow this down.

**Comment by julianobrasil** [comment] 2017-06-25 20:35
Honestly, no. If you wish, close this issue for now, and, if I get more clues, I open a new one. Until now I really don't know whether it happens because of my code, a corrupted VSCode file or a real bug.

**Comment by marcincichocki** [comment] 2017-06-26 09:09
Same happens to me. I also experienced "baseUrl" absolute paths errors(components in templates are not recognized). Maybe those two errros are connected. Can't share code because it's private.

**Comment by chuckjaz** [comment] 2017-06-26 15:51
@julianobrasil This looks like a real bug to me. Anything you can do to help narrow it down would be appreciated. There  should be no way that the symbol could be undefined at that location. Something went wrong to set this up before this stack so the stack doesn't help much.

@marcincichocki  Same with you. If you can narrow down what might be causing it I can play around and see if I can reproduce it.

**Comment by julianobrasil** [comment] 2017-07-02 03:46
@chuckjaz, the error happens when I hover the mouse pointer over the class or flex-layout attribute. I tried uninnstall and reinstall @angular/flex-layout, but it made no difference. I built a clean project trying to reproduce it, but I didn't manage to.

What else can I do to give you more information?

**Comment by julianobrasil** [comment] 2017-07-02 11:38
@chuckjaz, I found something:
1 - If I use **`"@angular/flex-layout": "^2.0.0-beta.8"`** in **`package.json`**, it installs the **2.0.0-beta.8** and the problem occurs (even if I remove the **`node_modules`** folder before `npm install`).

2 - If I use **`"@angular/flex-layout": "github:angular/flex-layout-builds"`**, it installs the **2.0.0-beta.8** (at least it's what **`ng -v`** is showing me) and the problem goes alway and an explanation popup appears when I hover the mouse pointer over the **`fxLayout`** directive:

![image](https://user-images.githubusercontent.com/25405143/27769269-c32709b8-5efc-11e7-8478-c0bb17576629.png)

Although **`ng -v`** shows **2.0.0-beta.8** version in both installations, it's clearly not the same **@angular/flex-layout** version that is installed in the two situations.

Maybe it's not a problem with Language Service at all, but an issue with flex-layout that will be corrected in 2.0.0-beta.9. Anyway something happens in particular scenarios that I couldn't reproduce in a clean angular-cli project.

Closing this issue is up to you.

**Comment by chuckjaz** [comment] 2017-07-06 18:09
Tracking in: https://github.com/angular/angular/issues/17965

**Comment by chuckjaz** [comment] 2017-07-06 18:10
@julianobrasil I was able to reproduce this. Thanks for your help!

**Comment by jbw91** [comment] 2017-07-25 20:21
@chuckjaz Any update on this? I see angular/angular#17965 was closed 18 days ago. Would love to not have to disable this extension, but the output errors blasting into existence every time I hover over a template attribute is really wearing on me. :) Hopefully it's just a simple matter of updating the Angular version within this extension. (I think the fix is in the latest release of angular, unless I read it wrong)

**Comment by chuckjaz** [comment] 2017-08-29 00:26
Closed with 0.1.6

**Closed by chuckjaz** 2017-08-29 00:26 UTC
Labels: bug, tracking in angular
