### ISSUE TITLE
Extension broken in Nx with 17.0.0+

### ISSUE THREAD

**Issue by pm20390** [angular/vscode-ng-language-service#1973] opened 2023-11-11 23:07 UTC
### Is this a regression?
Yes

Did this behavior use to work in the previous version?
Yes, the previous version in which this bug was not present was: 16.1.8

### Description

Variables are not detected in HTML files anymore. No error highlighting or hints are visible. Seems as if the service does not run at all. Downgrading to 16.1.8 resolved the problem for Angular 15. Service still only works intermittently even after upgrading to angular 17. Restarting the language service does not fix anything.

I am in an Nx workspace, which may be pertinent to the issue.

## Bug Type
What does this bug affect

- [X] Angular Language Service VSCode extension
- [X] Angular Language Service server

## Reproduction

1. Install angular version 15
2. Launch project with 17.0.0 or 17.0.1 VS code extension.

**Expected behavior**
The service should work properly or it should be documented which angular version is required for 17.0.0 and above.

## 🌍  Your Environment
**Angular Version:**
15.2.9
Extension Version: 17.0.1

Operating System:
Mac OS Ventura 13.2.1

Logs giving the following for any file I open after upgrading to Angular 17:
Project '/dev/null/inferredProject1*' (Inferred)
	Files (8)

-----------------------------------------------
Open files: 
	FileName: /Users/{username}/workspace/{path-to-html-file}.html ProjectRootPath: undefined
		Projects: /dev/null/inferredProject1*
Err 143   [19:20:13.721] No config file for  /Users/{username}/workspace/{path-to-html-file}.html

**Comment by pm20390** [comment] 2023-11-11 23:22
By the way, upgraded my angular version and it works. I feel this should just be more clearly documented, and if there is a way to prevent VS code from "auto-updating" the version since it is breaking, that would be ideal.

**Comment by pm20390** [comment] 2023-11-13 00:24
I believe this will be fixed by https://github.com/angular/vscode-ng-language-service/pull/1972

**Comment by wimjongman** [comment] 2023-11-13 08:31
We see the same issue. When commenting these two settings, things start working again.

    //"allowJs": true,
    //"checkJs": true,

**Comment by pm20390** [comment] 2023-11-13 13:31
> We see the same issue. When commenting these two settings, things start working again.
> 
> ```
> //"allowJs": true,
> //"checkJs": true,
> ```

The solution here fixed it for me for until the angular team can get a release out:
https://github.com/angular/vscode-ng-language-service/issues/1959#issuecomment-1803991495

**Comment by atscott** [comment] 2023-11-13 16:32
Duplicate of #1959

**Closed by atscott** 2023-11-13 16:32 UTC
Labels: bug
