### ISSUE TITLE
VSCode cannot give suggestion for a member of an object written in snake_case format

### ISSUE THREAD

**Issue by IMM9O** [angular/vscode-ng-language-service#295] opened 2018-10-27 18:03 UTC
If you create object with property names written in snake_case format,  VSCode  will not show it up in suggestion list

**Comment by ayazhafiz** [comment] 2019-09-24 14:22
Are you still seeing this issue? I think it was fixed in a recent version of the language service.

**Comment by andrius-pra** [comment] 2019-09-24 16:04
I think it only fixed in v0.900.0-next.0. It's duplicate of #258.

**Comment by kyliau** [comment] 2019-11-08 23:33
Closing this, will track progress in #258

**Closed by kyliau** 2019-11-08 23:33 UTC
