### ISSUE TITLE
The Angular Language Service server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by muhammadyusuf22** [angular/vscode-ng-language-service#313] opened 2019-02-08 00:08 UTC
After I updated Visual Studio Code to Version 1.31 I got an error in the Angular Language Service as follows

"The Angular Language Service server crashed 5 times in the last 3 minutes. The server will not be restarted."

**Comment by JacobMillward** [comment] 2019-02-08 10:22
Duplicate of #312

**Closed** 2019-02-08 10:27 UTC
