### ISSUE TITLE
No intellisense for events and structural directives starting with v12

### ISSUE THREAD

**Issue by ww2406** [angular/vscode-ng-language-service#1388] opened 2021-05-31 03:32 UTC
# 🐞 bug report

### Is this a regression?

Yes, the previous version in which this bug was not present was: 11.2.14

### Description

Since the version 12 release, intellisense no longer appears for events and directives. 

## Bug Type

- [X] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction
Typing () and pressing ctrl-space yields "no suggestions". Similarly, nothing populates anymore for common directives, e.g. *ngIf.

In a template, start typing () or *ng. Press ctrl-space. You'll get "no suggestions" instead of a list of events (e.g., (click) ) or *ngIf.

**Expected behavior**

A list of possible values should be provided.

### **Logs**

I've pulled out a few lines of interest. Nothing else appeared out of the ordinary. If there is another area in particular you need to see, let me know and I can pull it out.

<pre><code>
Open files: 
	FileName: /Users/jdoe/Projects/Angular/project/src/app/home/home.component.html ProjectRootPath: undefined
		Projects: /dev/null/inferredProject1*
Err 242   [23:24:26.111] No config file for /Users/jdoe/Projects/Angular/project/src/app/home/home.component.html
Info 243  [23:24:26.524] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
Info 244  [23:24:26.533] Finishing updateGraphWorker: Project: /dev/null/inferredProject1* Version: 5 structureChanged: false Elapsed: 8.963292121887207ms
Info 245  [23:24:26.533] Different program with same set of files:: structureIsReused:: 2

</code></pre>

## 🌍  Your Environment
**Angular Version:**
<pre><code>
11.2.5
</code></pre>

However, I have experienced this in other Angular 10 and 12 projects.

Extension Version:
<pre><code>
12.0.3
</code></pre>

However, I tested every version in 12.x and all had the same issue. Last working version is 11.2.4.

VSCode Version:
<pre><code>
1.56.2
</code></pre>

Operating System:
<pre><code>
OS X 11.2.3 and Windows 10 (unsure build)
</code></pre>

**Comment by rekna1** [comment] 2021-06-01 06:36
Similar problem : angular 11 project, vscode language service:
ngIf="vm$ | async as vm" --> vm is suddenly of type any, while previously it was typed.

This structural directive supports advanced type inference, but the current compiler configuration prevents its usage. The variable 'vm' will have type 'any' as a result.

It suggests enabling stricttemplate checking but then I get (a lot) weird errors , 
- like tabindex="1" should be a number...
- a lot of trackBy functions are errors 
- ....

**Comment by atscott** [comment] 2021-06-01 16:07
@rekna1 - this is working as expected. The errors you're getting after enabling `strictTemplates` show you the places in your templates where you have not supplied the correct type for the input. If you believe any of these are incorrect, please file an issue on [angular/angular](https://github.com/angular/angular/issues/new?assignees=&labels=&template=1-bug-report.md) with a reproduction.

**Comment by atscott** [comment] 2021-06-01 23:39
@ww2406 can you provide a project that we can reproduce this issue with?

**Comment by rekna1** [comment] 2021-06-02 05:39
@atscott : can I get code completion working again with enabling strictTemplates ? This was working a few days ago ...

**Comment by atscott** [comment] 2021-06-02 16:42
@rekna1 potentially. The specifics of your issue are still not entirely explained so I can't say for sure. But yes, generally enabling `strictTemplates` ensures the compiler produces the most accurate type information for your templates. Not having `strictTemplates` means that there will be incorrect typings (generally becoming `any`) that will not be able to provide completions (because they're type `any`).

**Comment by atscott** [comment] 2021-06-03 22:47
Investigated this some more today and can confirm that this is indeed an issue in all projects with no need for any special configuration to reproduce.

**Comment by lincolnthree** [comment] 2021-06-04 14:03
We are also experiencing issues like this with custom pipes. This pipe was working just fine previously, but now everything that gets returned is typed as "null". I tried playing with the method signatures (which are the same as the `async` pipe), but it is not working:

![image](https://user-images.githubusercontent.com/362329/120813168-a6504780-c51b-11eb-8dae-d4085aae7b9f.png)

```

  transform<U>(
    potentialObservable: null,
    config?: string | Observable<string>,
    renderCallback?: NextObserver<U>
  ): null;
  transform<U>(
    potentialObservable: undefined,
    config?: string | Observable<string>,
    renderCallback?: NextObserver<U>
  ): undefined;
  transform<U>(
    potentialObservable: ObservableInput<U>,
    config?: string | Observable<string>,
    renderCallback?: NextObserver<U>
  ): U;
  transform<U>(
    potentialObservable: ObservableInput<U> | null | undefined,
    config: string | Observable<string> | undefined,
    renderCallback?: NextObserver<U>
  ): U | null | undefined {
    //    ... do the work
    return this.renderedValue as U;
  }
```

This pipe is imported via a shared module:

```
const declarations = [
  // ...
  PushPipe
  // ...
];

@NgModule({
  declarations: [...declarations],
  imports: [
    CommonModule
  ],
  providers: [],
  exports: [...declarations]
})
export class TdCommonAngularModule {
  static forRoot(): ModuleWithProviders<TdCommonAngularModule> {
    return {
      ngModule: TdCommonAngularModule,
      providers: [ ]
    };
  }
}
```

**Closed** 2021-06-08 23:50 UTC
Labels: bug
