### ISSUE TITLE
Autocomplete doesn't work `as` keyword

### ISSUE THREAD

**Issue by kohashi** [angular/vscode-ng-language-service#1216] opened 2021-03-18 16:07 UTC
**Describe the bug**

When the library uses `as` in `*ngIf`, the type inference doesn't work and it inference  as `any`.
I faced this when using async pipes, but it seems async pipes are not required.

Simply.
```
<div *ngIf="heros[0] as hero">
   <!--  hero is `any`. autocomplete doesn't work. -->
</div>
```

async, I actually faced. 
```
<div *ngIf="hero$ as hero">
   {{ hero.name }} <!-- autocomplete not works. -->
</div>
```

Almost same as #255.

**To Reproduce**

Just install VSCode and Angular Language Service. 
And copy above.

**Expected behavior**

The type is retained even after the `as` keyword variable.
Autocomplete works on `as` keyword.

**Comment by atscott** [comment] 2021-03-19 17:58
duplicate of #1155

**Closed by atscott** 2021-03-19 17:58 UTC
Labels: bug
