### ISSUE TITLE
ngFor with slice pipe loses object type

### ISSUE THREAD

**Issue by timrayers** [angular/vscode-ng-language-service#345] opened 2019-07-15 16:18 UTC
**card.component.ts:**

```
...
availabilityArray = [
  { available: true },
  { available: false },
  { available: true },
  { available: false }
];
```

**card.component.html**
```
<ng-container *ngFor="let element of availabilityArray | slice:0:10">
    {{ element.available }}
</ng-container>
  ```

This produces the following error and intellisense does not list the identifier: 
> Identifier 'available' is not defined. 'T' does not contain such a member

```
<ng-container *ngFor="let element of availabilityArray">
    {{ element.available }}
</ng-container>
  ```

Removing the `slice` attribute of the ngFor suppresses the error and intellisense works.

Why does using `slice` stop intellisense from working, and shows the error?

**Comment by LoaderB0T** [comment] 2019-07-23 08:31
I also have problems with intellisense and ngFor.

I have an ngFor inside of an ngIf.

Intellisense is not working on the iterator variable.

Example:
`<div *ngIf="vm && vm.configuredSourceColumns">
  <div *ngFor="let sourceColumnVM of vm.configuredSourceColumns">
    <span>
      {{sourceColumnVM.name}}
    </span>
  </div>
</div>`

the property 'name' of sourceColumnVM is seemingly unknown to intellisense. Instead I always get '.ngForm' as only auto completion suggestion.....

However I do get squiggly error lines when I try to use a non-existing property.

**Comment by andrius-pra** [comment] 2019-07-23 21:07
> However I do get squiggly error lines when I try to use a non-existing property.

Did you try to add space before '}}'? Do you use CRLF (Windows) line endings? 

Angular compiler [replaces CRLF line endings to '\n'](https://github.com/angular/angular/blob/master/packages/compiler/src/ml_parser/lexer.ts#L168) and language service doesn't have exact position to provide completions.
workaround: add space before closing interpolation

![test](https://user-images.githubusercontent.com/17968027/61746143-b2a5de00-ada3-11e9-844c-99aa14c41211.gif)

**Comment by LoaderB0T** [comment] 2019-07-23 21:52
> workaround: add space before closing interpolation

I will try this tomorrow, thanks alot!
I guess a more permanent solution would be to switch to \n Unix-style line endings locally?

Is there any possibility this can be fixed even for Windows-style line endings?

**Comment by frankiee88** [comment] 2019-08-12 09:34
> **card.component.ts:**
> 
> ```
> ...
> availabilityArray = [
>   { available: true },
>   { available: false },
>   { available: true },
>   { available: false }
> ];
> ```
> 
> **card.component.html**
> 
> ```
> <ng-container *ngFor="let element of availabilityArray | slice:0:10">
>     {{ element.available }}
> </ng-container>
> ```
> 
> This produces the following error and intellisense does not list the identifier:
> 
> > Identifier 'available' is not defined. 'T' does not contain such a member
> 
> ```
> <ng-container *ngFor="let element of availabilityArray">
>     {{ element.available }}
> </ng-container>
> ```
> 
> Removing the `slice` attribute of the ngFor suppresses the error and intellisense works.
> 
> Why does using `slice` stop intellisense from working, and shows the error?

Same issue here. Removing 'slice' suppresses the 'errors'. Any idea when this might be fixed?

**Comment by zabuvay** [comment] 2019-08-31 07:01
> 
> 
> > However I do get squiggly error lines when I try to use a non-existing property.
> 
> Did you try to add space before '}}'? Do you use CRLF (Windows) line endings?
> 
> Angular compiler [replaces CRLF line endings to '\n'](https://github.com/angular/angular/blob/master/packages/compiler/src/ml_parser/lexer.ts#L168) and language service doesn't have exact position to provide completions.
> workaround: add space before closing interpolation
> 
> ![test](https://user-images.githubusercontent.com/17968027/61746143-b2a5de00-ada3-11e9-844c-99aa14c41211.gif)

The problem is not in this. I have the same issue. With using slice we lose object type.

**Comment by webcourse-ng** [comment] 2019-09-05 09:07
Ditto here. After spending a couple hours completing type definitions for every variable involved, checking types double and tripple times, nothing helped.

Removing slice is the only thing that gets rid of the "Identifier is not defined" errors. Uff, I guess the upside of the error is that it forced me to type the code more completely.

**Comment by JeffBeltran** [comment] 2019-09-10 15:16
here from stackoverflow just wanted to chime in as well

https://stackoverflow.com/questions/57828725/angular-language-service-pipe-causes-identifier-not-defined-error

**Comment by wrkettlitz** [comment] 2019-10-22 11:45
It doesn't seem to support generics, i always get errors when i use generics

**Closed** 2019-10-29 21:48 UTC
