### ISSUE TITLE
Renaming template reference variables

### ISSUE THREAD

**Issue by amitbeck** [angular/vscode-ng-language-service#829] opened 2020-06-23 14:35 UTC
**Is your feature request related to a problem? Please describe.**

I sometimes find myself needing to rename a template reference variable.
Attempting to rename a template reference variable in VS Code results in a 'No result' toast.

**Describe the solution you'd like**

I'd love it if I were able to rename template reference variables using Angular Language Service.
It could also be nice to support input, output and maybe even selector renaming.

**Describe alternatives you've considered**

The only alternative is manually renaming the template reference variable.

**Additional context**

![Screenshot from 2020-06-23 17-30-36](https://user-images.githubusercontent.com/22454058/85416690-72347e80-b577-11ea-9934-6eb809b5c5dd.png)
VS Code already supports *attempting* to rename tokens such as template reference variables.

**Comment by ayazhafiz** [comment] 2020-06-25 15:52
Thanks for the report. this is a dupe of #29, please see that issue for updates.

**Closed by ayazhafiz** 2020-06-25 15:52 UTC
Labels: feature
