### ISSUE TITLE
Notification handler 'textDocument/didSave' failed with message

### ISSUE THREAD

**Issue by andrezsegovia** [angular/vscode-ng-language-service#205] opened 2017-12-23 02:32 UTC
Hi

I have the next issue when i try to save a file.

I'm using VSCode 1.19.0 and Angular Language Service 0.1.7

```
Search path: /home/asc-dev/wksp-personal/demos/DataBaseManager/src/app
Config file name: /home/asc-dev/wksp-personal/demos/DataBaseManager/tsconfig.json
Angular Language Service: 5.0.0-beta.5
TypeScript: 2.4.2
SERVER ERROR: watch /home/asc-dev/wksp-personal/demos/DataBaseManager/node_modules/@angular/core/src/view ENOSPC
Error: watch /home/asc-dev/wksp-personal/demos/DataBaseManager/node_modules/@angular/core/src/view ENOSPC
    at exports._errnoException (util.js:1050:11)
    at FSWatcher.start (fs.js:1410:19)
    at Object.fs.watch (fs.js:1436:11)
    at addDirWatcher (/home/asc-dev/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/typescript/lib/typescript.js:3724:35)
    at Object.addFile (/home/asc-dev/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/typescript/lib/typescript.js:3734:21)
    at Object.watchFile (/home/asc-dev/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/typescript/lib/typescript.js:3893:60)
    at ProjectServiceHostImpl.watchFile (/home/asc-dev/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:36:23)
    at ProjectService.openFile (/home/asc-dev/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1361:50)
    at Project.openReferencedFile (/home/asc-dev/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:723:36)
    at LSHost.getScriptInfo (/home/asc-dev/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:573:39)
    at LSHost.getScriptSnapshot (/home/asc-dev/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:511:31)
    at HostCache.createEntry (/home/asc-dev/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/typescript/lib/typescript.js:88874:44)
    at HostCache.getOrCreateEntryByPath (/home/asc-dev/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/typescript/lib/typescript.js:88895:24)
[Error - 9:22:16 PM] Notification handler 'textDocument/didSave' failed with message: watch /home/asc-dev/wksp-personal/demos/DataBaseManager/node_modules/@angular/core/src/view ENOSPC
```

**Comment by Afbcary** [comment] 2017-12-29 17:32
I have the same issue. It doesn't seem to cause any problems but it constantly opens the OUTPUT window which is very annoying. Haven't found a way to disable that window interrupting my work.

**Comment by chuckjaz** [comment] 2017-12-30 18:33
This is a duplicate of #176

**Closed by chuckjaz** 2017-12-30 18:33 UTC
