### ISSUE TITLE
How to stop watching the dist folder

### ISSUE THREAD

**Issue by pfeigl** [angular/vscode-ng-language-service#224] opened 2018-01-25 16:32 UTC
Angular Lanuage Service seems to watch my dist folder and I cannot find a way to stop the plugin from doing that.

My main problem is, that it also very often locks the files which are created and often fastly deleted again and I get errors like 
```
BUILD ERROR
EPERM: operation not permitted, unlink 'C:\Development\...
```

As soon as I disable the language service completly, the errors go away.

**Comment by mpscheidt** [comment] 2018-09-05 07:46
I can confirm this behaviour.

It prevents ng-packagr from executing successfully, since the Angular Language Service plugin locks files in the dist/src folder.

**Comment by pfeigl** [comment] 2018-09-05 10:49
I was actually also running into the problem while using ng-packagr.

**Comment by e-davidson** [comment] 2019-02-05 01:01
https://github.com/ng-packagr/ng-packagr/issues/837

**Comment by kyliau** [comment] 2019-11-11 22:12
This is fixed in the new extension, which will be released in conjunction with Angular v9.
Meanwhile please try out the RC version by downloading the binary from the Release page.

**Comment by kyliau** [comment] 2019-11-25 19:54
The new extension is now live. Please download it from https://marketplace.visualstudio.com/items?itemName=Angular.ng-template
I'd like to close this issue for now. Please open a new issue for any lingering bugs, thank you!

**Closed by kyliau** 2019-11-25 19:54 UTC
