### ISSUE TITLE
Support for Custom Elements 

### ISSUE THREAD

**Issue by break-stuff** [angular/vscode-ng-language-service#1986] opened 2024-01-04 23:35 UTC
**Is your feature request related to a problem? Please describe.**

# 🚀 feature request

### Description
 
There doesn't seem to be a way to extend the language server for custom elements/web components.

### Feature Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [x] Angular Language Service server

### Describe the solution you'd like
 
Vue and JSX templates provide an interface that can be extended to include additional tag names, attributes/available values, and documentation. Something consistent with that would be very helpful.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by atscott** [comment] 2024-01-04 23:42
Duplicate of https://github.com/angular/angular/issues/12045

**Closed by atscott** 2024-01-04 23:42 UTC
Labels: feature
