### ISSUE TITLE
No Intellisense with elvis operator

### ISSUE THREAD

**Issue by nagarsuresh** [angular/vscode-ng-language-service#1391] opened 2021-06-01 18:57 UTC
Intellisense is not working with elvis operator.  Without elvis operator it does provide suggestions.

# 🐞 bug report

### Is this a regression?
Yes.  used work in earlier versions.

![2021-06-01 11 56 59](https://user-images.githubusercontent.com/7144356/120376282-8c6ef480-c2d0-11eb-90e6-f8ca2a27cd19.gif)

**Comment by atscott** [comment] 2021-06-01 19:13
@nagarsuresh - Can you share your `tsconfig`? This is likely working as intended. I suspect your compiler options have configured the compiler to type the safe navigations as `any` (`strictSafeNavigationTypes` is set to `false` unless you have `"strictTemplates": true` or `"strictSafeNavigationTypes": true`)

**Comment by nagarsuresh** [comment] 2021-06-01 23:08
@atscott Thanks for the reply.  Below is my tsconfig.json

`{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ]
  }
}
`

tsconfig.app.json
`{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": []
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ]
}
`

**Comment by atscott** [comment] 2021-06-01 23:38
@nagarsuresh I see. So you'll want to add `"angularCompilerOptions"` to your `tsconfig`. Preferably set `"strictTemplates": true` and fix any errors that you see as a result (these are real errors that you've currently configured the compiler to ignore). If that's too much for your app right now, maybe set just `"fullTemplateTypeCheck": true` and `"strictSafeNavigationTypes": true`.

Closing as working as expected.

**Closed by atscott** 2021-06-01 23:38 UTC
Labels: needs clarification, needs repro
