### ISSUE TITLE
Extension stops working after 30-60 minutes

### ISSUE THREAD

**Issue by devhus** [angular/vscode-ng-language-service#1399] opened 2021-06-04 07:56 UTC
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was:  11.2.14

### Description

Just finished upgrading my project to Angular 12 with the Ng Language Service v12 the IntelliSense starts getting buggy,
After few minutes from **Initializing Angular Language Features** the awareness of variables and methods in the component's template stopped working
Hovering on a variable shows its type, but trying to get the props of that variable won't show anything like the image below.
Note that, reloading VSCode or restarting it will fix the issue for a few minutes after the extension is initialized, then the issue will start to take effect.

Also enabling the **Legacy View Engine** option won't fix it, it will even bug it more taking away those few minutes before the issue happens.

## Bug Type

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

### **Logs**
(yes there is a lot of wired white spaces added to the logs for no reason, wasn't me who added it)
[nglangsvc.log](https://github.com/angular/vscode-ng-language-service/files/6596676/nglangsvc.log)
[nglangsvc.log](https://github.com/angular/vscode-ng-language-service/files/6596890/nglangsvc.log)

### **Screenshots**

![vscode](https://user-images.githubusercontent.com/58523735/120765452-83bd2f00-c519-11eb-92c6-53973b4e77a3.gif)

![vscode1](https://user-images.githubusercontent.com/58523735/120765860-ee6e6a80-c519-11eb-96b5-0304be87f4dc.gif)

when the issue happens and tries to **Go to definition** of a variable:
![unknown](https://user-images.githubusercontent.com/58523735/120767304-5ffae880-c51b-11eb-940b-5cb9f1589c6b.png)

## 🌍  Your Environment
**Angular Version:**
<pre> <code>
Angular CLI: 12.0.3
Node: 14.16.1
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.0.3
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.3
@angular-devkit/build-angular   12.0.3
@angular-devkit/core            12.0.3
@angular-devkit/schematics      12.0.3
@schematics/angular             11.2.14
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

Extension Version:
<pre><code>
12.0.4
</code></pre>

VSCode Version:
<pre>
<code>
Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042
</code></pre>

Operating System:
<pre><code>
Microsoft Windows 10 Pro
Version	10.0.19042 Build 19042
</code></pre>

package.json:
<pre><code>
{
  "name": "bnaturalia-frontend",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "ng-s": "node --max_old_space_size=8048 ./node_modules/@angular/cli/bin/ng serve"
  },
  "private": true,
  "dependencies": {
    "@angular-slider/ngx-slider": "^2.0.3",
    "@angular/animations": "^12.0.3",
    "@angular/cdk": "^12.0.3",
    "@angular/common": "^12.0.3",
    "@angular/compiler": "^12.0.3",
    "@angular/core": "^12.0.3",
    "@angular/forms": "^12.0.3",
    "@angular/localize": "^12.0.3",
    "@angular/platform-browser": "^12.0.3",
    "@angular/platform-browser-dynamic": "^12.0.3",
    "@angular/router": "^12.0.3",
    "@ckeditor/ckeditor5-angular": "^2.0.1",
    "@ckeditor/ckeditor5-autosave": "^27.1.0",
    "@ckeditor/ckeditor5-build-classic": "^27.1.0",
    "@ckeditor/ckeditor5-build-inline": "^27.1.0",
    "@gilsdav/ngx-translate-router": "^3.1.6",
    "@gilsdav/ngx-translate-router-http-loader": "^1.1.2",
    "@mdi/font": "^5.9.55",
    "@ng-bootstrap/ng-bootstrap": "^9.1.0",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "@schematics/angular": "^11.2.14",
    "@sweetalert2/ngx-sweetalert2": "^9.0.0",
    "@syncfusion/ej2-angular-filemanager": "^19.1.66",
    "apexcharts": "^3.26.0",
    "bootstrap": "^5.0.0-beta3",
    "country-state-city": "^2.1.0",
    "currency-list": "^1.0.6",
    "iso-country-currency": "^0.5.3",
    "ng-apexcharts": "^1.5.9",
    "ngx-bootstrap-icons": "^1.4.5",
    "ngx-rangeslider-component": "^1.0.6",
    "rxjs": "~6.6.0",
    "sweetalert2": "^10.16.0",
    "tslib": "^2.2.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^12.0.3",
    "@angular/cli": "^12.0.3",
    "@angular/compiler-cli": "^12.0.3",
    "@angular/language-service": "^12.0.3",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.20.14",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "^6.3.3",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "^4.2.4"
  }
}
</code></pre>

**Comment by CalinaCristian** [comment] 2021-06-04 13:30
I've noticed that if you go to Extension Settings and check the legacy view engine it works with latest.
![image](https://user-images.githubusercontent.com/9513641/120808807-1c6fa100-c552-11eb-8533-a5ffe5b03789.png)

**Comment by ashwingairola** [comment] 2021-06-07 20:22
In my experience, this is also happening for input properties.

**Comment by xantari** [comment] 2021-06-09 23:29
I'm also receiving this issue, revert to 11.2.14 for the time being. Intellisense is very broken in 12.0.4 in templates.

**Comment by atscott** [comment] 2021-06-10 00:12
@xantari @ashwingairola @devhus are any of you able to provide a project with a set of steps that reproduces this issue? I don't see anything in the logs. What could also be helpful is enabling either `verbose` or `messages` of the `trace: server` extension options and pasting some of the output here

![Screen Shot 2021-06-09 at 5 09 32 PM](https://user-images.githubusercontent.com/479713/121445084-9edad500-c945-11eb-995d-eddfa73ef014.png)

It should look like this:
![image](https://user-images.githubusercontent.com/479713/121444920-473c6980-c945-11eb-8fe8-3da324db06fb.png)

This trace shows the requests going from the client to the Angular language server as well as the response back. If something is breaking there, hopefully we can see it in the output (i.e. messages aren't being sent for some reason).

**Comment by xantari** [comment] 2021-06-10 01:18
Example from 12.0.4 Angular Language Service in the attached project.

```
[Trace - 8:02:36 PM] Received response 'textDocument/hover - (12)' in 1ms.
No result returned.


[Trace - 8:03:44 PM] Sending request 'textDocument/hover - (13)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/TFS/APM/src/app/product-list/product-list.component.html"
    },
    "position": {
        "line": 17,
        "character": 39
    }
}


[Trace - 8:03:44 PM] Received response 'textDocument/hover - (13)' in 1ms.
No result returned.


[Trace - 8:03:45 PM] Sending request 'textDocument/hover - (14)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/TFS/APM/src/app/product-list/product-list.component.html"
    },
    "position": {
        "line": 17,
        "character": 45
    }
}


[Trace - 8:03:45 PM] Received response 'textDocument/hover - (14)' in 1ms.
No result returned.


[Trace - 8:03:46 PM] Sending request 'textDocument/hover - (15)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/TFS/APM/src/app/product-list/product-list.component.html"
    },
    "position": {
        "line": 17,
        "character": 40
    }
}


[Trace - 8:03:46 PM] Received response 'textDocument/hover - (15)' in 1ms.
No result returned.


[Trace - 8:03:46 PM] Sending request 'textDocument/hover - (16)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/TFS/APM/src/app/product-list/product-list.component.html"
    },
    "position": {
        "line": 17,
        "character": 42
    }
}


[Trace - 8:03:46 PM] Received response 'textDocument/hover - (16)' in 0ms.
No result returned.


[Trace - 8:03:46 PM] Sending request 'textDocument/hover - (17)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/TFS/APM/src/app/product-list/product-list.component.html"
    },
    "position": {
        "line": 17,
        "character": 43
    }
}


[Trace - 8:03:46 PM] Received response 'textDocument/hover - (17)' in 1ms.
No result returned.


[Trace - 8:03:47 PM] Sending request 'textDocument/hover - (18)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/TFS/APM/src/app/product-list/product-list.component.html"
    },
    "position": {
        "line": 17,
        "character": 36
    }
}


[Trace - 8:03:47 PM] Received response 'textDocument/hover - (18)' in 0ms.
No result returned.


[Trace - 8:03:48 PM] Sending request 'textDocument/codeLens - (19)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/TFS/APM/src/app/product-list/product-list.component.html"
    }
}


[Trace - 8:03:48 PM] Received response 'textDocument/codeLens - (19)' in 0ms.
Result: [
    {
        "range": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 0,
                "character": 0
            }
        },
        "data": {
            "uri": "file:///c%3A/TFS/APM/src/app/product-list/product-list.component.html"
        }
    }
]
```

Global angular tools installed are 12.0.3. Local project version is 11.2.0:

I know this because of this warning:
Your global Angular CLI version (12.0.3) is greater than your local version (11.2.0). The local Angular CLI version is used.

To repro, hover over products in product-list.component.html using 12.0.4 of the angular language tools and you won't get any intellisense.

Revert back to 11.2.14 and hover over the products item and you will get intellisense when you hover over the "products" variable in product-list.component.html

At 11.2.14 hovering over products I see the following:

![image](https://user-images.githubusercontent.com/6610039/121449397-5d572380-c95f-11eb-95b9-47816e0315ac.png)

This is the log from 11.2.14 where it works, you can see the output is a bit different:

```
[Trace - 8:15:03 PM] Received response 'textDocument/hover - (5)' in 7ms.
Result: {
    "contents": [
        {
            "language": "typescript",
            "value": "(property) ProductListComponent.products: any[]"
        }
    ],
    "range": {
        "start": {
            "line": 33,
            "character": 35
        },
        "end": {
            "line": 33,
            "character": 43
        }
    }
}


[Trace - 8:15:18 PM] Sending request 'textDocument/hover - (6)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/TFS/APM/src/app/product-list/product-list.component.html"
    },
    "position": {
        "line": 33,
        "character": 36
    }
}


[Trace - 8:15:18 PM] Received response 'textDocument/hover - (6)' in 5ms.
Result: {
    "contents": [
        {
            "language": "typescript",
            "value": "(property) ProductListComponent.products: any[]"
        }
    ],
    "range": {
        "start": {
            "line": 33,
            "character": 35
        },
        "end": {
            "line": 33,
            "character": 43
        }
    }
}
```

You can see in the above log it seems to be working as the log output is different.

I've also noticed that I can get it to break in 11.2.14 as well by turning on the "angular.experimental-ivy": true flag. Did 12.0.4 of the language service perhaps turn that on by default and might explain why it's broken in 12.0.4, and also broken in 11.2.14 when the IVY flag is turned on?

[APM.zip](https://github.com/angular/vscode-ng-language-service/files/6627713/APM.zip)

**Comment by atscott** [comment] 2021-06-10 02:29
@xantari yes, Ivy became the default in v12. Can you share your `tsconfig.json`? The issue for your project here may be that you need to enable `strictTemplates`

**Comment by xantari** [comment] 2021-06-10 11:33
@atscott The config is in the APM.zip project example I attached above.

**Comment by atscott** [comment] 2021-06-10 15:13
@xantari Ah, I see that now (I was on my phone last night after hours). I'm able to reproduce your issue as well in that project so I will be investigating this today. Thanks!

**Comment by devhus** [comment] 2021-06-10 16:18
> @xantari yes, Ivy became the default in v12. Can you share your `tsconfig.json`? The issue for your project here may be that you need to enable `strictTemplates`

Its enabled, i will be able to share a bugged project with you today's night if you still need it.

**Comment by atscott** [comment] 2021-06-10 16:28
@devhus - I think that would be helpful. I have identified the issue with @xantari's project. The first `div` isn't closed. Adding another close `</div>` at the end of the template fixes things. That said, our visitor logic should handle this case. It would be good to know if your issue is the same or something different.

**Comment by xantari** [comment] 2021-06-10 22:21
@atscott Thanks for the pointer on the missing closed DIV, interesting that TSLint didn't highlight that, and that it wasn't a problem in the previous version. Ivy is a bit stricter it appears.

Sorry for the unrelated question, but what the heck do I have to do to VS Code to tell me i have malformed HTML!?!

**Comment by atscott** [comment] 2021-06-10 22:40
@xantari 😆  no problem! I did a quick search and it looks like there are a few extensions like [htmlhint](https://marketplace.visualstudio.com/items?itemName=mkaufman.HTMLHint) that would have caught this. I played around with the options and it seems like for your project this would work:
```
  "htmlhint.options": {
    "tagname-lowercase": false,
    "attr-lowercase": false,
    "attr-value-double-quotes": false,
    "doctype-first": false,
    "tag-pair": true
  },
```
Personally, I think `"attr-value-double-quotes"` should be true but that's really up to you and your project :)

**Comment by devhus** [comment] 2021-06-11 12:46
> @devhus - I think that would be helpful. I have identified the issue with @xantari's project. The first `div` isn't closed. Adding another close `</div>` at the end of the template fixes things. That said, our visitor logic should handle this case. It would be good to know if your issue is the same or something different.

that is a sample project(removed a lot of base code from the original project), it has some memory leak bug as well (in case that was what is causing the issue)
and as I mentioned in the report above, the issue does not happen right away in the project. after spending some time working on the issue will start to randomly happen but not before few minutes after Angular Language Features being Initialized.

[t.zip](https://github.com/angular/vscode-ng-language-service/files/6638425/t.zip)

**Comment by atscott** [comment] 2021-06-11 17:45
@devhus - I played around with the example project and wasn't able to reproduce the issue. There was a fix for autocompletion in the release yesterday. Could you update your extension to see if that resolves your issue?

**Comment by devhus** [comment] 2021-06-12 13:39
> @devhus - I played around with the example project and wasn't able to reproduce the issue. There was a fix for autocompletion in the release yesterday. Could you update your extension to see if that resolves your issue?

unfortunately, the issue was not fixed yet.

**Comment by devhus** [comment] 2021-06-12 14:34
> @devhus - I played around with the example project and wasn't able to reproduce the issue. There was a fix for autocompletion in the release yesterday. Could you update your extension to see if that resolves your issue?

You need to leave it open for some time. Open the project through ``workspace.code-workspace`` file then ``ng serve`` it, and leave the project opened in your taskbar for about 30-60 minutes and the issue will randomly happen, hopfully.
Unfortunately, the issue was not fixed for me with the last update.

**Comment by Nness** [comment] 2021-06-15 20:16
@atscott Is `strictTemplates` required for language service to function correctly for Angular 12 project?

**Comment by atscott** [comment] 2021-06-15 20:27
@Nness No, but the answer you're probably looking for is "yes". The language service has the same understanding of the program as the compiler. Any option which configures the compiler to ignore certain types, including `strictTemplates: false`,  will affect what information you get from the language service. It's "correct" in all cases but may not be "complete" information.

P.S. In the future, an existing GitHub issue is not the right forum for questions.

**Comment by atscott** [comment] 2021-06-15 20:30
@devhus - I have left the application running with `ng serve` for the past two days and have not encountered an issue. I'll leave this open for now to see if others are experiencing the same and can provide a reproduction but will probably end up closing it at some point in the future since we can't reproduce it.

**Comment by devhus** [comment] 2021-06-15 20:45
> @devhus - I have left the application running with `ng serve` for the past two days and have not encountered an issue. I'll leave this open for now to see if others are experiencing the same and can provide a reproduction but will probably end up closing it at some point in the future since we can't reproduce it.

Well, do you notice any memory leak in the project? (Nodejs runtime thread in your task manager will have about 1.5GB ram usage as you're serving the project and the memory usage keep increasing until your serve session is crashed)
if you don't have any issues with the memory causing the served session to be shutdown and throwing this error ``JavaScript heap out of memory`` while running ``ng serve`` then the real issue might be in my environment(pc win-10) but, I have no idea how to check this out.

**Comment by atscott** [comment] 2021-06-15 21:57
@devhus It sounds like this may potentially be https://github.com/angular/angular-cli/issues/20801. If that's the case, then the issue is with the cli and is being tracked there.

**Comment by devhus** [comment] 2021-06-27 12:58
> @devhus It sounds like this may potentially be [angular/angular-cli#20801](https://github.com/angular/angular-cli/issues/20801). If that's the case, then the issue is with the cli and is being tracked there.

the memory leak issue was fixed in ng cli, but the ng language service issue still going on.

**Comment by jpike88** [comment] 2021-07-21 22:30
may also be related to https://github.com/angular/vscode-ng-language-service/issues/1421

**Closed** 2021-07-28 23:03 UTC
Labels: bug, needs clarification, needs repro
